import { CORE_RULESET } from './coreRules.js?v=0.5.3.0';
import { ITALIAN_WARS_SUPPLEMENT } from './supplements/italianWars.js?v=0.5.3.0';
const SUPPLEMENTS=Object.freeze({[ITALIAN_WARS_SUPPLEMENT.id]:ITALIAN_WARS_SUPPLEMENT});
export function listSupplements(){return Object.values(SUPPLEMENTS).map(s=>({id:s.id,name:s.name,version:s.version,description:s.description}));}
export function ensureScenarioRuleset(scenario){if(!scenario)return{core:CORE_RULESET.id,supplement:ITALIAN_WARS_SUPPLEMENT.id,supplementVersion:ITALIAN_WARS_SUPPLEMENT.version};scenario.ruleset||={};scenario.ruleset.core||=CORE_RULESET.id;scenario.ruleset.supplement||=ITALIAN_WARS_SUPPLEMENT.id;const selected=SUPPLEMENTS[scenario.ruleset.supplement]||ITALIAN_WARS_SUPPLEMENT;scenario.ruleset.supplement=selected.id;scenario.ruleset.supplementVersion||=selected.version;return scenario.ruleset;}
export function getSupplement(id){return SUPPLEMENTS[id]||ITALIAN_WARS_SUPPLEMENT;}
export function getEffectiveRuleset(scenario){const selection=ensureScenarioRuleset(scenario),supplement=getSupplement(selection.supplement);return{id:`${CORE_RULESET.id}+${supplement.id}`,core:CORE_RULESET,supplement,unitLibrary:supplement.unitLibrary||[],capabilities:{...CORE_RULESET.capabilities,...(supplement.capabilities||{})},layers:[{kind:'core',id:CORE_RULESET.id,name:CORE_RULESET.name,source:CORE_RULESET.source},{kind:'supplement',id:supplement.id,name:supplement.name,source:supplement.source},{kind:'scenario',id:'scenario-overrides',name:'Scenario Overrides',source:'Designer-accepted scenario rules'}]};}
export function profileForText(text,scenarioOrRuleset){const rs=scenarioOrRuleset?.supplement?scenarioOrRuleset:getEffectiveRuleset(scenarioOrRuleset);for(const [profile,pattern] of rs.supplement.profileMatchers||[])if(pattern.test(text))return profile;return null;}
export function effectiveArmyAssetPolicy(scenario,faction){const rs=getEffectiveRuleset(scenario),base=rs.supplement.armyAssetPolicy||{campMax:0,baggageMax:0,mutuallyExclusive:false,source:'No selected supplement asset rule'};let campMax=Number(base.campMax||0),baggageMax=Number(base.baggageMax||0),mutuallyExclusive=!!base.mutuallyExclusive,source=base.source||rs.supplement.name;for(const r of (scenario?.suggestions||[]).filter(x=>x.status==='accepted')){const text=`${r.title||''} ${r.proposal||''} ${r.engineText||''} ${r.overrides||''}`.toLowerCase();const applies=!text.includes('imperial')&&!text.includes('garrison')||text.includes(String(faction).toLowerCase());if(!applies)continue;const explicit=text.match(/(?:max(?:imum)?\s*(?:camp\s*assets?|camps?)|camp\s*(?:assets?)?\s*(?:limit|max(?:imum)?))\D{0,24}(\d+)/i);if(explicit){campMax=Math.max(campMax,Number(explicit[1]));source=r.title||'Scenario override';}const twoCampRule=/(?:\btwo\b|\b2\b)[\s\S]{0,32}\bcamps?\b/i.test(text)||/\btwo[-\s]+camp\b/i.test(text);if(twoCampRule&&String(faction).toLowerCase()==='french'){campMax=Math.max(campMax,2);source=r.title||'Scenario override';}if(text.includes('camp')&&text.includes('baggage')&&(text.includes('both')||text.includes('not mutually exclusive')))mutuallyExclusive=false;}return{campMax,baggageMax,mutuallyExclusive,source,provenance:{core:rs.core.name,supplement:rs.supplement.name,scenarioOverride:source!==base.source?source:null}};}
