import { syncBattlefieldImages } from './battlefieldState.js?v=0.6.0.1';
import { footprintPercent, applyBattlefieldAspect } from './battlefieldScale.js?v=0.6.0.1';
import { SIDE_KEYS, sideLabel, sideForFaction } from './scenarioSides.js?v=0.6.0.1';
const $=s=>document.querySelector(s);
const safe=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;

export function setupDeploymentEditor(state,persist){
  const scenario=()=>state.project.scenario;
const scaleNote=()=>{const x=scenario().tabletop||{unitBaseMm:50,commanderBaseMm:25,measurementMultiplier:2},el=document.querySelector('#deploymentScaleNote');if(el)el.textContent=`${x.unitBaseMm} mm square units · ${x.commanderBaseMm} mm round commanders · ${x.measurementMultiplier}× rules measurements`;};
const footprint=mm=>footprintPercent(mm,state.project.playSpace||{});
const syncAspect=()=>applyBattlefieldAspect(frame,state.project.playSpace||{});
const normDeg=d=>((Number(d)||0)%360+360)%360;
const playDims=()=>({width:Number(state.project.playSpace?.width||48),height:Number(state.project.playSpace?.height||48)});
const baseInches=mm=>Number(mm||50)/25.4;
function worldPlacement(kind,id,p){const d=playDims(),u=kind==='unit'?unitIndex().get(id):null,mm=kind==='unit'?Number(u?.baseMm||scenario().tabletop?.unitBaseMm||50):Number(scenario().tabletop?.commanderBaseMm||25);return{x:Number(p.x)/100*d.width,y:Number(p.y)/100*d.height,facing:normDeg(p.facing||0),size:baseInches(mm),kind};}
function squareCorners(w){const h=w.size/2,r=w.facing*Math.PI/180,c=Math.cos(r),sn=Math.sin(r),pts=[[-h,-h],[h,-h],[h,h],[-h,h]];return pts.map(([x,y])=>({x:w.x+x*c-y*sn,y:w.y+x*sn+y*c}));}
function axes(poly){return poly.map((a,i)=>{const b=poly[(i+1)%poly.length],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1;return{x:-dy/l,y:dx/l};});}
function overlapPoly(a,b,tol=1e-6){for(const ax of [...axes(a),...axes(b)]){let alo=Infinity,ahi=-Infinity,blo=Infinity,bhi=-Infinity;for(const q of a){const v=q.x*ax.x+q.y*ax.y;alo=Math.min(alo,v);ahi=Math.max(ahi,v);}for(const q of b){const v=q.x*ax.x+q.y*ax.y;blo=Math.min(blo,v);bhi=Math.max(bhi,v);}if(ahi<=blo+tol||bhi<=alo+tol)return false;}return true;}
  const tree=$('#deploymentTree'),frame=$('#deploymentMapFrame'),pieces=$('#deploymentPieces'),zonesHost=$('#deploymentZones');
  let selected=null,zoneMode=null,zoneStart=null,preview=null,polyPoints=[],dragZone=null,dragVertex=null,dragPiece=null,dragFrameRect=null,dragRaf=0,pendingDragEvent=null;

  function commands(){return Object.entries(scenario().commands||{}).flatMap(([faction,cmds])=>(cmds||[]).map((c,commandIndex)=>({faction,commandIndex,...c})));}
  function unitIndex(){const map=new Map();for(const c of commands())for(const u of c.units||[])map.set(u.id,{...u,faction:c.faction,commandId:c.id,commandIndex:c.commandIndex,commandName:c.name,commandCommander:c.commander});return map;}
  function pctFromEvent(e,rect=null){const r=rect||frame.getBoundingClientRect();return{x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))};}
  function zonePoints(z){if(Array.isArray(z.points)&&z.points.length>=3)return z.points;if(Number.isFinite(z.x))return[{x:z.x,y:z.y},{x:z.x+z.width,y:z.y},{x:z.x+z.width,y:z.y+z.height},{x:z.x,y:z.y+z.height}];return[];}
  function ensurePolygonZones(){for(const z of scenario().deployment.zones||[]){if(!z.points){z.points=zonePoints(z);delete z.x;delete z.y;delete z.width;delete z.height;}}}
  ensurePolygonZones();

  function symbolFor(profile){const x=(profile||'').toLowerCase();if(x.includes('camp'))return 'CAMP';if(x.includes('baggage'))return 'LOG';if(x.includes('cannon')||x.includes('artillery'))return '●';if(x.includes('cavalry')||x.includes('gendar')||x.includes('knight')||x.includes('ginete')||x.includes('stradiot'))return '/';return '×';}
  function renderTree(){tree.innerHTML='';let serial=0;for(const c of commands()){
    const placed=scenario().deployment.placements||{}, done=(c.units||[]).filter(u=>placed[u.id]).length;
    const section=document.createElement('details');section.className='deployment-command';section.open=true;section.innerHTML=`<summary draggable="true" data-command-drag="${c.id}" data-faction="${c.faction}"><span><strong>${safe(c.name)}</strong><small>${safe(c.commander||'No commander assigned')}</small></span><span class="deploy-count">${done}/${(c.units||[]).length} deployed</span><span class="count-pill">${(c.units||[]).length}</span></summary><div class="deployment-command-body"></div>`;
    const body=section.querySelector('.deployment-command-body');if(c.commander){const yes=!!scenario().deployment.commanderPlacements?.[c.id],leader=document.createElement('div');leader.className=`deployment-tree-item commander-tree ${yes?'deployed':''}`;leader.draggable=true;leader.dataset.dragType='commander';leader.dataset.commandId=c.id;leader.dataset.faction=c.faction;leader.innerHTML=`<span class="commander-symbol">★</span><span><strong>${safe(c.commander)}</strong><small>Commander · ${scenario().tabletop?.commanderBaseMm||25} mm circle · <b class="deploy-state ${yes?'yes':'no'}">${yes?'✓ Deployed':'○ Undeployed'}</b></small></span>`;leader.addEventListener('dragstart',dragTree);body.appendChild(leader);}
    for(const u of c.units||[]){serial++;const yes=!!placed[u.id],row=document.createElement('div');row.className=`deployment-tree-item ${yes?'deployed':''}`;row.draggable=true;row.dataset.dragType='unit';row.dataset.unitId=u.id;row.dataset.commandId=c.id;row.dataset.faction=c.faction;row.innerHTML=`<span class="unit-mini ${c.faction.toLowerCase()}">${symbolFor(u.profile)}</span><span><strong>${safe(u.name)}</strong><small>${safe(u.profile)} · ${u.profile==='Camp'||u.profile==='Baggage Train'?'40':'50'} mm · <b class="deploy-state ${yes?'yes':'no'}">${yes?'✓ Deployed':'○ Undeployed'}</b></small></span>`;row.dataset.unitCode=`${c.faction[0]}${serial}`;row.addEventListener('dragstart',dragTree);body.appendChild(row);}
    section.querySelector('summary').addEventListener('dragstart',e=>e.dataTransfer.setData('application/x-bax-deployment',JSON.stringify({type:'command',commandId:c.id,faction:c.faction})));tree.appendChild(section);
  }}
  function dragTree(e){e.dataTransfer.setData('application/x-bax-deployment',JSON.stringify({type:e.currentTarget.dataset.dragType,unitId:e.currentTarget.dataset.unitId||null,commandId:e.currentTarget.dataset.commandId,faction:e.currentTarget.dataset.faction}));}
  function placeData(data,p){const dep=scenario().deployment;if(data.type==='unit'){const q=nearestLegalPlacement('unit',data.unitId,p);if(q)dep.placements[data.unitId]={x:q.x,y:q.y,facing:0,faction:data.faction,commandId:data.commandId};}if(data.type==='commander'){const q=nearestLegalPlacement('commander',data.commandId,p);if(q)dep.commanderPlacements[data.commandId]={x:q.x,y:q.y,faction:data.faction};}if(data.type==='command'){const c=(scenario().commands[data.faction]||[]).find(x=>x.id===data.commandId);if(!c)return;let i=0;for(const u of c.units||[]){const col=i%3,row=Math.floor(i/3),q=nearestLegalPlacement('unit',u.id,{x:p.x+(col-1)*5,y:p.y+row*5});if(q)dep.placements[u.id]={x:q.x,y:q.y,facing:0,faction:data.faction,commandId:c.id};i++;}if(c.commander){const q=nearestLegalPlacement('commander',c.id,{x:p.x,y:p.y-4});if(q)dep.commanderPlacements[c.id]={x:q.x,y:q.y,faction:data.faction};}}persist();render();}
  function commandColor(faction,index=0){const palettes={French:['#164A7A','#2376BD','#49A0D8','#285A8F','#196F82','#5A57B5','#2E87A7'],Imperial:['#7E2727','#A93A32','#D45A4D','#8B405D','#B96A32','#C64468','#6D3947'],Garrison:['#6F5423','#9B782D','#C19A45','#80683D']};const a=palettes[faction]||['#4d6380','#66809f','#384e68'];return a[index%a.length];}
  function pieceEl(kind,id,p,meta){const el=document.createElement('button');el.className=`deployment-piece ${kind} ${meta.faction.toLowerCase()} ${meta.asset?'asset':''}`;el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.style.transform=`translate(-50%,-50%) rotate(${normDeg(p.facing||0)}deg)`;el.style.setProperty('--label-counter-rotation',`${-normDeg(p.facing||0)}deg`);el.dataset.kind=kind;el.dataset.id=id;el.draggable=false;if(kind==='unit'){const configured=Number(scenario().tabletop?.unitBaseMm||50),mm=Number(meta.baseMm||configured),fp=footprint(mm);el.style.width=`${fp.width}%`;el.style.height=`${fp.height}%`;el.style.background=commandColor(meta.faction,meta.commandIndex);el.innerHTML=`<span class="piece-label">${safe(meta.name)}</span>`;el.title=`${meta.name} (${meta.profile}) · ${mm} mm square footprint · drag to reposition`;}else{const mm=Number(scenario().tabletop?.commanderBaseMm||25),fp=footprint(mm);el.style.width=`${fp.width}%`;el.style.height=`${fp.height}%`;el.style.background=commandColor(meta.faction,meta.commandIndex);el.innerHTML='★';el.title=`${meta.name} · ${mm} mm round footprint · drag to reposition`;}el.addEventListener('pointerdown',e=>{if(zoneMode)return;e.preventDefault();e.stopPropagation();selected={kind,id};dragFrameRect=frame.getBoundingClientRect();const pointerStart=pctFromEvent(e,dragFrameRect);dragPiece={kind,id,pointerId:e.pointerId,moved:false,pointerStart,origin:{x:Number(p.x),y:Number(p.y),facing:normDeg(p.facing||0)},last:{x:Number(p.x),y:Number(p.y),facing:normDeg(p.facing||0)},el};el.setPointerCapture?.(e.pointerId);el.classList.add('dragging');renderSelection();});el.addEventListener('click',e=>e.stopPropagation());return el;}
  function clampPiecePoint(kind,id,p){let mm;if(kind==='unit'){const u=unitIndex().get(id);mm=Number(u?.baseMm||scenario().tabletop?.unitBaseMm||50);}else mm=Number(scenario().tabletop?.commanderBaseMm||25);const fp=footprint(mm),hx=fp.width/2,hy=fp.height/2;return{x:Math.max(hx,Math.min(100-hx,p.x)),y:Math.max(hy,Math.min(100-hy,p.y))};}
  function placementFootprint(kind,id){let mm;if(kind==='unit'){const u=unitIndex().get(id);mm=Number(u?.baseMm||scenario().tabletop?.unitBaseMm||50);}else mm=Number(scenario().tabletop?.commanderBaseMm||25);return footprint(mm);}
  function placementClear(kind,id,p){const d=playDims(),w=worldPlacement(kind,id,p);if(kind==='commander'){const h=w.size/2;if(w.x-h<0||w.x+h>d.width||w.y-h<0||w.y+h>d.height)return false;}else if(squareCorners(w).some(q=>q.x<0||q.x>d.width||q.y<0||q.y>d.height))return false;const idx=unitIndex();for(const [oid,op] of Object.entries(scenario().deployment.placements||{})){if(kind==='unit'&&oid===id)continue;const ow=worldPlacement('unit',oid,op);if(kind==='commander'){const dx=Math.max(Math.abs(w.x-ow.x)-ow.size/2,0),dy=Math.max(Math.abs(w.y-ow.y)-ow.size/2,0);if(Math.hypot(dx,dy)<w.size/2-1e-6)return false;}else if(overlapPoly(squareCorners(w),squareCorners(ow)))return false;}for(const [oid,op] of Object.entries(scenario().deployment.commanderPlacements||{})){if(kind==='commander'&&oid===id)continue;const ow=worldPlacement('commander',oid,op),r=(w.size+ow.size)/2;if(kind==='commander'){if(Math.hypot(w.x-ow.x,w.y-ow.y)<r-1e-6)return false;}else{const poly=squareCorners(w),dx=Math.max(...poly.map(q=>Math.abs(q.x-ow.x))),dy=Math.max(...poly.map(q=>Math.abs(q.y-ow.y)));if(Math.hypot(Math.max(dx-w.size/2,0),Math.max(dy-w.size/2,0))<ow.size/2-1e-6){const min=Math.min(...poly.map(q=>Math.hypot(q.x-ow.x,q.y-ow.y)));if(min<ow.size/2-1e-6)return false;}}}return true;}
  function nearestLegalPlacement(kind,id,p){const base=clampPiecePoint(kind,id,p);if(placementClear(kind,id,base))return base;for(let radius=.75;radius<=20;radius+=.75)for(let deg=0;deg<360;deg+=30){const r=deg*Math.PI/180,q=clampPiecePoint(kind,id,{x:base.x+Math.cos(r)*radius,y:base.y+Math.sin(r)*radius});if(placementClear(kind,id,q))return q;}return null;}
  function renderPieces(){syncAspect();pieces.innerHTML='';const idx=unitIndex();let n=0;for(const [id,p] of Object.entries(scenario().deployment.placements||{})){const u=idx.get(id);if(u){n++;pieces.appendChild(pieceEl('unit',id,p,{name:u.name,profile:u.profile,faction:u.faction,code:`${u.faction[0]}${n}`,asset:['Camp','Baggage Train'].includes(u.profile),baseMm:Number(u.baseMm||scenario().tabletop?.unitBaseMm||50),commandId:u.commandId,commandIndex:u.commandIndex}));}}for(const [id,p] of Object.entries(scenario().deployment.commanderPlacements||{})){const c=commands().find(x=>x.id===id);if(c)pieces.appendChild(pieceEl('commander',id,p,{name:c.commander,faction:c.faction,commandIndex:c.commandIndex}));}if(selected?.kind!=='zone')document.querySelectorAll('.deployment-piece').forEach(el=>el.classList.toggle('selected',el.dataset.kind===selected?.kind&&el.dataset.id===selected?.id));}
  function svgEl(name,attrs={}){const e=document.createElementNS('http://www.w3.org/2000/svg',name);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
  function centroid(points){return{x:points.reduce((a,p)=>a+p.x,0)/points.length,y:points.reduce((a,p)=>a+p.y,0)/points.length};}
  function renderZones(){zonesHost.innerHTML='';for(const z of scenario().deployment.zones||[]){const pts=zonePoints(z);if(pts.length<3)continue;const g=svgEl('g',{'data-zone':z.id,class:`zone-group ${String(z.faction||'neutral').toLowerCase()}${selected?.kind==='zone'&&selected.id===z.id?' selected':''}`});const poly=svgEl('polygon',{points:pts.map(p=>`${p.x},${p.y}`).join(' '),class:'deployment-zone-poly'});poly.addEventListener('pointerdown',e=>{e.stopPropagation();selected={kind:'zone',id:z.id};dragZone={id:z.id,start:pctFromEvent(e),original:pts.map(p=>({...p}))};poly.setPointerCapture?.(e.pointerId);renderSelection();});g.appendChild(poly);const c=centroid(pts),text=svgEl('text',{x:c.x,y:c.y,class:'deployment-zone-label'});text.textContent=z.name;g.appendChild(text);if(selected?.kind==='zone'&&selected.id===z.id){pts.forEach((p,i)=>{const h=svgEl('circle',{cx:p.x,cy:p.y,r:'1.25',class:'zone-vertex','data-vertex':i});h.addEventListener('pointerdown',e=>{e.stopPropagation();dragVertex={id:z.id,index:i};h.setPointerCapture?.(e.pointerId);});g.appendChild(h);});}zonesHost.appendChild(g);}if(zoneMode==='polygon'&&polyPoints.length){const pl=svgEl('polyline',{points:polyPoints.map(p=>`${p.x},${p.y}`).join(' '),class:'zone-preview-line'});zonesHost.appendChild(pl);for(const p of polyPoints)zonesHost.appendChild(svgEl('circle',{cx:p.x,cy:p.y,r:'1',class:'zone-preview-point'}));}}
  function renderWarnings(){syncBattlefieldImages(state);const idx=unitIndex(),placed=scenario().deployment.placements||{},cp=scenario().deployment.commanderPlacements||{};const missingUnits=[...idx.values()].filter(u=>!placed[u.id]),missingCmd=commands().filter(c=>c.commander&&!cp[c.id]);const warnings=[];if(!idx.size)warnings.push('No Battle Axe units are currently available for deployment.');else{if(missingUnits.length)warnings.push(`${missingUnits.length} unit${missingUnits.length===1?' is':'s are'} not deployed`);if(missingCmd.length)warnings.push(`${missingCmd.length} commander${missingCmd.length===1?' is':'s are'} not placed`);}if(!state.project.mapSource)warnings.push('No battlefield map is generated for the current scenario.');if(scenario().deployment?.battlefieldRevision&&state.project.battlefieldRevision&&scenario().deployment.battlefieldRevision!==state.project.battlefieldRevision)warnings.push('Deployment belongs to an earlier battlefield revision and must be reviewed.');$('#deploymentWarningCount').textContent=warnings.length;$('#deploymentWarnings').innerHTML=warnings.length?`<ul>${warnings.map(x=>`<li>${safe(x)}</li>`).join('')}</ul>`:'<p class="success">All current force-list objects are placed.</p>';$('#deploymentStatus').textContent=`${Object.keys(placed).length}/${idx.size} units placed`;
  }
  function renderSelection(){const host=$('#deploymentSelection'),remove=$('#removeDeploymentObject'),addV=$('#addZoneVertex'),delV=$('#deleteZoneVertex'),rotL=$('#rotateDeploymentLeft'),rotR=$('#rotateDeploymentRight');if(!selected){host.innerHTML='<p class="muted">Select a deployed unit, commander, or zone.</p>';remove.disabled=true;if(addV)addV.disabled=true;if(delV)delV.disabled=true;if(rotL)rotL.disabled=true;if(rotR)rotR.disabled=true;return;}remove.disabled=false;if(rotL)rotL.disabled=selected.kind!=='unit';if(rotR)rotR.disabled=selected.kind!=='unit';if(selected.kind==='unit'){const u=unitIndex().get(selected.id),p=scenario().deployment.placements[selected.id];host.innerHTML=u?`<strong>${safe(u.name)}</strong><p>${safe(u.commandName)} · ${safe(u.profile)}</p><small>${p.x.toFixed(1)}%, ${p.y.toFixed(1)}% · facing ${normDeg(p.facing||0).toFixed(0)}°</small>`:'<p>Unit placement</p>';}else if(selected.kind==='commander'){const c=commands().find(x=>x.id===selected.id);host.innerHTML=c?`<strong>${safe(c.commander)}</strong><p>Commander · ${safe(c.name)}</p>`:'<p>Commander placement</p>';}else{const z=(scenario().deployment.zones||[]).find(x=>x.id===selected.id),pts=z?zonePoints(z):[];host.innerHTML=z?`<strong>${safe(z.name)}</strong><p>${safe(z.faction||'Unassigned')} deployment zone · ${pts.length} vertices</p><small>Drag the polygon to move it. Drag yellow vertex handles to reshape it.</small>`:'<p>Deployment zone</p>';if(addV)addV.disabled=!z;if(delV)delV.disabled=!z||pts.length<=3;}}
  function removeSelected(){if(!selected)return;if(selected.kind==='unit')delete scenario().deployment.placements[selected.id];else if(selected.kind==='commander')delete scenario().deployment.commanderPlacements[selected.id];else scenario().deployment.zones=scenario().deployment.zones.filter(z=>z.id!==selected.id);selected=null;persist();render();}
  function render(){scaleNote();renderTree();renderPieces();renderZones();renderWarnings();renderSelection();}
  function newZone(points){if(points.length<3)return;const name=prompt('Deployment zone name:','New deployment zone')||'Deployment zone',a=sideLabel(scenario(),SIDE_KEYS[0]),b=sideLabel(scenario(),SIDE_KEYS[1]),raw=prompt(`Assign to side (${a}, ${b}, or leave blank):`,'')||'',faction=raw?(sideForFaction(scenario(),raw,{assign:false})||raw):'';scenario().deployment.zones.push({id:uid('zone'),name,faction,points:points.map(p=>({x:p.x,y:p.y}))});persist();selected={kind:'zone',id:scenario().deployment.zones.at(-1).id};}
  function stopZoneMode(){zoneMode=null;zoneStart=null;preview?.remove?.();preview=null;polyPoints=[];$('#addDeploymentZone').textContent='Rectangle zone';$('#addPolygonZone').textContent='Polygon zone';$('#finishPolygonZone').hidden=true;frame.classList.remove('zone-mode');const c=$('#cancelDeploymentTool');if(c)c.hidden=true;renderZones();}

  function updatePieceDrag(e){if(!dragPiece)return;const pointer=pctFromEvent(e,dragFrameRect),dx=pointer.x-dragPiece.pointerStart.x,dy=pointer.y-dragPiece.pointerStart.y,p={x:dragPiece.origin.x+dx,y:dragPiece.origin.y+dy,facing:dragPiece.origin.facing||0},el=dragPiece.el||pieces.querySelector(`[data-kind="${dragPiece.kind}"][data-id="${dragPiece.id}"]`);dragPiece.last=p;dragPiece.moved=dragPiece.moved||Math.abs(dx)>.02||Math.abs(dy)>.02;if(el){el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.style.transform=`translate(-50%,-50%) rotate(${normDeg(p.facing||0)}deg)`;el.style.setProperty('--label-counter-rotation',`${-normDeg(p.facing||0)}deg`);const legal=placementClear(dragPiece.kind,dragPiece.id,p);el.classList.toggle('drag-valid',legal);el.classList.toggle('drag-invalid',!legal);}}
  function schedulePieceDrag(e){pendingDragEvent={clientX:e.clientX,clientY:e.clientY};if(dragRaf)return;dragRaf=requestAnimationFrame(()=>{dragRaf=0;if(pendingDragEvent){updatePieceDrag(pendingDragEvent);pendingDragEvent=null;}});}
  frame.addEventListener('dragover',e=>e.preventDefault());frame.addEventListener('drop',e=>{e.preventDefault();const p=pctFromEvent(e),treeRaw=e.dataTransfer.getData('application/x-bax-deployment'),depRaw=e.dataTransfer.getData('application/x-bax-deployed');if(treeRaw){placeData(JSON.parse(treeRaw),p);return;}if(depRaw){const d=JSON.parse(depRaw),q=nearestLegalPlacement(d.kind,d.id,p);if(q){if(d.kind==='unit')scenario().deployment.placements[d.id]={...scenario().deployment.placements[d.id],...q};else scenario().deployment.commanderPlacements[d.id]={...scenario().deployment.commanderPlacements[d.id],...q};persist();render();}}});
  frame.addEventListener('click',e=>{if(zoneMode==='polygon'){if(e.target.closest('#deploymentZones')?.querySelector?.('.zone-vertex'))return;polyPoints.push(pctFromEvent(e));renderZones();return;}if(zoneMode)return;selected=null;render();});
  $('#removeDeploymentObject').addEventListener('click',removeSelected);$('#clearDeploymentSelection').addEventListener('click',()=>{selected=null;render();});
  $('#addDeploymentZone').addEventListener('click',()=>{stopZoneMode();zoneMode='rect';$('#addDeploymentZone').textContent='Drag rectangle…';frame.classList.add('zone-mode');const c=$('#cancelDeploymentTool');if(c)c.hidden=false;});
  $('#addPolygonZone').addEventListener('click',()=>{stopZoneMode();zoneMode='polygon';$('#addPolygonZone').textContent='Click map vertices…';$('#finishPolygonZone').hidden=false;frame.classList.add('zone-mode');const c=$('#cancelDeploymentTool');if(c)c.hidden=false;});
  $('#finishPolygonZone').addEventListener('click',()=>{if(polyPoints.length>=3)newZone(polyPoints);stopZoneMode();render();});
  $('#addZoneVertex').addEventListener('click',()=>{if(selected?.kind!=='zone')return;const z=scenario().deployment.zones.find(x=>x.id===selected.id),pts=zonePoints(z);let best=0,bestD=-1;for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length],d=Math.hypot(a.x-b.x,a.y-b.y);if(d>bestD){bestD=d;best=i;}}const a=pts[best],b=pts[(best+1)%pts.length];pts.splice(best+1,0,{x:(a.x+b.x)/2,y:(a.y+b.y)/2});z.points=pts;persist();render();});
  $('#deleteZoneVertex').addEventListener('click',()=>{if(selected?.kind!=='zone')return;const z=scenario().deployment.zones.find(x=>x.id===selected.id),pts=zonePoints(z);if(pts.length<=3)return;pts.pop();z.points=pts;persist();render();});
  frame.addEventListener('pointerdown',e=>{if(zoneMode!=='rect')return;e.preventDefault();zoneStart=pctFromEvent(e);preview=document.createElement('div');preview.className='deployment-zone preview';$('#deploymentZonePreviewHost').appendChild(preview);});
  frame.addEventListener('pointermove',e=>{if(dragPiece){schedulePieceDrag(e);return;}if(zoneMode==='rect'&&zoneStart&&preview){const p=pctFromEvent(e),x=Math.min(zoneStart.x,p.x),y=Math.min(zoneStart.y,p.y),w=Math.abs(p.x-zoneStart.x),h=Math.abs(p.y-zoneStart.y);Object.assign(preview.style,{left:`${x}%`,top:`${y}%`,width:`${w}%`,height:`${h}%`});return;}if(dragVertex){const z=scenario().deployment.zones.find(x=>x.id===dragVertex.id),p=pctFromEvent(e);if(z){z.points[dragVertex.index]=p;renderZones();}return;}if(dragZone){const z=scenario().deployment.zones.find(x=>x.id===dragZone.id),p=pctFromEvent(e),dx=p.x-dragZone.start.x,dy=p.y-dragZone.start.y;if(z){z.points=dragZone.original.map(q=>({x:Math.max(0,Math.min(100,q.x+dx)),y:Math.max(0,Math.min(100,q.y+dy))}));renderZones();}}});
  frame.addEventListener('pointerup',e=>{if(dragPiece){if(dragRaf){cancelAnimationFrame(dragRaf);dragRaf=0;}pendingDragEvent=null;const p=dragPiece.last||dragPiece.origin,q=placementClear(dragPiece.kind,dragPiece.id,p)?p:dragPiece.origin;dragPiece.el?.classList.remove('dragging','drag-valid','drag-invalid');if(dragPiece.kind==='unit')scenario().deployment.placements[dragPiece.id]={...scenario().deployment.placements[dragPiece.id],...q};else scenario().deployment.commanderPlacements[dragPiece.id]={...scenario().deployment.commanderPlacements[dragPiece.id],...q};dragPiece=null;dragFrameRect=null;persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));render();return;}if(zoneMode==='rect'&&zoneStart){const p=pctFromEvent(e),x=Math.min(zoneStart.x,p.x),y=Math.min(zoneStart.y,p.y),w=Math.abs(p.x-zoneStart.x),h=Math.abs(p.y-zoneStart.y);preview?.remove();preview=null;zoneStart=null;if(w>=2&&h>=2)newZone([{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}]);stopZoneMode();persist();render();}if(dragVertex||dragZone){dragVertex=null;dragZone=null;persist();render();}});

  frame.addEventListener('pointercancel',()=>{if(dragPiece){if(dragRaf)cancelAnimationFrame(dragRaf);dragRaf=0;pendingDragEvent=null;dragPiece.el?.classList.remove('dragging','drag-valid','drag-invalid');dragPiece=null;dragFrameRect=null;renderPieces();}if(dragVertex||dragZone){dragVertex=null;dragZone=null;renderZones();}});

  document.querySelector('[data-view="deployment"]')?.addEventListener('click',()=>setTimeout(()=>{syncAspect();render();},0));window.addEventListener('bax:battlefield-changed',()=>{selected=null;syncAspect();render();});window.addEventListener('bax:scenario-changed',()=>{syncAspect();render();});syncBattlefieldImages(state);syncAspect();render();return{render};
}
