const $=s=>document.querySelector(s);
const safe=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;

export function setupDeploymentEditor(state,persist){
  const scenario=()=>state.project.scenario;
  const tree=$('#deploymentTree'),frame=$('#deploymentMapFrame'),pieces=$('#deploymentPieces'),zonesHost=$('#deploymentZones');
  let selected=null,zoneMode=false,zoneStart=null,previewZone=null;

  function commands(){return Object.entries(scenario().commands||{}).flatMap(([faction,cmds])=>(cmds||[]).map(c=>({faction,...c})));}
  function unitIndex(){const map=new Map();for(const c of commands())for(const u of c.units||[])map.set(u.id,{...u,faction:c.faction,commandId:c.id,commandName:c.name,commandCommander:c.commander});return map;}
  function pctFromEvent(e){const r=frame.getBoundingClientRect();return{x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))};}
  function basePct(mm,axis='width'){const inches=mm/25.4,space=Number(state.project.playSpace?.[axis]||48);return inches/space*100;}

  function renderTree(){tree.innerHTML='';for(const c of commands()){
    const section=document.createElement('details');section.className='deployment-command';section.open=true;section.innerHTML=`<summary draggable="true" data-command-drag="${c.id}" data-faction="${c.faction}"><span><strong>${safe(c.name)}</strong><small>${safe(c.commander||'No commander assigned')}</small></span><span class="count-pill">${(c.units||[]).length}</span></summary><div class="deployment-command-body"></div>`;
    const body=section.querySelector('.deployment-command-body');if(c.commander){const leader=document.createElement('div');leader.className='deployment-tree-item commander-tree';leader.draggable=true;leader.dataset.dragType='commander';leader.dataset.commandId=c.id;leader.dataset.faction=c.faction;leader.innerHTML=`<span class="commander-symbol">★</span><span><strong>${safe(c.commander)}</strong><small>Commander · 25 mm circle</small></span>`;leader.addEventListener('dragstart',dragTree);body.appendChild(leader);}
    for(const u of c.units||[]){const row=document.createElement('div');row.className='deployment-tree-item';row.draggable=true;row.dataset.dragType='unit';row.dataset.unitId=u.id;row.dataset.commandId=c.id;row.dataset.faction=c.faction;row.innerHTML=`<span class="unit-mini ${c.faction.toLowerCase()}"></span><span><strong>${safe(u.name)}</strong><small>${safe(u.profile)} · 50 mm square</small></span>`;row.addEventListener('dragstart',dragTree);body.appendChild(row);}
    section.querySelector('summary').addEventListener('dragstart',e=>e.dataTransfer.setData('application/x-bax-deployment',JSON.stringify({type:'command',commandId:c.id,faction:c.faction})));tree.appendChild(section);
  }}
  function dragTree(e){e.dataTransfer.setData('application/x-bax-deployment',JSON.stringify({type:e.currentTarget.dataset.dragType,unitId:e.currentTarget.dataset.unitId||null,commandId:e.currentTarget.dataset.commandId,faction:e.currentTarget.dataset.faction}));}

  function placeData(data,p){const dep=scenario().deployment;if(data.type==='unit'){dep.placements[data.unitId]={x:p.x,y:p.y,faction:data.faction,commandId:data.commandId};}
    if(data.type==='commander'){dep.commanderPlacements[data.commandId]={x:p.x,y:p.y,faction:data.faction};}
    if(data.type==='command'){const c=(scenario().commands[data.faction]||[]).find(x=>x.id===data.commandId);if(!c)return;let i=0;for(const u of c.units||[]){const col=i%3,row=Math.floor(i/3);dep.placements[u.id]={x:Math.min(96,p.x+(col-1)*5),y:Math.min(96,p.y+row*5),faction:data.faction,commandId:c.id};i++;}if(c.commander)dep.commanderPlacements[c.id]={x:p.x,y:Math.max(2,p.y-4),faction:data.faction};}
    persist();render();}

  function pieceEl(kind,id,p,meta){const el=document.createElement('button');el.className=`deployment-piece ${kind} ${meta.faction.toLowerCase()}`;el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.dataset.kind=kind;el.dataset.id=id;el.draggable=true;if(kind==='unit'){const w=basePct(50,'width'),h=basePct(50,'height');el.style.width=`${w}%`;el.style.height=`${h}%`;el.innerHTML=`<span>${safe(meta.name)}</span>`;}else{const w=basePct(25,'width'),h=basePct(25,'height');el.style.width=`${w}%`;el.style.height=`${h}%`;el.innerHTML='★';el.title=meta.name;}
    el.addEventListener('click',e=>{e.stopPropagation();selected={kind,id};renderSelection();document.querySelectorAll('.deployment-piece').forEach(x=>x.classList.toggle('selected',x===el));});el.addEventListener('dragstart',e=>{e.dataTransfer.setData('application/x-bax-deployed',JSON.stringify({kind,id}));});return el;}
  function renderPieces(){pieces.innerHTML='';const idx=unitIndex();for(const [id,p] of Object.entries(scenario().deployment.placements||{})){const u=idx.get(id);if(u)pieces.appendChild(pieceEl('unit',id,p,{name:u.name,faction:u.faction}));}for(const [id,p] of Object.entries(scenario().deployment.commanderPlacements||{})){const c=commands().find(x=>x.id===id);if(c)pieces.appendChild(pieceEl('commander',id,p,{name:c.commander,faction:c.faction}));}}
  function renderZones(){zonesHost.innerHTML='';for(const z of scenario().deployment.zones||[]){const el=document.createElement('button');el.className=`deployment-zone ${String(z.faction||'neutral').toLowerCase()}`;el.style.left=`${z.x}%`;el.style.top=`${z.y}%`;el.style.width=`${z.width}%`;el.style.height=`${z.height}%`;el.innerHTML=`<span>${safe(z.name)}</span>`;el.addEventListener('click',e=>{e.stopPropagation();selected={kind:'zone',id:z.id};renderSelection();});zonesHost.appendChild(el);}}
  function renderWarnings(){const idx=unitIndex(),placed=scenario().deployment.placements||{},cp=scenario().deployment.commanderPlacements||{};const missingUnits=[...idx.values()].filter(u=>!placed[u.id]),missingCmd=commands().filter(c=>c.commander&&!cp[c.id]);const warnings=[];if(missingUnits.length)warnings.push(`${missingUnits.length} unit${missingUnits.length===1?' is':'s are'} not deployed`);if(missingCmd.length)warnings.push(`${missingCmd.length} commander${missingCmd.length===1?' is':'s are'} not placed`);$('#deploymentWarningCount').textContent=warnings.length;$('#deploymentWarnings').innerHTML=warnings.length?`<ul>${warnings.map(x=>`<li>${safe(x)}</li>`).join('')}</ul>`:'<p class="success">All current force-list objects are placed.</p>';$('#deploymentStatus').textContent=`${Object.keys(placed).length}/${idx.size} units placed`;}
  function renderSelection(){const host=$('#deploymentSelection'),remove=$('#removeDeploymentObject');if(!selected){host.innerHTML='<p class="muted">Select a deployed unit, commander, or zone.</p>';remove.disabled=true;return;}remove.disabled=false;if(selected.kind==='unit'){const u=unitIndex().get(selected.id),p=scenario().deployment.placements[selected.id];host.innerHTML=u?`<strong>${safe(u.name)}</strong><p>${safe(u.commandName)} · ${safe(u.profile)}</p><small>${p.x.toFixed(1)}%, ${p.y.toFixed(1)}%</small>`:'<p>Unit placement</p>';}else if(selected.kind==='commander'){const c=commands().find(x=>x.id===selected.id);host.innerHTML=c?`<strong>${safe(c.commander)}</strong><p>Commander · ${safe(c.name)}</p>`:'<p>Commander placement</p>';}else{const z=(scenario().deployment.zones||[]).find(x=>x.id===selected.id);host.innerHTML=z?`<strong>${safe(z.name)}</strong><p>${safe(z.faction||'Unassigned')} deployment zone</p>`:'<p>Deployment zone</p>';}}
  function removeSelected(){if(!selected)return;if(selected.kind==='unit')delete scenario().deployment.placements[selected.id];else if(selected.kind==='commander')delete scenario().deployment.commanderPlacements[selected.id];else scenario().deployment.zones=scenario().deployment.zones.filter(z=>z.id!==selected.id);selected=null;persist();render();}
  function render(){renderTree();renderPieces();renderZones();renderWarnings();renderSelection();}

  frame.addEventListener('dragover',e=>e.preventDefault());frame.addEventListener('drop',e=>{e.preventDefault();const p=pctFromEvent(e),treeRaw=e.dataTransfer.getData('application/x-bax-deployment'),depRaw=e.dataTransfer.getData('application/x-bax-deployed');if(treeRaw){placeData(JSON.parse(treeRaw),p);return;}if(depRaw){const d=JSON.parse(depRaw);if(d.kind==='unit')scenario().deployment.placements[d.id]={...scenario().deployment.placements[d.id],...p};else scenario().deployment.commanderPlacements[d.id]={...scenario().deployment.commanderPlacements[d.id],...p};persist();render();}});
  frame.addEventListener('click',()=>{selected=null;renderSelection();document.querySelectorAll('.deployment-piece').forEach(x=>x.classList.remove('selected'));});
  $('#removeDeploymentObject').addEventListener('click',removeSelected);$('#clearDeploymentSelection').addEventListener('click',()=>{selected=null;renderSelection();});
  $('#addDeploymentZone').addEventListener('click',()=>{zoneMode=!zoneMode;$('#addDeploymentZone').textContent=zoneMode?'Drag on map to draw zone…':'Draw rectangular deployment zone';frame.classList.toggle('zone-mode',zoneMode);});
  frame.addEventListener('pointerdown',e=>{if(!zoneMode)return;e.preventDefault();zoneStart=pctFromEvent(e);previewZone=document.createElement('div');previewZone.className='deployment-zone preview';zonesHost.appendChild(previewZone);});
  frame.addEventListener('pointermove',e=>{if(!zoneMode||!zoneStart||!previewZone)return;const p=pctFromEvent(e),x=Math.min(zoneStart.x,p.x),y=Math.min(zoneStart.y,p.y),w=Math.abs(p.x-zoneStart.x),h=Math.abs(p.y-zoneStart.y);Object.assign(previewZone.style,{left:`${x}%`,top:`${y}%`,width:`${w}%`,height:`${h}%`});});
  frame.addEventListener('pointerup',e=>{if(!zoneMode||!zoneStart)return;const p=pctFromEvent(e),x=Math.min(zoneStart.x,p.x),y=Math.min(zoneStart.y,p.y),width=Math.abs(p.x-zoneStart.x),height=Math.abs(p.y-zoneStart.y);previewZone?.remove();previewZone=null;zoneStart=null;zoneMode=false;$('#addDeploymentZone').textContent='Draw rectangular deployment zone';frame.classList.remove('zone-mode');if(width<2||height<2)return;const name=prompt('Deployment zone name:','New deployment zone')||'Deployment zone',faction=prompt('Assign to side (French, Imperial, Garrison, or leave blank):','')||'';scenario().deployment.zones.push({id:uid('zone'),name,faction,x,y,width,height});persist();render();});

  document.querySelector('[data-view="deployment"]')?.addEventListener('click',()=>setTimeout(render,0));
  render();return{render};
}
