import { syncBattlefieldImages } from './battlefieldState.js?v=0.6.8.0';
import { applyBattlefieldAspect } from './battlefieldScale.js?v=0.6.8.0';
import { SIDE_KEYS, sideLabel, sideForFaction } from './scenarioSides.js?v=0.6.8.0';
import { getEffectiveRuleset } from '../rules/ruleset.js?v=0.6.8.0';
import { footprintsPenetrate, footprintInsideBattlefield, footprintPercentFromSpec } from './footprintGeometry.js?v=0.6.8.0';
const $=s=>document.querySelector(s);
const safe=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;

export function dragCenterFromGrab(origin,pointerStart,pointerNow){return{x:Number(origin.x)+(Number(pointerNow.x)-Number(pointerStart.x)),y:Number(origin.y)+(Number(pointerNow.y)-Number(pointerStart.y)),facing:Number(origin.facing||0)};}
export function nearestBattlefieldEdge(p){const d={north:Number(p.y),south:100-Number(p.y),west:Number(p.x),east:100-Number(p.x)};return Object.entries(d).sort((a,b)=>a[1]-b[1])[0][0];}
export function edgePercent(edge,p){return['north','south'].includes(edge)?Math.max(0,Math.min(100,Number(p.x))):Math.max(0,Math.min(100,Number(p.y)));}
export function edgeEntryLine(edge,startPct=0,endPct=100){const a=Math.max(0,Math.min(100,Number(startPct))),b=Math.max(0,Math.min(100,Number(endPct))),start=Math.min(a,b),end=Math.max(a,b);if(edge==='north')return{x1:start,y1:0,x2:end,y2:0};if(edge==='south')return{x1:start,y1:100,x2:end,y2:100};if(edge==='west')return{x1:0,y1:start,x2:0,y2:end};return{x1:100,y1:start,x2:100,y2:end};}

export function setupDeploymentEditor(state,persist){
  const scenario=()=>state.project.scenario;
  const scaleNote=()=>{const x=scenario().tabletop||{unitBaseMm:50,unitBaseWidthMm:50,unitBaseDepthMm:50,commanderBaseMm:25,measurementMultiplier:2},w=Number(x.unitBaseWidthMm||x.unitBaseMm||50),d=Number(x.unitBaseDepthMm||x.unitBaseMm||w),el=$('#deploymentScaleNote');if(el)el.textContent=`${w}×${d} mm unit default · ${x.commanderBaseMm||25} mm round commanders · ${x.measurementMultiplier||1}× rules measurements`;};
  const tree=$('#deploymentTree'),frame=$('#deploymentMapFrame'),pieces=$('#deploymentPieces'),zonesHost=$('#deploymentZones');
  const syncAspect=()=>applyBattlefieldAspect(frame,state.project.playSpace||{});
  const normDeg=d=>((Number(d)||0)%360+360)%360;
  const playDims=()=>({width:Number(state.project.playSpace?.width||48),height:Number(state.project.playSpace?.height||48)});
  let selected=null,zoneMode=null,zoneStart=null,preview=null,polyPoints=[],dragZone=null,dragVertex=null,dragPiece=null,dragFrameRect=null,dragRaf=0,pendingDragEvent=null,reserveTool=null;
  const undoStack=[],redoStack=[];

  function commandRecords(){return Object.entries(scenario().commands||{}).flatMap(([faction,cmds])=>(cmds||[]).map((command,commandIndex)=>({faction,commandIndex,command})));}
  function commands(){return commandRecords().map(r=>({faction:r.faction,commandIndex:r.commandIndex,...r.command}));}
  function actualCommand(faction,id){return (scenario().commands?.[faction]||[]).find(c=>c.id===id)||commandRecords().find(r=>r.command.id===id)?.command||null;}
  function authoringSnapshot(){const reserves={};for(const r of commandRecords())if(r.command.reserve!==undefined)reserves[r.command.id]=structuredClone(r.command.reserve);return{deployment:structuredClone(scenario().deployment||{}),reserves};}
  function updateHistoryButtons(){const u=$('#deploymentUndo'),r=$('#deploymentRedo');if(u)u.disabled=!undoStack.length;if(r)r.disabled=!redoStack.length;}
  function checkpoint(){undoStack.push(authoringSnapshot());if(undoStack.length>50)undoStack.shift();redoStack.length=0;updateHistoryButtons();}
  function restoreSnapshot(snap){scenario().deployment=structuredClone(snap.deployment||{placements:{},commanderPlacements:{},zones:[]});for(const r of commandRecords()){if(Object.prototype.hasOwnProperty.call(snap.reserves||{},r.command.id))r.command.reserve=structuredClone(snap.reserves[r.command.id]);else delete r.command.reserve;}persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));render();updateHistoryButtons();}
  function undo(){if(!undoStack.length)return;redoStack.push(authoringSnapshot());restoreSnapshot(undoStack.pop());}
  function redo(){if(!redoStack.length)return;undoStack.push(authoringSnapshot());restoreSnapshot(redoStack.pop());}
  function persistDeployment(){persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));render();}
  function setToolStatus(text=''){const el=$('#deploymentToolStatus');if(el)el.textContent=text||'Ready';}

  function worldPlacement(kind,id,p){const d=playDims(),u=kind==='unit'?unitIndex().get(id):null,tt=scenario().tabletop||{},legacy=Number(tt.unitBaseMm||50),defaultW=Number(tt.unitBaseWidthMm||legacy),defaultD=Number(tt.unitBaseDepthMm||legacy),baseMm=kind==='unit'?Number(u?.baseMm||legacy):Number(tt.commanderBaseMm||25);return{x:Number(p.x)/100*d.width,y:Number(p.y)/100*d.height,facing:normDeg(p.facing||0),baseMm,baseWidthMm:kind==='unit'?Number(u?.baseWidthMm||defaultW):baseMm,baseDepthMm:kind==='unit'?Number(u?.baseDepthMm||defaultD):baseMm,kind,baseShape:kind==='commander'?'circle':'rect'};}
  function resolvedUnitGeometry(u){const tt=scenario().tabletop||{},legacy=Number(tt.unitBaseMm||50),scenarioW=Number(tt.unitBaseWidthMm||legacy),scenarioD=Number(tt.unitBaseDepthMm||legacy),profile=getEffectiveRuleset(scenario()).unitLibrary.find(x=>x.profile===u.profile)||{},explicitLegacy=u.baseMm!=null&&String(u.baseMm).trim()!==''?Number(u.baseMm):null,fixed=!!profile.asset&&Number(profile.baseMm)>0,baseMm=Number(Number.isFinite(explicitLegacy)&&explicitLegacy>0?explicitLegacy:(fixed?profile.baseMm:legacy)),profileW=Number(profile.baseWidthMm||((Number.isFinite(explicitLegacy)&&explicitLegacy>0)||fixed?baseMm:scenarioW)),profileD=Number(profile.baseDepthMm||((Number.isFinite(explicitLegacy)&&explicitLegacy>0)||fixed?baseMm:scenarioD));return{baseMm,baseWidthMm:Number(u.baseWidthMm||profileW),baseDepthMm:Number(u.baseDepthMm||profileD)};}
  function unitIndex(){const map=new Map();for(const c of commands())for(const u of c.units||[])map.set(u.id,{...u,...resolvedUnitGeometry(u),faction:c.faction,commandId:c.id,commandIndex:c.commandIndex,commandName:c.name,commandCommander:c.commander});return map;}
  function pctFromEvent(e,rect=null,clampToFrame=true){const r=rect||frame.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;return clampToFrame?{x:Math.max(0,Math.min(100,x)),y:Math.max(0,Math.min(100,y))}:{x,y};}
  function zonePoints(z){if(Array.isArray(z.points)&&z.points.length>=3)return z.points;if(Number.isFinite(z.x))return[{x:z.x,y:z.y},{x:z.x+z.width,y:z.y},{x:z.x+z.width,y:z.y+z.height},{x:z.x,y:z.y+z.height}];return[];}
  function ensurePolygonZones(){scenario().deployment=scenario().deployment||{placements:{},commanderPlacements:{},zones:[]};scenario().deployment.placements=scenario().deployment.placements||{};scenario().deployment.commanderPlacements=scenario().deployment.commanderPlacements||{};scenario().deployment.zones=scenario().deployment.zones||[];for(const z of scenario().deployment.zones){if(!z.points){z.points=zonePoints(z);delete z.x;delete z.y;delete z.width;delete z.height;}}}
  ensurePolygonZones();

  function reserveSummary(c){const r=c?.reserve;if(!r?.enabled)return'';const e=r.entry||{};let where='entry not set';if(e.type==='point')where=`point ${Number(e.x||0).toFixed(0)}%, ${Number(e.y||0).toFixed(0)}%`;else if(e.type==='edge')where=`${e.edge||'edge'} edge`;else if(e.type==='edge-segment')where=`${e.edge||'edge'} ${Number(e.startPct||0).toFixed(0)}–${Number(e.endPct||100).toFixed(0)}%`;else if(e.type==='zone'){const z=scenario().deployment.zones.find(z=>z.id===e.zoneId);where=z?`zone ${z.name}`:'deployment zone';}return`RESERVE · Turn ${Number(r.deploymentTurn||1)} · ${where}`;}
  function setReserveTurn(c){const command=actualCommand(c.faction,c.id)||c,current=command.reserve||{},raw=prompt('Reserve deployment turn (enters at end of owning player turn):',String(current.deploymentTurn||1));if(raw===null)return;const deploymentTurn=Math.max(1,Math.floor(Number(raw)||1));checkpoint();command.reserve={...current,enabled:true,deploymentTurn};persistDeployment();}
  function removeReserve(c){const command=actualCommand(c.faction,c.id)||c;if(!confirm(`Remove reserve status from ${command.name}?`))return;checkpoint();delete command.reserve;persistDeployment();}
  function clearReserveEntry(c){const command=actualCommand(c.faction,c.id)||c;if(!command.reserve?.enabled)return;checkpoint();command.reserve={...command.reserve,entry:null};persistDeployment();}
  function startReserveTool(c,type){const command=actualCommand(c.faction,c.id)||c;if(!command.reserve?.enabled){alert('Set the command as a reserve and choose its deployment turn first.');return;}stopZoneMode();reserveTool={commandId:command.id,faction:c.faction,type,start:null,current:null,edge:null};zoneMode=`reserve-${type}`;frame.classList.add('zone-mode');$('#cancelDeploymentTool').hidden=false;if(type==='zone'){$('#finishPolygonZone').hidden=false;$('#finishPolygonZone').textContent='Finish reserve zone';setToolStatus(`Reserve entry for ${command.name}: click polygon vertices, then Finish reserve zone. Esc cancels.`);}else if(type==='edge-segment')setToolStatus(`Reserve entry for ${command.name}: drag along the desired table-edge portion. Esc cancels.`);else if(type==='edge')setToolStatus(`Reserve entry for ${command.name}: click near the desired table edge. Esc cancels.`);else setToolStatus(`Reserve entry for ${command.name}: click the entry point on the map. Esc cancels.`);renderZones();}
  function commitReserveEntry(entry){if(!reserveTool)return;const command=actualCommand(reserveTool.faction,reserveTool.commandId);if(!command)return;checkpoint();command.reserve={...(command.reserve||{}),enabled:true,deploymentTurn:Number(command.reserve?.deploymentTurn||1),entry};persistDeployment();stopZoneMode();}
  function newReserveZone(points){if(points.length<3||!reserveTool)return;const command=actualCommand(reserveTool.faction,reserveTool.commandId);if(!command)return;checkpoint();const z={id:uid('zone'),name:`${command.name} reserve entry`,faction:reserveTool.faction,reserveEntryFor:command.id,points:points.map(p=>({x:p.x,y:p.y}))};scenario().deployment.zones.push(z);command.reserve={...(command.reserve||{}),enabled:true,deploymentTurn:Number(command.reserve?.deploymentTurn||1),entry:{type:'zone',zoneId:z.id}};selected={kind:'zone',id:z.id};persistDeployment();stopZoneMode();}

  function symbolFor(profile){const x=(profile||'').toLowerCase();if(x.includes('camp'))return'CAMP';if(x.includes('baggage'))return'LOG';if(x.includes('cannon')||x.includes('artillery'))return'●';if(x.includes('cavalry')||x.includes('gendar')||x.includes('knight')||x.includes('ginete')||x.includes('stradiot'))return'/';return'×';}
  function renderReserveControls(body,c){const reserve=!!c.reserve?.enabled;if(!reserve){const b=document.createElement('button');b.type='button';b.className='secondary small';b.textContent='Set as reserve';b.addEventListener('click',e=>{e.preventDefault();setReserveTurn(c);});body.appendChild(b);return;}const wrap=document.createElement('div');wrap.className='reserve-entry-controls';wrap.innerHTML=`<button type="button" class="secondary small" data-reserve-turn>Turn ${Number(c.reserve.deploymentTurn||1)}</button><span class="reserve-entry-label">Draw entry:</span><button type="button" class="secondary small" data-reserve-entry="point">Point</button><button type="button" class="secondary small" data-reserve-entry="edge">Edge</button><button type="button" class="secondary small" data-reserve-entry="edge-segment">Edge portion</button><button type="button" class="secondary small" data-reserve-entry="zone">Zone</button><button type="button" class="link-button" data-reserve-clear>Clear entry</button><button type="button" class="link-button danger-text" data-reserve-remove>Remove reserve</button>`;wrap.querySelector('[data-reserve-turn]').onclick=e=>{e.preventDefault();setReserveTurn(c);};wrap.querySelectorAll('[data-reserve-entry]').forEach(b=>b.onclick=e=>{e.preventDefault();startReserveTool(c,b.dataset.reserveEntry);});wrap.querySelector('[data-reserve-clear]').onclick=e=>{e.preventDefault();clearReserveEntry(c);};wrap.querySelector('[data-reserve-remove]').onclick=e=>{e.preventDefault();removeReserve(c);};body.appendChild(wrap);}
  function renderTree(){tree.innerHTML='';let serial=0;for(const c of commands()){const placed=scenario().deployment.placements||{},reserve=!!c.reserve?.enabled,done=(c.units||[]).filter(u=>placed[u.id]).length;const section=document.createElement('details');section.className='deployment-command';section.open=true;const status=reserve?reserveSummary(c):`${done}/${(c.units||[]).length} deployed`;section.innerHTML=`<summary draggable="true" data-command-drag="${c.id}" data-faction="${c.faction}"><span><strong>${safe(c.name)}</strong><small>${safe(c.commander||'No commander assigned')}</small></span><span class="deploy-count">${safe(status)}</span><span class="count-pill">${(c.units||[]).length}</span></summary><div class="deployment-command-body"></div>`;const body=section.querySelector('.deployment-command-body');renderReserveControls(body,c);if(c.commander){const yes=!!scenario().deployment.commanderPlacements?.[c.id],leader=document.createElement('div');leader.className=`deployment-tree-item commander-tree ${yes?'deployed':''}`;leader.draggable=!reserve;leader.dataset.dragType='commander';leader.dataset.commandId=c.id;leader.dataset.faction=c.faction;const stateText=reserve?'↳ Off-table reserve':yes?'✓ Deployed':'○ Undeployed';leader.innerHTML=`<span class="commander-symbol">★</span><span><strong>${safe(c.commander)}</strong><small>Commander · ${scenario().tabletop?.commanderBaseMm||25} mm circle · <b class="deploy-state ${yes?'yes':'no'}">${stateText}</b></small></span>`;if(!reserve)leader.addEventListener('dragstart',dragTree);body.appendChild(leader);}for(const u of c.units||[]){serial++;const yes=!!placed[u.id],row=document.createElement('div');row.className=`deployment-tree-item ${yes?'deployed':''}`;row.draggable=!reserve;row.dataset.dragType='unit';row.dataset.unitId=u.id;row.dataset.commandId=c.id;row.dataset.faction=c.faction;const geom=resolvedUnitGeometry(u),stateText=reserve?'↳ Off-table reserve':yes?'✓ Deployed':'○ Undeployed';row.innerHTML=`<span class="unit-mini ${c.faction.toLowerCase()}">${symbolFor(u.profile)}</span><span><strong>${safe(u.name)}</strong><small>${safe(u.profile)} · ${geom.baseWidthMm}×${geom.baseDepthMm} mm · <b class="deploy-state ${yes?'yes':'no'}">${stateText}</b></small></span>`;row.dataset.unitCode=`${c.faction[0]}${serial}`;if(!reserve)row.addEventListener('dragstart',dragTree);body.appendChild(row);}section.querySelector('summary').addEventListener('dragstart',e=>{if(reserve){e.preventDefault();return;}e.dataTransfer.setData('application/x-bax-deployment',JSON.stringify({type:'command',commandId:c.id,faction:c.faction}));});tree.appendChild(section);}}
  function dragTree(e){e.dataTransfer.setData('application/x-bax-deployment',JSON.stringify({type:e.currentTarget.dataset.dragType,unitId:e.currentTarget.dataset.unitId||null,commandId:e.currentTarget.dataset.commandId,faction:e.currentTarget.dataset.faction}));}
  function placeData(data,p){checkpoint();const dep=scenario().deployment;if(data.type==='unit'){const q=nearestLegalPlacement('unit',data.unitId,p);if(q)dep.placements[data.unitId]={x:q.x,y:q.y,facing:0,faction:data.faction,commandId:data.commandId};}if(data.type==='commander'){const q=nearestLegalPlacement('commander',data.commandId,p);if(q)dep.commanderPlacements[data.commandId]={x:q.x,y:q.y,faction:data.faction};}if(data.type==='command'){const c=actualCommand(data.faction,data.commandId);if(!c)return;let i=0;for(const u of c.units||[]){const col=i%3,row=Math.floor(i/3),q=nearestLegalPlacement('unit',u.id,{x:p.x+(col-1)*5,y:p.y+row*5});if(q)dep.placements[u.id]={x:q.x,y:q.y,facing:0,faction:data.faction,commandId:c.id};i++;}if(c.commander){const q=nearestLegalPlacement('commander',c.id,{x:p.x,y:p.y-4});if(q)dep.commanderPlacements[c.id]={x:q.x,y:q.y,faction:data.faction};}}persistDeployment();}
  function commandColor(faction,index=0){const palettes={French:['#164A7A','#2376BD','#49A0D8','#285A8F','#196F82','#5A57B5','#2E87A7'],Imperial:['#7E2727','#A93A32','#D45A4D','#8B405D','#B96A32','#C64468','#6D3947']};const a=palettes[faction]||['#4d6380','#66809f','#384e68'];return a[index%a.length];}
  function pieceEl(kind,id,p,meta){const el=document.createElement('button');el.className=`deployment-piece ${kind} ${meta.faction.toLowerCase()} ${meta.asset?'asset':''}`;el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.style.transform=`translate(-50%,-50%) rotate(${normDeg(p.facing||0)}deg)`;el.style.setProperty('--label-counter-rotation',`${-normDeg(p.facing||0)}deg`);el.dataset.kind=kind;el.dataset.id=id;el.draggable=false;if(kind==='unit'){const tt=scenario().tabletop||{},legacy=Number(tt.unitBaseMm||50),configuredW=Number(tt.unitBaseWidthMm||legacy),configuredD=Number(tt.unitBaseDepthMm||legacy),mm=Number(meta.baseMm||legacy),entity={kind:'unit',baseMm:mm,baseWidthMm:Number(meta.baseWidthMm||configuredW),baseDepthMm:Number(meta.baseDepthMm||configuredD)},fp=footprintPercentFromSpec(entity,state.project.playSpace||{},{});el.style.width=`${fp.width}%`;el.style.height=`${fp.height}%`;el.style.background=commandColor(meta.faction,meta.commandIndex);el.innerHTML=`<span class="deployment-facing-arrow" aria-hidden="true"></span><span class="piece-label">${safe(meta.name)}</span>`;el.title=`${meta.name} (${meta.profile}) · ${entity.baseWidthMm}×${entity.baseDepthMm} mm footprint · front is the ${entity.baseWidthMm} mm edge · drag to reposition`;}else{const mm=Number(scenario().tabletop?.commanderBaseMm||25),entity={kind:'commander',baseMm:mm,baseShape:'circle'},fp=footprintPercentFromSpec(entity,state.project.playSpace||{},{});el.style.width=`${fp.width}%`;el.style.height=`${fp.height}%`;el.style.background=commandColor(meta.faction,meta.commandIndex);el.innerHTML='★';el.title=`${meta.name} · ${mm} mm round footprint · drag to reposition`;}el.addEventListener('pointerdown',e=>{if(zoneMode)return;e.preventDefault();e.stopPropagation();checkpoint();selected={kind,id};dragFrameRect=frame.getBoundingClientRect();const pointerStart=pctFromEvent(e,dragFrameRect,false);dragPiece={kind,id,pointerId:e.pointerId,moved:false,pointerStart,origin:{x:Number(p.x),y:Number(p.y),facing:normDeg(p.facing||0)},last:{x:Number(p.x),y:Number(p.y),facing:normDeg(p.facing||0)},el};el.setPointerCapture?.(e.pointerId);el.classList.add('dragging');renderSelection();});el.addEventListener('click',e=>e.stopPropagation());return el;}
  function placementEntity(kind,id){const tt=scenario().tabletop||{},legacy=Number(tt.unitBaseMm||50);if(kind==='unit'){const u=unitIndex().get(id),mm=Number(u?.baseMm||legacy),w=Number(u?.baseWidthMm||tt.unitBaseWidthMm||legacy),d=Number(u?.baseDepthMm||tt.unitBaseDepthMm||legacy);return{kind:'unit',baseMm:mm,baseWidthMm:w,baseDepthMm:d,baseShape:'rect'};}const mm=Number(tt.commanderBaseMm||25);return{kind:'commander',baseMm:mm,baseWidthMm:mm,baseDepthMm:mm,baseShape:'circle'};}
  function clampPiecePoint(kind,id,p){const fp=footprintPercentFromSpec(placementEntity(kind,id),state.project.playSpace||{},{}),hx=fp.width/2,hy=fp.height/2;return{x:Math.max(hx,Math.min(100-hx,p.x)),y:Math.max(hy,Math.min(100-hy,p.y))};}
  function placementClear(kind,id,p){const d=playDims(),w=worldPlacement(kind,id,p);if(!footprintInsideBattlefield(w,d.width,d.height,w.x,w.y,w.facing))return false;for(const [oid,op] of Object.entries(scenario().deployment.placements||{})){if(kind==='unit'&&oid===id)continue;const ow=worldPlacement('unit',oid,op);if(footprintsPenetrate(w,ow))return false;}for(const [oid,op] of Object.entries(scenario().deployment.commanderPlacements||{})){if(kind==='commander'&&oid===id)continue;const ow=worldPlacement('commander',oid,op);if(footprintsPenetrate(w,ow))return false;}return true;}
  function deploymentGeometryIssues(){const d=playDims(),actors=[];for(const [id,p] of Object.entries(scenario().deployment.placements||{})){if(unitIndex().has(id))actors.push({kind:'unit',id,label:unitIndex().get(id)?.name||id,world:worldPlacement('unit',id,p)});}for(const [id,p] of Object.entries(scenario().deployment.commanderPlacements||{})){const c=commands().find(x=>x.id===id);if(c)actors.push({kind:'commander',id,label:c.commander||c.name||id,world:worldPlacement('commander',id,p)});}const issues=[];for(const a of actors)if(!footprintInsideBattlefield(a.world,d.width,d.height,a.world.x,a.world.y,a.world.facing))issues.push({kind:'off-table',actors:[`${a.kind}:${a.id}`],message:`${a.label} has a base footprint outside the battlefield.`});for(let i=0;i<actors.length;i++)for(let j=i+1;j<actors.length;j++)if(footprintsPenetrate(actors[i].world,actors[j].world))issues.push({kind:'overlap',actors:[`${actors[i].kind}:${actors[i].id}`,`${actors[j].kind}:${actors[j].id}`],message:`${actors[i].label} overlaps ${actors[j].label}.`});return issues;}
  function nearestLegalPlacement(kind,id,p){const base=clampPiecePoint(kind,id,p);if(placementClear(kind,id,base))return base;for(let radius=.75;radius<=20;radius+=.75)for(let deg=0;deg<360;deg+=30){const r=deg*Math.PI/180,q=clampPiecePoint(kind,id,{x:base.x+Math.cos(r)*radius,y:base.y+Math.sin(r)*radius});if(placementClear(kind,id,q))return q;}return null;}
  function renderPieces(){syncAspect();pieces.innerHTML='';const idx=unitIndex(),invalid=new Set(deploymentGeometryIssues().flatMap(x=>x.actors||[]));let n=0;for(const [id,p] of Object.entries(scenario().deployment.placements||{})){const u=idx.get(id);if(u){n++;const el=pieceEl('unit',id,p,{name:u.name,profile:u.profile,faction:u.faction,code:`${u.faction[0]}${n}`,asset:['Camp','Baggage Train'].includes(u.profile),baseMm:Number(u.baseMm||scenario().tabletop?.unitBaseMm||50),baseWidthMm:Number(u.baseWidthMm),baseDepthMm:Number(u.baseDepthMm),commandId:u.commandId,commandIndex:u.commandIndex});el.classList.toggle('illegal-placement',invalid.has(`unit:${id}`));pieces.appendChild(el);}}for(const [id,p] of Object.entries(scenario().deployment.commanderPlacements||{})){const c=commands().find(x=>x.id===id);if(c){const el=pieceEl('commander',id,p,{name:c.commander,faction:c.faction,commandIndex:c.commandIndex});el.classList.toggle('illegal-placement',invalid.has(`commander:${id}`));pieces.appendChild(el);}}if(selected?.kind!=='zone')document.querySelectorAll('.deployment-piece').forEach(el=>el.classList.toggle('selected',el.dataset.kind===selected?.kind&&el.dataset.id===selected?.id));}
  function svgEl(name,attrs={}){const e=document.createElementNS('http://www.w3.org/2000/svg',name);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
  function centroid(points){return{x:points.reduce((a,p)=>a+p.x,0)/points.length,y:points.reduce((a,p)=>a+p.y,0)/points.length};}
  function addReserveOverlay(c){const e=c.reserve?.entry;if(!c.reserve?.enabled||!e)return;const cls=`reserve-entry ${c.faction.toLowerCase()}`;if(e.type==='point'){const g=svgEl('g',{class:cls});g.appendChild(svgEl('circle',{cx:e.x,cy:e.y,r:'1.6',class:'reserve-entry-point'}));const t=svgEl('text',{x:Number(e.x)+2,y:Number(e.y)-2,class:'reserve-entry-label-map'});t.textContent=`${c.name} entry`;g.appendChild(t);zonesHost.appendChild(g);return;}if(e.type==='edge'||e.type==='edge-segment'){const l=edgeEntryLine(e.edge,e.type==='edge'?0:e.startPct,e.type==='edge'?100:e.endPct),g=svgEl('g',{class:cls});g.appendChild(svgEl('line',{...l,class:'reserve-entry-line'}));const t=svgEl('text',{x:(l.x1+l.x2)/2+(e.edge==='west'?2:e.edge==='east'?-2:0),y:(l.y1+l.y2)/2+(e.edge==='north'?3:e.edge==='south'?-2:0),class:'reserve-entry-label-map'});t.textContent=`${c.name} entry`;g.appendChild(t);zonesHost.appendChild(g);return;}if(e.type==='zone'){const z=scenario().deployment.zones.find(x=>x.id===e.zoneId),pts=z?zonePoints(z):[];if(pts.length<3)return;const g=svgEl('g',{class:cls});g.appendChild(svgEl('polygon',{points:pts.map(p=>`${p.x},${p.y}`).join(' '),class:'reserve-entry-zone-outline'}));const mid=centroid(pts),t=svgEl('text',{x:mid.x,y:mid.y+3,class:'reserve-entry-label-map'});t.textContent=`Reserve: ${c.name}`;g.appendChild(t);zonesHost.appendChild(g);}}
  function renderZones(){zonesHost.innerHTML='';for(const z of scenario().deployment.zones||[]){const pts=zonePoints(z);if(pts.length<3)continue;const g=svgEl('g',{'data-zone':z.id,class:`zone-group ${String(z.faction||'neutral').toLowerCase()}${selected?.kind==='zone'&&selected.id===z.id?' selected':''}`});const poly=svgEl('polygon',{points:pts.map(p=>`${p.x},${p.y}`).join(' '),class:'deployment-zone-poly'});poly.addEventListener('pointerdown',e=>{if(zoneMode)return;e.stopPropagation();checkpoint();selected={kind:'zone',id:z.id};dragZone={id:z.id,start:pctFromEvent(e),original:pts.map(p=>({...p}))};poly.setPointerCapture?.(e.pointerId);renderSelection();});g.appendChild(poly);const c=centroid(pts),text=svgEl('text',{x:c.x,y:c.y,class:'deployment-zone-label'});text.textContent=z.name;g.appendChild(text);if(selected?.kind==='zone'&&selected.id===z.id){pts.forEach((p,i)=>{const h=svgEl('circle',{cx:p.x,cy:p.y,r:'1.25',class:'zone-vertex','data-vertex':i});h.addEventListener('pointerdown',e=>{if(zoneMode)return;e.stopPropagation();checkpoint();dragVertex={id:z.id,index:i,original:pts.map(q=>({...q}))};h.setPointerCapture?.(e.pointerId);});g.appendChild(h);});}zonesHost.appendChild(g);}for(const c of commands())addReserveOverlay(c);if(['polygon','reserve-zone'].includes(zoneMode)&&polyPoints.length){const pl=svgEl('polyline',{points:polyPoints.map(p=>`${p.x},${p.y}`).join(' '),class:'zone-preview-line'});zonesHost.appendChild(pl);for(const p of polyPoints)zonesHost.appendChild(svgEl('circle',{cx:p.x,cy:p.y,r:'1',class:'zone-preview-point'}));}if(zoneMode==='reserve-edge-segment'&&reserveTool?.edge&&reserveTool.start!=null&&reserveTool.current!=null){const l=edgeEntryLine(reserveTool.edge,reserveTool.start,reserveTool.current);zonesHost.appendChild(svgEl('line',{...l,class:'reserve-entry-line preview'}));}}
  function renderWarnings(){syncBattlefieldImages(state);const idx=unitIndex(),placed=scenario().deployment.placements||{},cp=scenario().deployment.commanderPlacements||{},reserveIds=new Set(commands().filter(c=>c.reserve?.enabled).map(c=>c.id));const missingUnits=[...idx.values()].filter(u=>!placed[u.id]&&!reserveIds.has(u.commandId)),missingCmd=commands().filter(c=>c.commander&&!cp[c.id]&&!c.reserve?.enabled),geometryIssues=deploymentGeometryIssues();const warnings=[];if(!idx.size)warnings.push('No Battle Axe units are currently available for deployment.');else{if(missingUnits.length)warnings.push(`${missingUnits.length} unit${missingUnits.length===1?' is':'s are'} not deployed`);if(missingCmd.length)warnings.push(`${missingCmd.length} commander${missingCmd.length===1?' is':'s are'} not placed`);}for(const c of commands().filter(c=>c.reserve?.enabled))if(!c.reserve?.entry)warnings.push(`${c.name} is a reserve command but has no visual entry point/edge/zone.`);for(const issue of geometryIssues)warnings.push(`Illegal base geometry: ${issue.message}`);if(!state.project.mapSource)warnings.push('No battlefield map is generated for the current scenario.');if(scenario().deployment?.battlefieldRevision&&state.project.battlefieldRevision&&scenario().deployment.battlefieldRevision!==state.project.battlefieldRevision)warnings.push('Deployment belongs to an earlier battlefield revision and must be reviewed.');$('#deploymentWarningCount').textContent=warnings.length;$('#deploymentWarnings').innerHTML=warnings.length?`<ul>${warnings.map(x=>`<li>${safe(x)}</li>`).join('')}</ul>`:'<p class="success">All current force-list objects are placed with legal physical footprints.</p>';$('#deploymentStatus').textContent=`${Object.keys(placed).length}/${idx.size} units placed${geometryIssues.length?` · ${geometryIssues.length} geometry issue${geometryIssues.length===1?'':'s'}`:''}`;}
  function renderSelection(){const host=$('#deploymentSelection'),remove=$('#removeDeploymentObject'),addV=$('#addZoneVertex'),delV=$('#deleteZoneVertex'),rotL=$('#rotateDeploymentLeft'),rotR=$('#rotateDeploymentRight');if(!selected){host.innerHTML='<p class="muted">Select a deployed unit, commander, or zone.</p>';remove.disabled=true;if(addV)addV.disabled=true;if(delV)delV.disabled=true;if(rotL)rotL.disabled=true;if(rotR)rotR.disabled=true;return;}remove.disabled=false;if(rotL)rotL.disabled=selected.kind!=='unit';if(rotR)rotR.disabled=selected.kind!=='unit';if(selected.kind==='unit'){const u=unitIndex().get(selected.id),p=scenario().deployment.placements[selected.id];host.innerHTML=u?`<strong>${safe(u.name)}</strong><p>${safe(u.commandName)} · ${safe(u.profile)}</p><small>${p.x.toFixed(1)}%, ${p.y.toFixed(1)}% · facing ${normDeg(p.facing||0).toFixed(0)}°</small>`:'<p>Unit placement</p>';if(u){const peers=[...unitIndex().values()].filter(x=>x.commandId===u.commandId&&scenario().deployment.placements?.[x.id]);if(peers.length>1){host.insertAdjacentHTML('beforeend',`<div class="deployment-bulk-rotate"><small>Command facing · ${peers.length} deployed units</small><div><button type="button" data-command-rotate="-15">↺ Rotate command</button> <button type="button" data-command-rotate="15">Rotate command ↻</button></div></div>`);host.querySelectorAll('[data-command-rotate]').forEach(b=>b.addEventListener('click',()=>rotateSelectedCommand(Number(b.dataset.commandRotate)||0)));}}}else if(selected.kind==='commander'){const c=commands().find(x=>x.id===selected.id);host.innerHTML=c?`<strong>${safe(c.commander)}</strong><p>Commander · ${safe(c.name)}</p>`:'<p>Commander placement</p>';}else{const z=scenario().deployment.zones.find(x=>x.id===selected.id),pts=z?zonePoints(z):[];host.innerHTML=z?`<strong>${safe(z.name)}</strong><p>${safe(z.faction||'Unassigned')} deployment zone · ${pts.length} vertices</p><small>Drag the polygon to move it. Drag yellow vertex handles to reshape it.</small>`:'<p>Deployment zone</p>';if(addV)addV.disabled=!z;if(delV)delV.disabled=!z||pts.length<=3;}}
  function unlinkZoneFromReserves(zoneId){for(const r of commandRecords())if(r.command.reserve?.entry?.type==='zone'&&r.command.reserve.entry.zoneId===zoneId)r.command.reserve={...r.command.reserve,entry:null};}
  function removeSelected(){if(!selected)return;checkpoint();if(selected.kind==='unit')delete scenario().deployment.placements[selected.id];else if(selected.kind==='commander')delete scenario().deployment.commanderPlacements[selected.id];else{unlinkZoneFromReserves(selected.id);scenario().deployment.zones=scenario().deployment.zones.filter(z=>z.id!==selected.id);}selected=null;persistDeployment();}
  function render(){scaleNote();renderTree();renderPieces();renderZones();renderWarnings();renderSelection();updateHistoryButtons();}
  function newZone(points){if(points.length<3)return;const name=prompt('Deployment zone name:','New deployment zone')||'Deployment zone',a=sideLabel(scenario(),SIDE_KEYS[0]),b=sideLabel(scenario(),SIDE_KEYS[1]),raw=prompt(`Assign to side (${a}, ${b}, or leave blank):`,'')||'',faction=raw?(sideForFaction(scenario(),raw,{assign:false})||raw):'';checkpoint();scenario().deployment.zones.push({id:uid('zone'),name,faction,points:points.map(p=>({x:p.x,y:p.y}))});selected={kind:'zone',id:scenario().deployment.zones.at(-1).id};persistDeployment();}
  function stopZoneMode(){zoneMode=null;zoneStart=null;preview?.remove?.();preview=null;polyPoints=[];reserveTool=null;$('#addDeploymentZone').textContent='Rectangle zone';$('#addPolygonZone').textContent='Polygon zone';$('#finishPolygonZone').hidden=true;$('#finishPolygonZone').textContent='Finish polygon';frame.classList.remove('zone-mode');const c=$('#cancelDeploymentTool');if(c)c.hidden=true;setToolStatus('Ready');renderZones();}

  function updatePieceDrag(e){if(!dragPiece)return;const pointer=pctFromEvent(e,dragFrameRect,false),p=dragCenterFromGrab(dragPiece.origin,dragPiece.pointerStart,pointer),dx=p.x-dragPiece.origin.x,dy=p.y-dragPiece.origin.y,el=dragPiece.el||pieces.querySelector(`[data-kind="${dragPiece.kind}"][data-id="${dragPiece.id}"]`);dragPiece.last=p;dragPiece.moved=dragPiece.moved||Math.abs(dx)>.02||Math.abs(dy)>.02;if(el){el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.style.transform=`translate(-50%,-50%) rotate(${normDeg(p.facing||0)}deg)`;el.style.setProperty('--label-counter-rotation',`${-normDeg(p.facing||0)}deg`);const legal=placementClear(dragPiece.kind,dragPiece.id,p);el.classList.toggle('drag-valid',legal);el.classList.toggle('drag-invalid',!legal);}}
  function schedulePieceDrag(e){pendingDragEvent={clientX:e.clientX,clientY:e.clientY};if(dragRaf)return;dragRaf=requestAnimationFrame(()=>{dragRaf=0;if(pendingDragEvent){updatePieceDrag(pendingDragEvent);pendingDragEvent=null;}});}
  frame.addEventListener('dragover',e=>e.preventDefault());
  frame.addEventListener('drop',e=>{if(zoneMode)return;e.preventDefault();const p=pctFromEvent(e),treeRaw=e.dataTransfer.getData('application/x-bax-deployment'),depRaw=e.dataTransfer.getData('application/x-bax-deployed');if(treeRaw){placeData(JSON.parse(treeRaw),p);return;}if(depRaw){const d=JSON.parse(depRaw),q=nearestLegalPlacement(d.kind,d.id,p);if(q){checkpoint();if(d.kind==='unit')scenario().deployment.placements[d.id]={...scenario().deployment.placements[d.id],...q};else scenario().deployment.commanderPlacements[d.id]={...scenario().deployment.commanderPlacements[d.id],...q};persistDeployment();}}});
  frame.addEventListener('click',e=>{if(zoneMode==='polygon'||zoneMode==='reserve-zone'){if(e.target.closest('.zone-vertex'))return;polyPoints.push(pctFromEvent(e));renderZones();return;}if(zoneMode==='reserve-point'){const p=pctFromEvent(e);commitReserveEntry({type:'point',x:p.x,y:p.y});return;}if(zoneMode==='reserve-edge'){const p=pctFromEvent(e),edge=nearestBattlefieldEdge(p);commitReserveEntry({type:'edge',edge});return;}if(zoneMode)return;selected=null;render();});
  function rotateSelectedCommand(delta){if(selected?.kind!=='unit'||!delta)return;const idx=unitIndex(),u=idx.get(selected.id);if(!u)return;const placements=scenario().deployment.placements||{},ids=[...idx.values()].filter(x=>x.commandId===u.commandId&&placements[x.id]).map(x=>x.id);if(ids.length<2)return;const snapshot=Object.fromEntries(ids.map(id=>[id,{...placements[id]}]));checkpoint();for(const id of ids)placements[id]={...placements[id],facing:normDeg(Number(placements[id].facing||0)+delta)};const legal=ids.every(id=>placementClear('unit',id,placements[id]));if(!legal){for(const id of ids)placements[id]=snapshot[id];undoStack.pop();updateHistoryButtons();alert('That command rotation would place one or more units off the battlefield or overlapping another base. No units were rotated.');render();return;}persistDeployment();}
  function rotateSelected(delta){if(selected?.kind!=='unit')return;const p=scenario().deployment.placements?.[selected.id];if(!p)return;const candidate={...p,facing:normDeg(Number(p.facing||0)+delta)};if(!placementClear('unit',selected.id,candidate)){alert('That rotation would place the unit off the battlefield or overlap another base.');return;}checkpoint();scenario().deployment.placements[selected.id]=candidate;persistDeployment();}
  $('#rotateDeploymentLeft')?.addEventListener('click',()=>rotateSelected(-15));$('#rotateDeploymentRight')?.addEventListener('click',()=>rotateSelected(15));$('#deploymentUndo')?.addEventListener('click',undo);$('#deploymentRedo')?.addEventListener('click',redo);
  $('#removeDeploymentObject')?.addEventListener('click',removeSelected);$('#clearDeploymentSelection')?.addEventListener('click',()=>{selected=null;render();});
  $('#addDeploymentZone')?.addEventListener('click',()=>{stopZoneMode();zoneMode='rect';$('#addDeploymentZone').textContent='Drag rectangle…';frame.classList.add('zone-mode');$('#cancelDeploymentTool').hidden=false;setToolStatus('Drag a rectangle on the map. Esc cancels.');});
  $('#addPolygonZone')?.addEventListener('click',()=>{stopZoneMode();zoneMode='polygon';$('#addPolygonZone').textContent='Click map vertices…';$('#finishPolygonZone').hidden=false;frame.classList.add('zone-mode');$('#cancelDeploymentTool').hidden=false;setToolStatus('Click polygon vertices, then Finish polygon. Esc cancels.');});
  $('#cancelDeploymentTool')?.addEventListener('click',()=>{stopZoneMode();render();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&zoneMode){stopZoneMode();render();}});
  $('#finishPolygonZone')?.addEventListener('click',()=>{if(zoneMode==='reserve-zone'){if(polyPoints.length>=3)newReserveZone(polyPoints);else alert('A reserve zone needs at least three vertices.');return;}if(zoneMode==='polygon'&&polyPoints.length>=3)newZone(polyPoints);stopZoneMode();render();});
  $('#addZoneVertex')?.addEventListener('click',()=>{if(selected?.kind!=='zone')return;const z=scenario().deployment.zones.find(x=>x.id===selected.id),pts=zonePoints(z);if(!z)return;checkpoint();let best=0,bestD=-1;for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length],d=Math.hypot(a.x-b.x,a.y-b.y);if(d>bestD){bestD=d;best=i;}}const a=pts[best],b=pts[(best+1)%pts.length];pts.splice(best+1,0,{x:(a.x+b.x)/2,y:(a.y+b.y)/2});z.points=pts;persistDeployment();});
  $('#deleteZoneVertex')?.addEventListener('click',()=>{if(selected?.kind!=='zone')return;const z=scenario().deployment.zones.find(x=>x.id===selected.id),pts=zonePoints(z);if(!z||pts.length<=3)return;checkpoint();pts.pop();z.points=pts;persistDeployment();});
  frame.addEventListener('pointerdown',e=>{if(zoneMode==='reserve-edge-segment'){e.preventDefault();const p=pctFromEvent(e);reserveTool.edge=nearestBattlefieldEdge(p);reserveTool.start=edgePercent(reserveTool.edge,p);reserveTool.current=reserveTool.start;renderZones();return;}if(zoneMode!=='rect')return;e.preventDefault();zoneStart=pctFromEvent(e);preview=document.createElement('div');preview.className='deployment-zone preview';$('#deploymentZonePreviewHost').appendChild(preview);});
  frame.addEventListener('pointermove',e=>{if(dragPiece){schedulePieceDrag(e);return;}if(zoneMode==='reserve-edge-segment'&&reserveTool?.edge&&reserveTool.start!=null){reserveTool.current=edgePercent(reserveTool.edge,pctFromEvent(e));renderZones();return;}if(zoneMode==='rect'&&zoneStart&&preview){const p=pctFromEvent(e),x=Math.min(zoneStart.x,p.x),y=Math.min(zoneStart.y,p.y),w=Math.abs(p.x-zoneStart.x),h=Math.abs(p.y-zoneStart.y);Object.assign(preview.style,{left:`${x}%`,top:`${y}%`,width:`${w}%`,height:`${h}%`});return;}if(dragVertex){const z=scenario().deployment.zones.find(x=>x.id===dragVertex.id),p=pctFromEvent(e);if(z){z.points[dragVertex.index]=p;renderZones();}return;}if(dragZone){const z=scenario().deployment.zones.find(x=>x.id===dragZone.id),p=pctFromEvent(e),dx=p.x-dragZone.start.x,dy=p.y-dragZone.start.y;if(z){z.points=dragZone.original.map(q=>({x:Math.max(0,Math.min(100,q.x+dx)),y:Math.max(0,Math.min(100,q.y+dy))}));renderZones();}}});
  frame.addEventListener('pointerup',e=>{if(dragPiece){if(dragRaf){cancelAnimationFrame(dragRaf);dragRaf=0;}pendingDragEvent=null;const p=dragPiece.last||dragPiece.origin,q=placementClear(dragPiece.kind,dragPiece.id,p)?p:dragPiece.origin;dragPiece.el?.classList.remove('dragging','drag-valid','drag-invalid');if(dragPiece.kind==='unit')scenario().deployment.placements[dragPiece.id]={...scenario().deployment.placements[dragPiece.id],...q};else scenario().deployment.commanderPlacements[dragPiece.id]={...scenario().deployment.commanderPlacements[dragPiece.id],...q};dragPiece=null;dragFrameRect=null;persistDeployment();return;}if(zoneMode==='reserve-edge-segment'&&reserveTool?.edge&&reserveTool.start!=null){const end=edgePercent(reserveTool.edge,pctFromEvent(e));commitReserveEntry({type:'edge-segment',edge:reserveTool.edge,startPct:Math.min(reserveTool.start,end),endPct:Math.max(reserveTool.start,end)});return;}if(zoneMode==='rect'&&zoneStart){const p=pctFromEvent(e),x=Math.min(zoneStart.x,p.x),y=Math.min(zoneStart.y,p.y),w=Math.abs(p.x-zoneStart.x),h=Math.abs(p.y-zoneStart.y);preview?.remove();preview=null;zoneStart=null;if(w>=2&&h>=2)newZone([{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}]);stopZoneMode();render();return;}if(dragVertex||dragZone){dragVertex=null;dragZone=null;persistDeployment();}});
  frame.addEventListener('pointercancel',()=>{if(dragPiece){if(dragRaf)cancelAnimationFrame(dragRaf);dragRaf=0;pendingDragEvent=null;dragPiece.el?.classList.remove('dragging','drag-valid','drag-invalid');dragPiece=null;dragFrameRect=null;if(undoStack.length)undoStack.pop();updateHistoryButtons();renderPieces();}if(dragVertex){const z=scenario().deployment.zones.find(x=>x.id===dragVertex.id);if(z&&dragVertex.original)z.points=dragVertex.original;dragVertex=null;if(undoStack.length)undoStack.pop();updateHistoryButtons();renderZones();}if(dragZone){const z=scenario().deployment.zones.find(x=>x.id===dragZone.id);if(z)z.points=dragZone.original;dragZone=null;if(undoStack.length)undoStack.pop();updateHistoryButtons();renderZones();}if(zoneMode)stopZoneMode();});

  document.querySelector('[data-view="deployment"]')?.addEventListener('click',()=>setTimeout(()=>{syncAspect();render();},0));window.addEventListener('bax:battlefield-changed',()=>{selected=null;syncAspect();render();});window.addEventListener('bax:scenario-changed',()=>{syncAspect();render();});syncBattlefieldImages(state);syncAspect();render();return{render};
}
