import { runPlaytest, runBatch, buildRuntimeFromStudio, toPctSnapshot } from './playtestEngine.js?v=0.4.0-alpha.4';
const $=s=>document.querySelector(s);
const safe=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function setupPlaytestCenter(state,persist){
  let currentRun=null,currentBatch=null,replayIndex=0,heatType='movement';
  const settings=()=>({seed:Number($('#playSeed')?.value||42),turns:Number($('#playTurns')?.value||state.project.scenario.metadata?.gameLength||6),runs:Number($('#playRuns')?.value||25),measurementScale:Number($('#playScale')?.value||2),garrisonTurn:Number($('#playGarrisonTurn')?.value||2)});
  function runtimeInfo(){return buildRuntimeFromStudio(state,settings());}
  function readiness(){const rt=runtimeInfo(),scenario=state.project.scenario,allUnits=Object.values(scenario.commands||{}).flatMap(cs=>cs.flatMap(c=>c.units||[])),placed=Object.keys(scenario.deployment?.placements||{}).length,approved=(state.project.features||[]).filter(f=>state.decisions?.[f.id]?.status==='approved').length,w=[];if(!allUnits.length)w.push('No Battle Axe units in the Scenario Builder.');if(!rt.units.length)w.push('No deployed units are available to the browser playtest adapter.');if(placed<allUnits.length)w.push(`${allUnits.length-placed} force-list unit(s) are not deployed and will be omitted.`);if(!rt.units.some(u=>u.faction==='French'))w.push('No deployed French units.');if(!rt.units.some(u=>u.faction==='Imperial'||u.faction==='Garrison'))w.push('No deployed Imperial/Garrison units.');if(!approved)w.push('No terrain features are approved; the run will treat the battlefield as open ground.');$('#playReadySummary').innerHTML=`<dl class="summary-dl"><div><dt>Roster units</dt><dd>${allUnits.length}</dd></div><div><dt>Deployed units</dt><dd>${rt.units.length}</dd></div><div><dt>Placed commanders</dt><dd>${rt.commanders.length}</dd></div><div><dt>Approved terrain</dt><dd>${approved}</dd></div><div><dt>Surprise adapter</dt><dd>${rt.surprise?'On':'Off'}</dd></div><div><dt>Garrison sortie adapter</dt><dd>${rt.sortie?'On':'Off'}</dd></div></dl>${w.length?`<div class="playtest-warnings"><strong>Warnings</strong><ul>${w.map(x=>`<li>${safe(x)}</li>`).join('')}</ul></div>`:'<p class="success">Current scenario has enough data for a browser playtest preview.</p>'}`;return w;}
  function resultCards(r){$('#playSingleResult').innerHTML=r?`<div class="result-card winner-${r.winner.toLowerCase()}"><span>Winner</span><strong>${safe(r.winner)}</strong></div><div class="result-card"><span>Turns</span><strong>${r.turnsCompleted}</strong></div><div class="result-card"><span>French VP</span><strong>${r.victoryPoints.French}</strong></div><div class="result-card"><span>Imperial VP</span><strong>${r.victoryPoints.Imperial}</strong></div><div class="result-card"><span>Events</span><strong>${r.events.length}</strong></div>`:'<p class="muted">Run a deterministic game to see results.</p>';}
  function batchCards(b){if(!b){$('#playBatchResult').innerHTML='<p class="muted">Run a batch to estimate balance.</p>';return;}$('#playBatchResult').innerHTML=`<div class="balance-grid"><div><span>French</span><strong>${b.winPct.French.toFixed(1)}%</strong></div><div><span>Imperial</span><strong>${b.winPct.Imperial.toFixed(1)}%</strong></div><div><span>Draw</span><strong>${b.winPct.Draw.toFixed(1)}%</strong></div><div><span>Avg turns</span><strong>${b.avgTurns.toFixed(1)}</strong></div><div><span>Avg French VP</span><strong>${b.avgVp.French.toFixed(1)}</strong></div><div><span>Avg Imperial VP</span><strong>${b.avgVp.Imperial.toFixed(1)}</strong></div></div><p class="muted">${b.runs} deterministic runs using sequential seeds starting at ${settings().seed}.</p>`;}
  function eventText(ev){if(!ev)return'Setup';const p=ev.payload||{};if(ev.type==='move')return`T${ev.turn} ${ev.actorName} moved ${Number(p.distance||0).toFixed(1)}".`;if(ev.type==='pivot')return`T${ev.turn} ${ev.actorName} pivoted ${Math.abs(Number(p.delta||0)).toFixed(0)}° to facing ${Number(p.to||0).toFixed(0)}°.`;if(ev.type==='attack')return`T${ev.turn} ${ev.actorName} attacked ${p.target}: ${p.hits} hit(s).`;if(ev.type==='artillery')return`T${ev.turn} ${ev.actorName} bombardment roll ${p.roll}.`;if(ev.type==='unit_destroyed')return`T${ev.turn} ${ev.actorName} destroyed.`;if(ev.type==='command_test')return`T${ev.turn} ${ev.actorName} command test ${p.roll} vs ${p.threshold}+ — ${p.outcome}.`;if(ev.type==='engagement')return`T${ev.turn} ${ev.actorName} engaged ${p.target}.`;if(ev.type==='reinforcement_activated')return`T${ev.turn} ${ev.actorName} entered play.`;return`T${ev.turn||0} ${ev.actorName||''} ${ev.type.replaceAll('_',' ')}.`;}
  function renderReplay(){const host=$('#playReplayPieces'),label=$('#replayEventLabel'),slider=$('#replaySlider');host.innerHTML='';if(!currentRun){label.textContent='No replay loaded';slider.max=0;slider.value=0;drawHeat();return;}replayIndex=Math.max(0,Math.min(currentRun.snapshots.length-1,replayIndex));slider.max=currentRun.snapshots.length-1;slider.value=replayIndex;const snap=toPctSnapshot(currentRun.snapshots[replayIndex],state);for(const u of snap.units){const el=document.createElement('div');el.className=`replay-piece ${u.faction.toLowerCase()} ${u.destroyed?'destroyed':''} ${u.inactive?'inactive':''}`;el.style.left=`${u.x}%`;el.style.top=`${u.y}%`;el.style.transform=`translate(-50%,-50%) rotate(${Number(u.facing||0)}deg)`;el.style.setProperty('--counter-rotation',`${-Number(u.facing||0)}deg`);el.innerHTML=`<span class="facing-arrow">▲</span><span class="piece-label">${safe(u.name.slice(0,12))}</span>`;el.title=`${u.name} — facing ${Number(u.facing||0).toFixed(0)}°${u.destroyed?' — destroyed':''}`;host.appendChild(el);}for(const c of snap.commanders){const el=document.createElement('div');el.className=`replay-commander ${c.faction.toLowerCase()}`;el.style.left=`${c.x}%`;el.style.top=`${c.y}%`;el.textContent='★';el.title=c.name;host.appendChild(el);}label.textContent=eventText(snap.event);$('#replayCounter').textContent=`${replayIndex}/${currentRun.snapshots.length-1}`;drawHeat();}
  function drawHeat(){const canvas=$('#playHeatCanvas');if(!canvas)return;const frame=$('#playReplayFrame'),rect=frame.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));canvas.style.width=`${rect.width}px`;canvas.style.height=`${rect.height}px`;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,rect.width,rect.height);if(!currentRun||heatType==='none')return;const points=currentRun.heat?.[heatType]||[],cols=18,rows=18,grid=Array.from({length:rows},()=>Array(cols).fill(0)),w=Number(state.project.playSpace?.width||48),h=Number(state.project.playSpace?.height||48);for(const p of points){const x=Math.max(0,Math.min(cols-1,Math.floor(p.x/w*cols))),y=Math.max(0,Math.min(rows-1,Math.floor(p.y/h*rows)));grid[y][x]++;}const max=Math.max(1,...grid.flat());for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const v=grid[y][x]/max;if(!v)continue;ctx.fillStyle=`rgba(255,45,38,${0.10+v*.58})`;ctx.fillRect(x*rect.width/cols,y*rect.height/rows,rect.width/cols+1,rect.height/rows+1);}}
  function renderLog(){const host=$('#playEventLog');if(!currentRun){host.innerHTML='<p class="muted">No run selected.</p>';return;}host.innerHTML=currentRun.events.slice(0,250).map(ev=>`<button class="event-row" data-event-index="${ev.i}"><span>${ev.i}</span><strong>${safe(ev.type.replaceAll('_',' '))}</strong><small>${safe(eventText(ev))}</small></button>`).join('');host.querySelectorAll('[data-event-index]').forEach(b=>b.addEventListener('click',()=>{const idx=Number(b.dataset.eventIndex),snapIndex=currentRun.snapshots.findIndex(s=>s.event?.i===idx);if(snapIndex>=0){replayIndex=snapIndex;renderReplay();}}));}
  function single(){const w=readiness();if(w.some(x=>/No deployed French|No deployed Imperial|No deployed units/.test(x)))return;currentRun=runPlaytest(state,settings());currentBatch=null;replayIndex=0;resultCards(currentRun);batchCards(null);renderReplay();renderLog();$('#playRunStatus').textContent=`Seed ${currentRun.seed} complete`;}
  function batch(){const w=readiness();if(w.some(x=>/No deployed French|No deployed Imperial|No deployed units/.test(x)))return;$('#playRunStatus').textContent='Running batch…';setTimeout(()=>{currentBatch=runBatch(state,settings());currentRun=currentBatch.results[0]||null;replayIndex=0;batchCards(currentBatch);resultCards(currentRun);renderReplay();renderLog();$('#playRunStatus').textContent=`${currentBatch.runs} runs complete`;},20);}
  $('#runSinglePlaytest')?.addEventListener('click',single);$('#runBatchPlaytest')?.addEventListener('click',batch);$('#replaySlider')?.addEventListener('input',e=>{replayIndex=Number(e.target.value);renderReplay();});$('#replayPrev')?.addEventListener('click',()=>{replayIndex--;renderReplay();});$('#replayNext')?.addEventListener('click',()=>{replayIndex++;renderReplay();});document.querySelectorAll('[data-heat]').forEach(b=>b.addEventListener('click',()=>{heatType=b.dataset.heat;document.querySelectorAll('[data-heat]').forEach(x=>x.classList.toggle('active',x===b));drawHeat();}));['playSeed','playTurns','playRuns','playScale','playGarrisonTurn'].forEach(id=>$(`#${id}`)?.addEventListener('change',readiness));window.addEventListener('resize',()=>{if(document.querySelector('[data-view="playtest"]')?.classList.contains('active'))drawHeat();});document.querySelector('[data-view="playtest"]')?.addEventListener('click',()=>setTimeout(()=>{readiness();renderReplay();},0));
  readiness();resultCards(null);batchCards(null);renderReplay();renderLog();return{readiness,runSingle:single,runBatch:batch};
}
