export const PLAYTEST_ENGINE_690_PATCH_VERSION='0.6.9.1';

function replaceRequired(source,needle,replacement,label){
  if(!source.includes(needle))throw new Error(`Battle Axe v0.6.9.1 engine patch could not find ${label}; refusing to run against an unexpected baseline.`);
  return source.replace(needle,replacement);
}

export function absolutizeEngineImports690(source,baseUrl){
  if(!baseUrl)return source;
  return source.replace(/(from\s+['"])(\.\.?\/[^'"]+)(['"])/g,(_m,a,spec,b)=>`${a}${new URL(spec,baseUrl).href}${b}`);
}

const HELPERS_690=String.raw`
function normSemantic690(s){return String(s||'').toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').trim();}
function textHasPhrase690(text,phrase){const t=normSemantic690(text),p=normSemantic690(phrase);return !!p&&p.length>=3&&new RegExp('\\b'+p.replace(/ /g,'\\s+')+'\\b').test(t);}
function mentionedSide690(text,runtime,ownSide=null){const t=normSemantic690(text),pairs=[];for(const side of ['sideA','sideB']){const label=runtime?.sideLabels?.[side]||side;pairs.push([side,label]);}pairs.push(['sideA','sideA'],['sideB','sideB']);if(runtime?.rules?.supplement?.id==='american-civil-war'||runtime?.rules?.capabilities?.acwCommanderCompetency){pairs.push(['sideA','Union'],['sideA','Federal'],['sideB','Confederate'],['sideB','Confederates'],['sideB','Rebel'],['sideB','Rebels']);}for(const [side,label] of pairs)if(textHasPhrase690(t,label))return side;if(/\b(enemy|opposing|opponent)\b/.test(t)&&ownSide)return ownSide==='sideA'?'sideB':'sideA';if(/\b(friendly|our|own)\b/.test(t)&&ownSide)return ownSide;return null;}
function commandAliases690(c){return[c?.name,c?.commander,c?.commanderName,c?.historicalCommander,c?.scenarioCommanderOverride].filter(Boolean);}
function mentionedCommands690(text,scenario){const hits=[];for(const cmds of Object.values(scenario?.commands||{}))for(const c of cmds||[])if(commandAliases690(c).some(a=>textHasPhrase690(text,a)))hits.push(c);return hits.sort((a,b)=>Math.max(...commandAliases690(b).map(x=>normSemantic690(x).length),0)-Math.max(...commandAliases690(a).map(x=>normSemantic690(x).length),0));}
function mentionedCommand690(text,scenario){return mentionedCommands690(text,scenario)[0]||null;}
function enrichSemanticModifiers690(mods,runtime,scenario,ownSide,command){const out={...mods},raw=String(out.raw||''),t=normSemantic690(raw),conditional=/\b(until|when|after|once|unless|only if|not until)\b/.test(t),sideMention=mentionedSide690(raw,runtime,ownSide),named=mentionedCommands690(raw,scenario).find(c=>c.id!==command?.id&&(!sideMention||coalition(c.faction)===sideMention))||null;let region=null;if(/\bleft flank\b/.test(t))region='left';else if(/\bright flank\b/.test(t))region='right';else if(/\b(?:the )?flank\b/.test(t)||/\bflanking\b/.test(t))region='nearest';if(region){const side=named?coalition(named.faction):sideMention||(ownSide==='sideA'?'sideB':'sideA');out.targetRegion=region;out.targetCommandId=named?.id||null;out.targetSide=side;out.semantic690=true;out.screenFlank=true;}
  if(conditional&&/\b(reach|reaches|reached|cross|crosses|crossed|enter|enters|entered|occupy|occupies|occupied)\b/.test(t)){const matches=(runtime?.terrain||[]).filter(z=>z?.name&&textHasPhrase690(raw,z.name)).sort((a,b)=>normSemantic690(b.name).length-normSemantic690(a.name).length);if(matches.length){const bestName=normSemantic690(matches[0].name),selected=matches.filter(z=>normSemantic690(z.name)===bestName),z=selected[0],triggerSide=named?coalition(named.faction):sideMention||(ownSide==='sideA'?'sideB':'sideA');out.releaseTerrainIds=selected.map(x=>x.id);out.releaseTerrainId=z.id;out.releaseTerrainName=z.name||z.id;out.releaseTerrainSide=triggerSide;out.releaseTerrainCommandId=named?.id||null;out.conditionalAdvance=true;out.unparsedConditional=false;out.semantic690=true;}}
  const thenMatch=/\bthen\s+(withdraw|fall back|retire|assault|charge|attack|advance|move forward|press forward|maneuver|manoeuvre|flank|envelop|defend|hold)\b/.exec(t);if(conditional&&thenMatch){out.postReleaseOrder=/withdraw|fall back|retire/.test(thenMatch[1])?'Withdraw':/assault|charge|attack/.test(thenMatch[1])?'Assault':/advance|move forward|press forward/.test(thenMatch[1])?'Advance':/maneuver|manoeuvre|flank|envelop/.test(thenMatch[1])?'Maneuver':'Defend';out.semantic690=true;}
  return out;}
function groupMembers690(group,ctx){if(!group)return[];if(group.commandId)return ctx.units.filter(x=>!x.destroyed&&!x.inactive&&(x.commandId===group.commandId||commandHasAuthority(group.commandId,x.commandId,ctx.commandParentById)));return ctx.units.filter(x=>!x.destroyed&&!x.inactive&&coalition(x.faction)===group.side);}
function semanticTargetGroup690(u,ctx,mods={}){const targetSide=mods.targetSide||(coalition(u.faction)==='sideA'?'sideB':'sideA');if(mods.targetCommandId){const members=ctx.units.filter(x=>!x.destroyed&&!x.inactive&&(x.commandId===mods.targetCommandId||commandHasAuthority(mods.targetCommandId,x.commandId,ctx.commandParentById)));if(members.length)return{commandId:mods.targetCommandId,side:targetSide,label:ctx.commandConfigById?.[mods.targetCommandId]?.name||mods.targetCommandId,members};}const members=ctx.units.filter(x=>!x.destroyed&&!x.inactive&&coalition(x.faction)===targetSide);return members.length?{commandId:null,side:targetSide,label:ctx.sideLabels?.[targetSide]||targetSide,members}:null;}
function formationFrame690(group,ctx){const members=group?.members?.length?group.members:groupMembers690(group,ctx);if(!members.length)return null;const center={x:members.reduce((a,m)=>a+m.x,0)/members.length,y:members.reduce((a,m)=>a+m.y,0)/members.length};let sx=0,sy=0;for(const m of members){const f=forwardVec(m.facing??0);sx+=f.x;sy+=f.y;}let facing;if(Math.hypot(sx,sy)<Math.max(.15,members.length*.08))facing=members[0]?.facing??0;else facing=normDeg(Math.atan2(sx,-sy)*180/Math.PI);return{center,facing,forward:forwardVec(facing),right:rightVec(facing),members};}
function formationFlankAnchor690(group,region,ctx){const frame=formationFrame690(group,ctx);if(!frame)return null;const {center,right,forward,members}=frame;const projected=members.map(m=>{const dx=m.x-center.x,dy=m.y-center.y,p=dx*right.x+dy*right.y,e=baseFrontage(m)/2;return{m,left:p-e,right:p+e};});let side=region;if(side==='nearest'){const own=ctx.__semanticRequester690||center,left=Math.min(...projected.map(x=>x.left)),rightEdge=Math.max(...projected.map(x=>x.right)),lp={x:center.x+right.x*left,y:center.y+right.y*left},rp={x:center.x+right.x*rightEdge,y:center.y+right.y*rightEdge};side=dist(own,lp)<=dist(own,rp)?'left':'right';}const edge=side==='right'?Math.max(...projected.map(x=>x.right)):Math.min(...projected.map(x=>x.left)),edgePoint={x:center.x+right.x*edge,y:center.y+right.y*edge},outward=side==='right'?right:{x:-right.x,y:-right.y},standoff=Math.max(1.5*ctx.scale,.75),rearBias=standoff*.35;return{x:clamp(edgePoint.x+outward.x*standoff-forward.x*rearBias,0,ctx.width),y:clamp(edgePoint.y+outward.y*standoff-forward.y*rearBias,0,ctx.height),side,frame,edgePoint};}
function semanticFlankFormationTarget690(u,ctx,mods={}){if(!mods.targetRegion)return null;const group=semanticTargetGroup690(u,ctx,mods);if(!group)return null;ctx.__semanticRequester690={x:u.x,y:u.y};const flank=formationFlankAnchor690(group,mods.targetRegion,ctx);ctx.__semanticRequester690=null;if(!flank)return null;const own=ctx.units.filter(x=>!x.destroyed&&!x.inactive&&x.commandId===u.commandId&&['infantry','ranged'].includes(unitRole(x))),wave=Number(u.maneuverWave||1),waveMembers=(own.length?own:[u]).filter(x=>Number(x.maneuverWave||1)===wave).sort((a,b)=>String(a.id).localeCompare(String(b.id))),index=Math.max(0,waveMembers.findIndex(x=>x.id===u.id)),ownCenter=own.length?{x:own.reduce((a,f)=>a+f.x,0)/own.length,y:own.reduce((a,f)=>a+f.y,0)/own.length}:{x:u.x,y:u.y},dx=flank.x-ownCenter.x,dy=flank.y-ownCenter.y,l=Math.hypot(dx,dy)||1,fx=dx/l,fy=dy/l,px=-fy,py=fx,spacing=Math.max(baseFrontage(u)*1.08,.6*ctx.scale),lateral=(index-(waveMembers.length-1)/2)*spacing,lineGap=Math.max(1.15*ctx.scale,baseDepthSize(u)*1.05),waveDepth=(wave-1)*Math.max(1.25*ctx.scale,baseDepthSize(u)*1.45),anchor={x:flank.x-fx*(lineGap+waveDepth),y:flank.y-fy*(lineGap+waveDepth)},reference=flank.frame.members.sort((a,b)=>dist(a,flank.edgePoint)-dist(b,flank.edgePoint))[0]||null;return{target:{x:clamp(anchor.x+px*lateral,0,ctx.width),y:clamp(anchor.y+py*lateral,0,ctx.height)},reference,group,flank,wave,index};}
function actorOnRequestedFlank690(actor,group,region,ctx){if(!actor||!group||!region)return false;ctx.__semanticRequester690={x:actor.x,y:actor.y};const flank=formationFlankAnchor690(group,region,ctx);ctx.__semanticRequester690=null;if(!flank)return false;const frame=flank.frame,dx=actor.x-frame.center.x,dy=actor.y-frame.center.y,lateral=dx*frame.right.x+dy*frame.right.y,edgeProj=(flank.edgePoint.x-frame.center.x)*frame.right.x+(flank.edgePoint.y-frame.center.y)*frame.right.y,slack=Math.max(2*ctx.scale,baseFrontage(actor)*1.5);return flank.side==='left'?lateral<=edgeProj+slack:lateral>=edgeProj-slack;}
function terrainReleaseState690(commandId,ownSide,ctx,mods={}){const ids=(mods.releaseTerrainIds?.length?mods.releaseTerrainIds:[mods.releaseTerrainId]).filter(Boolean);if(!ids.length)return{satisfied:false};const features=(ctx.terrain||[]).filter(z=>ids.includes(z.id));if(!features.length)return{satisfied:false,reason:'named terrain feature is no longer present'};const targetSide=mods.releaseTerrainSide||(ownSide==='sideA'?'sideB':'sideA'),actors=ctx.units.filter(x=>!x.destroyed&&!x.inactive&&coalition(x.faction)===targetSide&&(!mods.releaseTerrainCommandId||(x.commandId===mods.releaseTerrainCommandId||commandHasAuthority(mods.releaseTerrainCommandId,x.commandId,ctx.commandParentById))));for(const feature of features){const actor=actors.find(x=>baseOverlapsTerrainZone(x,feature,x.x,x.y,x.facing??0)||terrainContains(feature,x.x,x.y));if(actor)return{satisfied:true,actor,feature,features,reason:String(actor.name||actor.id)+' reached '+String(feature.name||feature.id)};}return{satisfied:false,feature:features[0],features};}
function geographicFormationTarget690(u,ctx,mods={}){const region=mods.targetGeographicRegion;if(!region)return null;const group=semanticTargetGroup690(u,ctx,mods);if(!group?.members?.length)return null;const members=group.members,center={x:members.reduce((a,m)=>a+m.x,0)/members.length,y:members.reduce((a,m)=>a+m.y,0)/members.length},edge=members.slice().sort((a,b)=>region==='south'?b.y-a.y:region==='north'?a.y-b.y:region==='east'?b.x-a.x:a.x-b.x)[0],outward=region==='south'?{x:0,y:1}:region==='north'?{x:0,y:-1}:region==='east'?{x:1,y:0}:{x:-1,y:0},standoff=Math.max(1.5*ctx.scale,baseFrontage(u)),own=ctx.units.filter(x=>!x.destroyed&&!x.inactive&&x.commandId===u.commandId),index=Math.max(0,own.slice().sort((a,b)=>String(a.id).localeCompare(String(b.id))).findIndex(x=>x.id===u.id)),lateral=(index-(own.length-1)/2)*Math.max(baseFrontage(u)*1.08,.6*ctx.scale),perp={x:-outward.y,y:outward.x};return{target:{x:clamp(edge.x+outward.x*standoff+perp.x*lateral,0,ctx.width),y:clamp(edge.y+outward.y*standoff+perp.y*lateral,0,ctx.height)},reference:edge,group,region,center};}
function evaluateCondition690(condition,u,ctx){if(!condition)return{satisfied:false};if(condition.op){const rows=(condition.conditions||[]).map(c=>evaluateCondition690(c,u,ctx));if(condition.op==='ANY'){const hit=rows.find(x=>x.satisfied);return hit||{satisfied:false};}if(condition.op==='ALL')return rows.length&&rows.every(x=>x.satisfied)?{satisfied:true,reason:rows.map(x=>x.reason).filter(Boolean).join(' AND '),conditions:rows}:{satisfied:false};if(condition.op==='NOT')return{satisfied:!rows[0]?.satisfied,reason:!rows[0]?.satisfied?'negated condition satisfied':null};return{satisfied:false};}
  if(condition.type==='turn_reached'){const ok=Number(ctx.turn||0)>=Number(condition.turn||Infinity);return{satisfied:ok,reason:ok?'Turn '+condition.turn+' backstop reached':null,predicate:condition};}
  if(condition.type==='unit_destroyed'){const matches=(ctx.units||[]).filter(x=>x.destroyed&&(!condition.side||coalition(x.faction)===condition.side)&&(!condition.commandId||(x.commandId===condition.commandId||commandHasAuthority(condition.commandId,x.commandId,ctx.commandParentById)))&&(!condition.role||unitRole(x)===condition.role||(condition.role==='artillery'&&/artillery|cannon|battery/i.test(String(x.profile||x.name||'')))));const ok=matches.length>=Number(condition.quantity||1),actor=matches[0];return{satisfied:ok,reason:ok?String(actor?.name||condition.role||'qualifying unit')+' destroyed':null,actor,predicate:condition};}
  if(condition.type==='terrain_occupied'){const terrain=terrainReleaseState690(u.commandId,coalition(u.faction),ctx,{releaseTerrainIds:condition.terrainIds,releaseTerrainName:condition.terrainName,releaseTerrainSide:condition.side,releaseTerrainCommandId:condition.commandId});return{...terrain,predicate:condition};}
  if(condition.type==='line_breached'){const line=friendlyDefensiveLineState(u,ctx);return{satisfied:line.breached,reason:line.breached?'defensive line breached':null,predicate:condition};}
  if(condition.type==='line_abandoned'){const line=friendlyDefensiveLineState(u,ctx);return{satisfied:line.left,reason:line.left?'defensive line abandoned':null,predicate:condition};}
  if(condition.type==='enemy_vulnerable'){const ok=enemyVulnerable(u,ctx);return{satisfied:ok,reason:ok?'enemy vulnerable':null,predicate:condition};}
  return{satisfied:false};}
`;

export function applyPlaytestEngine690Patch(source,{baseUrl=null}={}){
  let s=String(source||'');
  if(!s.includes("import { getEffectiveRuleset }"))throw new Error('Battle Axe v0.6.9.1 engine patch expected the v0.6.8.1 playtest engine source.');

  const mergeNeedle="function mergeModifiers(a,b){return{raw:[a?.raw,b?.raw].filter(Boolean).join(' / '),preservePosition:Math.max(a?.preservePosition||0,b?.preservePosition||0),preferShoot:Math.max(a?.preferShoot||0,b?.preferShoot||0),counterattack:!!(a?.counterattack||b?.counterattack),noPursuit:!!(a?.noPursuit||b?.noPursuit),aggression:(a?.aggression||0)+(b?.aggression||0),preservation:Math.max(a?.preservation||0,b?.preservation||0),holdUntilEnemyClose:!!(a?.holdUntilEnemyClose||b?.holdUntilEnemyClose),screenFlank:!!(a?.screenFlank||b?.screenFlank),releaseOnLineBreached:!!(a?.releaseOnLineBreached||b?.releaseOnLineBreached),releaseOnFriendlyLineLeaves:!!(a?.releaseOnFriendlyLineLeaves||b?.releaseOnFriendlyLineLeaves),releaseOnEnemyVulnerable:!!(a?.releaseOnEnemyVulnerable||b?.releaseOnEnemyVulnerable),conditionalAdvance:!!(a?.conditionalAdvance||b?.conditionalAdvance),unparsedConditional:!!(a?.unparsedConditional||b?.unparsedConditional),summary:[...(a?.summary||[]),...(b?.summary||[])]};}";
  s=replaceRequired(s,mergeNeedle,mergeNeedle+HELPERS_690,'tactical modifier merge hook');

  s=replaceRequired(s,
    "modifiers=mergeModifiers(armies[side].modifiers,interpretOrderText(ov.text||''));commands[c.id]=",
    "modifiers=enrichSemanticModifiers690(mergeModifiers(armies[side].modifiers,interpretOrderText(ov.text||'')),runtime,scenario,side,c);const intentContext={scope:'command',commandId:c.id,ownSide:side,sideLabels:runtime.sideLabels||{},supplementId:runtime.rules?.supplement?.id||scenario.ruleset?.supplement||'',commands:Object.entries(scenario.commands||{}).flatMap(([f,rows])=>(rows||[]).map(x=>({id:x.id,name:x.name,commander:x.commander||'',commanderName:x.commanderName||'',historicalCommander:x.historicalCommander||'',scenarioCommanderOverride:x.scenarioCommanderOverride||'',side:coalition(f)}))),terrain:(runtime.terrain||[]).map(z=>({id:z.id,name:z.name}))};const tacticalIntent=ov.tacticalIntent&&typeof ov.tacticalIntent==='object'?structuredClone(ov.tacticalIntent):compileTacticalIntent(ov.text||'',intentContext);if(tacticalIntent.status!=='blocked')Object.assign(modifiers,intentToLegacyModifiers(tacticalIntent));else{modifiers=mergeModifiers(armies[side].modifiers,{});modifiers.unparsedConditional=true;modifiers.preservePosition=Math.max(1,modifiers.preservePosition||0);}commands[c.id]=",
    'command semantic-intent enrichment hook');

  s=replaceRequired(s,
    "commands[c.id]={commandId:c.id,name:c.name,commander:c.commander||'',side,order,autoOrder,text:ov.text||'',modifiers,",
    "commands[c.id]={commandId:c.id,name:c.name,commander:c.commander||'',side,order,autoOrder,text:ov.text||'',tacticalIntent,modifiers,",
    'canonical TacticalIntent runtime storage');

  s=replaceRequired(s,
    "function orderFor(u,ctx){return ctx.tacticalPlan?.commands?.[u.commandId]||{order:'Advance',autoOrder:'Advance',side:coalition(u.faction),modifiers:interpretOrderText('')};}",
    "function orderFor(u,ctx){const base=ctx.tacticalPlan?.commands?.[u.commandId]||{order:'Advance',autoOrder:'Advance',side:coalition(u.faction),modifiers:interpretOrderText('')};if(ctx.commandRelease?.[u.commandId]&&base.modifiers?.postReleaseOrder)return{...base,order:base.modifiers.postReleaseOrder,semanticPostRelease:true};return base;}",
    'post-release order transition');

  const movementHead="function movementIntent(u,ctx){const plan=orderFor(u,ctx),order=plan.order||'Advance',enemy=nearestVisibleEnemyActor(u,ctx)||nearestEnemy(u,ctx.units),doctrine=supplement(ctx).aiDoctrine||{},role=unitRole(u);";
  const movementSemantic=movementHead+"if(enemy&&plan.modifiers?.targetGeographicRegion&&['Advance','Assault','Maneuver'].includes(order)){const geographic=geographicFormationTarget690(u,ctx,plan.modifiers||{});if(geographic)return{target:geographic.target,mode:'flank',reference:geographic.reference||enemy,semanticFlank:geographic.region,semanticTarget:geographic.group?.label||geographic.group?.side,semanticGeographic:true};}if(enemy&&plan.modifiers?.targetRegion&&['Advance','Assault','Maneuver'].includes(order)){const semantic=semanticFlankFormationTarget690(u,ctx,plan.modifiers||{});if(semantic){const onFlank=actorOnRequestedFlank690(u,semantic.group,plan.modifiers.targetRegion,ctx);if(!onFlank)return{target:semantic.target,mode:'flank',reference:semantic.reference||enemy,semanticFlank:semantic.flank?.side||plan.modifiers.targetRegion,semanticTarget:semantic.group?.label||semantic.group?.commandId||semantic.group?.side};const target=(semantic.group.members||[]).filter(x=>!x.destroyed&&!x.inactive).sort((a,b)=>baseGapDistance(u,a)-baseGapDistance(u,b))[0]||semantic.reference||enemy;return{target,mode:'advance',reference:target,semanticFlank:semantic.flank?.side||plan.modifiers.targetRegion,semanticTarget:semantic.group?.label||semantic.group?.commandId||semantic.group?.side,semanticFlankReached:true};}}";
  s=replaceRequired(s,movementHead,movementSemantic,'formation-relative flank movement intent');

  s=replaceRequired(s,
    "if(intent?.target)actions.push({type:'move',target:intent.target,reference:intent.reference||null,moveMode:intent.mode,distance:intent.reference?baseGapDistance(u,intent.reference):dist(u,intent.target)});",
    "if(intent?.target)actions.push({type:'move',target:intent.target,reference:intent.reference||null,moveMode:intent.mode,semanticFlank:intent.semanticFlank||null,semanticTarget:intent.semanticTarget||null,semanticFlankReached:!!intent.semanticFlankReached,distance:intent.reference?baseGapDistance(u,intent.reference):dist(u,intent.target)});",
    'semantic movement metadata');

  const oldManeuver="if(order==='Maneuver'&&enemy){const dx=enemy.x-u.x,dy=enemy.y-u.y,l=Math.hypot(dx,dy)||1,px=-dy/l,py=dx/l,roomA=Math.min(ctx.width-u.x,ctx.height-u.y),roomB=Math.min(u.x,u.y),sign=roomA>=roomB?1:-1,offset=Math.max(2*ctx.scale,u.move*ctx.scale);return{target:{x:clamp(enemy.x+px*offset*sign,0,ctx.width),y:clamp(enemy.y+py*offset*sign,0,ctx.height)},mode:'flank',reference:enemy};}";
  const newManeuver=oldManeuver;
  s=replaceRequired(s,oldManeuver,newManeuver,'Maneuver flank-target hook');

  const oldRelease="function releaseByIntent(u,ctx,mods){ctx.commandRelease=ctx.commandRelease||{};if(ctx.commandRelease[u.commandId])return true;const line=friendlyDefensiveLineState(u,ctx),released=(mods.releaseOnLineBreached&&line.breached)||(mods.releaseOnFriendlyLineLeaves&&line.left)||(mods.releaseOnEnemyVulnerable&&enemyVulnerable(u,ctx));if(released)ctx.commandRelease[u.commandId]={turn:ctx.turn||0,reason:mods.releaseOnLineBreached&&line.breached?'defensive line breached':mods.releaseOnFriendlyLineLeaves&&line.left?'defensive line abandoned':'enemy vulnerable'};return !!released;}";
  const newRelease="function releaseByIntent(u,ctx,mods){ctx.commandRelease=ctx.commandRelease||{};if(ctx.commandRelease[u.commandId])return true;const line=friendlyDefensiveLineState(u,ctx),terrain=terrainReleaseState690(u.commandId,coalition(u.faction),ctx,mods),canonical=evaluateCondition690(mods.releaseCondition,u,ctx),released=canonical.satisfied||(mods.releaseOnLineBreached&&line.breached)||(mods.releaseOnFriendlyLineLeaves&&line.left)||(mods.releaseOnEnemyVulnerable&&enemyVulnerable(u,ctx))||terrain.satisfied;if(released){const reason=canonical.satisfied?canonical.reason:mods.releaseOnLineBreached&&line.breached?'defensive line breached':mods.releaseOnFriendlyLineLeaves&&line.left?'defensive line abandoned':mods.releaseOnEnemyVulnerable&&enemyVulnerable(u,ctx)?'enemy vulnerable':terrain.reason||`named terrain trigger ${mods.releaseTerrainName||mods.releaseTerrainId}`;const feature=canonical.feature||terrain.feature,actor=canonical.actor||terrain.actor;ctx.commandRelease[u.commandId]={turn:ctx.turn||0,reason,latched:true,triggerFeatureId:feature?.id||null,triggerFeatureName:feature?.name||null,triggerActorId:actor?.id||null,triggerActorName:actor?.name||null,predicate:canonical.predicate||null};ctx.event?.('reserve_released',u,{commandId:u.commandId,reason,triggerFeatureId:feature?.id||null,triggerFeatureName:feature?.name||null,triggerActorId:actor?.id||null,triggerActorName:actor?.name||null,predicate:canonical.predicate||null});}return !!released;}";
  s=replaceRequired(s,oldRelease,newRelease,'reserve release predicate');

  s=replaceRequired(s,
    "const explicit=mods.releaseOnLineBreached||mods.releaseOnFriendlyLineLeaves||mods.releaseOnEnemyVulnerable;if(explicit)return releaseByIntent(u,ctx,mods);",
    "const explicit=!!mods.releaseCondition||mods.releaseOnLineBreached||mods.releaseOnFriendlyLineLeaves||mods.releaseOnEnemyVulnerable||!!mods.releaseTerrainId;if(explicit)return releaseByIntent(u,ctx,mods);",
    'reserve explicit-trigger detection');

  s=replaceRequired(s,
    "const hasExplicitRelease=mods.releaseOnLineBreached||mods.releaseOnFriendlyLineLeaves||mods.releaseOnEnemyVulnerable,released=reserveReleased(u,ctx,mods,threat);",
    "const hasExplicitRelease=!!mods.releaseCondition||mods.releaseOnLineBreached||mods.releaseOnFriendlyLineLeaves||mods.releaseOnEnemyVulnerable||!!mods.releaseTerrainId,released=reserveReleased(u,ctx,mods,threat);",
    'reserve scoring trigger detection');

  const scoreNeedle="if(order==='Maneuver'&&action.type==='move'&&action.moveMode==='flank'){score+=18;reasons.push('maneuver order seeks a flank approach rather than a direct advance');}";
  const scoreExtra=scoreNeedle+"if(mods.targetRegion){const group=semanticTargetGroup690(u,ctx,mods);if(action.type==='move'&&action.moveMode==='flank'){score+=58;reasons.push(`written tactical plan anchors the command on the ${mods.targetRegion} flank of ${group?.label||ctx.sideLabels?.[mods.targetSide]||'the target formation'}`);}if(group&&action.type==='move'&&action.semanticFlankReached){score+=32;reasons.push('command has reached the requested flank and continues against the designated formation');}if(group&&action.type.startsWith('charge')&&action.target){const targetIsRelevant=group.commandId?(action.target.commandId===group.commandId||commandHasAuthority(group.commandId,action.target.commandId,ctx.commandParentById)):coalition(action.target.faction)===group.side;if(!targetIsRelevant){score-=95;reasons.push('charge would abandon the written target formation');}else if(actorOnRequestedFlank690(u,group,mods.targetRegion,ctx)){score+=58;reasons.push('charge is launched from the requested formation flank');}else{score-=92;reasons.push('written flank mission requires maneuvering onto the requested flank before a frontal charge');}}}";
  s=replaceRequired(s,scoreNeedle,scoreExtra,'semantic flank action scoring');

  const reserveLoop="for(const config of Object.values(ctx.commandConfigById||{}).filter(c=>c.faction===side&&c.reserve?.enabled&&Number(c.reserve.deploymentTurn||1)<=ctx.turn)){";
  s=replaceRequired(s,reserveLoop,"for(const config of Object.values(ctx.commandConfigById||{}).filter(c=>c.faction===side&&c.reserve?.enabled)){",'off-table reserve loop');
  const pendingNeedle="const pendingUnits=ctx.units.filter(u=>u.commandId===config.id&&u.reserveOffTable&&!u.destroyed),offTableCommander=ctx.commanders.find(c=>c.commandId===config.id&&c.reserveOffTable&&!c.destroyed),activeCommander=ctx.commanders.find(c=>c.commandId===config.id&&!c.reserveOffTable&&!c.inactive&&!c.destroyed);if(!pendingUnits.length&&!offTableCommander)continue;";
  const pendingReplacement=pendingNeedle+"const reservePlan=ctx.tacticalPlan?.commands?.[config.id]||{},reserveMods=reservePlan.modifiers||{},explicitReserveTrigger=!!reserveMods.releaseCondition||reserveMods.releaseOnLineBreached||reserveMods.releaseOnFriendlyLineLeaves||reserveMods.releaseOnEnemyVulnerable||!!reserveMods.releaseTerrainId;if(Number(config.reserve.deploymentTurn||1)>ctx.turn)continue;if(explicitReserveTrigger){const representative=pendingUnits[0]||offTableCommander;if(!representative||!reserveReleased(representative,ctx,reserveMods,Infinity)){if(representative)ctx.event('reserve_held',representative,{commandId:config.id,commandName:config.name,reason:reserveMods.releaseTerrainId?`waiting for ${reserveMods.releaseTerrainName||reserveMods.releaseTerrainId}`:'explicit tactical-plan release condition not yet satisfied'});continue;}}";
  s=replaceRequired(s,pendingNeedle,pendingReplacement,'off-table reserve semantic trigger hook');

  s=replaceRequired(s,
    "commanderHasAuthority};",
    "commanderHasAuthority,enrichSemanticModifiers690,semanticTargetGroup690,formationFrame690,formationFlankAnchor690,semanticFlankFormationTarget690,geographicFormationTarget690,actorOnRequestedFlank690,terrainReleaseState690,evaluateCondition690};",
    'conformance export hook');

  return absolutizeEngineImports690(s,baseUrl);
}
