import { buildRuntimeFromStudio, toPctSnapshot, scenarioConfigFingerprint, interpretOrderText } from './playtestEngine.js?v=0.5.6.0';
import { syncBattlefieldImages } from './battlefieldState.js?v=0.5.6.0';
import { footprintPercent, applyBattlefieldAspect } from './battlefieldScale.js?v=0.5.6.0';
import { sideLabel } from './scenarioSides.js?v=0.5.6.0';
const $=s=>document.querySelector(s);
const safe=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ARMY_POSTURES=['Auto','Offensive','Balanced','Defensive','Delay'];
const COMMAND_ORDERS=['Auto','Hold','Defend','Advance','Assault','Reserve','Screen','Maneuver','Withdraw'];

export function setupPlaytestCenter(state,persist){
  let currentRun=null,currentBatch=null,replayIndex=0,heatType='movement',playTimer=null,preparedHash=null,logMode='battle';
  state.playtestWorkspace=state.playtestWorkspace||{armyOrders:{},commandOrders:{},cueLevel:'standard'};
  state.playtestWorkspace.armyOrders=state.playtestWorkspace.armyOrders||{};
  state.playtestWorkspace.commandOrders=state.playtestWorkspace.commandOrders||{};
  state.playtestWorkspace.cueLevel=state.playtestWorkspace.cueLevel||'standard';
  const scenario=()=>state.project.scenario;
  const footprint=mm=>footprintPercent(mm,state.project.playSpace||{});
  const syncAspect=()=>applyBattlefieldAspect($('#playReplayStage'),state.project.playSpace||{});
  let simulationWorker=null,workerRequest=0;
  function worker(){if(!simulationWorker)simulationWorker=new Worker(new URL('./playtestWorker.js?v=0.5.6.0',import.meta.url),{type:'module'});return simulationWorker;}
  function planSettings(){return{armyOrders:structuredClone(state.playtestWorkspace.armyOrders||{}),commandOrders:structuredClone(state.playtestWorkspace.commandOrders||{})};}
  const settings=()=>({seed:Number($('#playSeed')?.value||42),turns:Number($('#playTurns')?.value||scenario().metadata?.gameLength||6),runs:Number($('#playRuns')?.value||25),measurementScale:Number(scenario().tabletop?.measurementMultiplier||2),garrisonTurn:Number($('#playGarrisonTurn')?.value||2),tacticalPlan:planSettings()});
  const currentHash=()=>scenarioConfigFingerprint(state);const isStale=()=>preparedHash!==currentHash();
  function setRunBusy(busy,label=''){const a=$('#runSinglePlaytest'),b=$('#runBatchPlaytest'),r=$('#resetPlaytest');if(a)a.disabled=busy||isStale();if(b)b.disabled=busy||isStale();if(r)r.disabled=busy;if(label&&$('#playRunStatus'))$('#playRunStatus').textContent=label;}
  function simulate(kind,opts){return new Promise((resolve,reject)=>{const w=worker(),id=++workerRequest,onMessage=e=>{const m=e.data||{};if(m.id!==id)return;w.removeEventListener('message',onMessage);w.removeEventListener('error',onError);if(m.ok)resolve(m.result);else{const err=new Error(m.error?.message||'Simulation failed');err.code=m.error?.code;err.diagnostic=m.error?.diagnostic;reject(err);}},onError=e=>{w.removeEventListener('message',onMessage);w.removeEventListener('error',onError);reject(new Error(e.message||'Playtest worker failed'));};w.addEventListener('message',onMessage);w.addEventListener('error',onError);w.postMessage({id,kind,state,settings:opts});});}
  function simulationFailure(error){console.error(error);const d=error?.diagnostic;$('#playRunStatus').textContent=`Simulation halted safely: ${error?.message||error}${d?` · Turn ${d.turn||'?'} · ${d.side||'unknown'} · ${d.actorName||d.actor||'unknown actor'} · ${d.eventCount||0} events`:''}`;}
  function runtimeInfo(){return buildRuntimeFromStudio(state,settings());}
  function resetPlaytest(){stopPlayback();syncBattlefieldImages(state);syncAspect();preparedHash=currentHash();scenario().playtestPreparedHash=preparedHash;currentRun=null;currentBatch=null;replayIndex=0;$('#playTurns').value=Number(scenario().metadata?.gameLength||6);scenario().playtestSummary=null;scenario().playtestSingle=null;persist();resultCards(null);batchCards(null);renderReplay();renderLog();updateStale();readiness();renderTacticalPlan();$('#playRunStatus').textContent=`Reset to ${preparedHash} · ${$('#playTurns').value} turns`;}
  function updateStale(){const stale=isStale(),b=$('#playtestStaleBanner');if(stale&&(currentRun||currentBatch)){stopPlayback();currentRun=null;currentBatch=null;replayIndex=0;resultCards(null);batchCards(null);renderLog();}if(b)b.hidden=!stale;if($('#playtestStaleDetail'))$('#playtestStaleDetail').textContent=stale?`Current scenario ${currentHash()} differs from prepared ${preparedHash||'none'}. The old replay has been cleared from the current-scenario preview.`:`Prepared ${preparedHash}.`;$('#runSinglePlaytest').disabled=stale;$('#runBatchPlaytest').disabled=stale;syncBattlefieldImages(state);syncAspect();}
  function renderConfigSummary(){const s=scenario(),tt={unitBaseMm:50,commanderBaseMm:25,measurementMultiplier:2,...(s.tabletop||{})},ps=state.project.playSpace||{},el=$('#playtestConfigSummary');if(el)el.innerHTML=`<strong>${ps.width||'?'} × ${ps.height||'?'} ${ps.units||''}</strong> · ${tt.unitBaseMm} mm units · ${tt.commanderBaseMm} mm commanders · ${tt.measurementMultiplier}× rules measurements · ${s.metadata?.gameLength||'?'} turns · ${s.ruleset?.supplement||'supplement'}`;}
  function readiness(){syncBattlefieldImages(state);renderConfigSummary();const rt=runtimeInfo(),s=scenario(),allUnits=Object.values(s.commands||{}).flatMap(cs=>cs.flatMap(c=>c.units||[])),placed=Object.keys(s.deployment?.placements||{}).length,approved=(state.project.features||[]).filter(f=>state.decisions?.[f.id]?.status==='approved').length,w=[],a=sideLabel(s,'French'),b=sideLabel(s,'Imperial');if(!state.project.mapSource)w.push('No battlefield map is generated for the current scenario.');if(!allUnits.length)w.push('No Battle Axe units in the Scenario Builder.');if(!rt.units.length)w.push('No deployed units are available to the browser playtest adapter.');if(placed<allUnits.length)w.push(`${allUnits.length-placed} force-list unit(s) are not deployed and will be omitted.`);if(allUnits.length&&!rt.units.some(u=>u.faction==='French'))w.push(`No deployed ${a} units.`);if(allUnits.length&&!rt.units.some(u=>u.faction==='Imperial'||u.faction==='Garrison'))w.push(`No deployed ${b} units.`);if(!approved)w.push('No terrain features are approved; the run will treat the battlefield as open ground.');$('#playReadySummary').innerHTML=`<dl class="summary-dl"><div><dt>Configuration</dt><dd>${preparedHash||'Not reset'}</dd></div><div><dt>Scenario turns</dt><dd>${safe(s.metadata?.gameLength||'—')}</dd></div><div><dt>Playtest turns</dt><dd>${settings().turns}</dd></div><div><dt>Roster units</dt><dd>${allUnits.length}</dd></div><div><dt>Deployed units</dt><dd>${rt.units.length}</dd></div><div><dt>Approved terrain</dt><dd>${approved}</dd></div></dl>${w.length?`<div class="playtest-warnings"><strong>Warnings</strong><ul>${w.map(x=>`<li>${safe(x)}</li>`).join('')}</ul></div>`:'<p class="success">Current scenario has enough data for a browser playtest preview.</p>'}`;updateStale();return w;}

  function optionList(values,current){return values.map(v=>`<option value="${v}" ${v===current?'selected':''}>${v}</option>`).join('');}
  function interpretationHtml(text){const x=interpretOrderText(text);return x.summary.length?`<small class="order-interpretation">Interpreted: ${safe(x.summary.join('; '))}.</small>`:'<small class="order-interpretation muted">Optional free text modifies the selected/default order; unrecognized wording is ignored rather than guessed.</small>';}
  function renderTacticalPlan(){const host=$('#tacticalPlanEditor');if(!host)return;let effective;try{effective=runtimeInfo().tacticalPlan;}catch{effective={armies:{},commands:{}};}const s=scenario();host.innerHTML=['French','Imperial'].map(side=>{const ao=state.playtestWorkspace.armyOrders[side]||{posture:'Auto',text:''},ep=effective.armies?.[side]||{},commands=Object.entries(s.commands||{}).flatMap(([faction,cs])=>(faction==='French'&&side==='French')||(faction!=='French'&&side==='Imperial')?(cs||[]):[]);return `<section class="tactical-army"><header><div><strong>${safe(sideLabel(s,side))}</strong><span>Auto: ${safe(ep.autoPosture||'Balanced')}</span></div><label>Army posture<select data-army-posture="${side}">${optionList(ARMY_POSTURES,ao.posture||'Auto')}</select></label></header><label class="tactical-free-text">Optional army intent<input data-army-text="${side}" value="${safe(ao.text||'')}" placeholder="Example: preserve the prepared position and let the enemy come on"></label>${interpretationHtml(ao.text||'')}<div class="tactical-command-list">${commands.map(c=>{const co=state.playtestWorkspace.commandOrders[c.id]||{order:'Auto',text:''},resolved=effective.commands?.[c.id]||{};return `<div class="tactical-command"><div class="tactical-command-name"><strong>${safe(c.name)}</strong><span>${safe(c.commander||'Commander not assigned')} · Auto: ${safe(resolved.autoOrder||'Advance')}</span></div><select data-command-order="${c.id}" aria-label="${safe(c.name)} order">${optionList(COMMAND_ORDERS,co.order||'Auto')}</select><input data-command-text="${c.id}" value="${safe(co.text||'')}" placeholder="Optional additional intent"></div>${co.text?interpretationHtml(co.text):''}`;}).join('')}</div><details class="tactical-auto-reason"><summary>Why Auto chose these defaults</summary><p>${safe(ep.reason||'Auto evaluates deployment, terrain and force roles.')}</p></details></section>`;}).join('');
    host.querySelectorAll('[data-army-posture]').forEach(el=>el.addEventListener('change',()=>{const side=el.dataset.armyPosture,stateRow=state.playtestWorkspace.armyOrders[side]||{};state.playtestWorkspace.armyOrders[side]={...stateRow,posture:el.value};persist();renderTacticalPlan();$('#playRunStatus').textContent='Tactical plan updated · rerun to apply.';}));
    host.querySelectorAll('[data-army-text]').forEach(el=>el.addEventListener('change',()=>{const side=el.dataset.armyText,stateRow=state.playtestWorkspace.armyOrders[side]||{};state.playtestWorkspace.armyOrders[side]={...stateRow,text:el.value};persist();renderTacticalPlan();$('#playRunStatus').textContent='Tactical plan updated · rerun to apply.';}));
    host.querySelectorAll('[data-command-order]').forEach(el=>el.addEventListener('change',()=>{const id=el.dataset.commandOrder,row=state.playtestWorkspace.commandOrders[id]||{};state.playtestWorkspace.commandOrders[id]={...row,order:el.value};persist();renderTacticalPlan();$('#playRunStatus').textContent='Tactical plan updated · rerun to apply.';}));
    host.querySelectorAll('[data-command-text]').forEach(el=>el.addEventListener('change',()=>{const id=el.dataset.commandText,row=state.playtestWorkspace.commandOrders[id]||{};state.playtestWorkspace.commandOrders[id]={...row,text:el.value};persist();renderTacticalPlan();$('#playRunStatus').textContent='Tactical plan updated · rerun to apply.';}));
  }

  function resultCards(r){const a=sideLabel(scenario(),'French'),b=sideLabel(scenario(),'Imperial'),winner=r?.winner==='French'?a:r?.winner==='Imperial'?b:r?.winner;$('#playSingleResult').innerHTML=r?`<div class="result-card winner-${r.winner.toLowerCase()}"><span>Winner</span><strong>${safe(winner)}</strong></div><div class="result-card"><span>Turns</span><strong>${r.turnsCompleted}</strong></div><div class="result-card"><span>${safe(a)} VP</span><strong>${r.victoryPoints.French}</strong></div><div class="result-card"><span>${safe(b)} VP</span><strong>${r.victoryPoints.Imperial}</strong></div><div class="result-card"><span>Events</span><strong>${r.events.length}</strong></div>`:'<p class="muted">Run a deterministic game to see results.</p>';}
  function batchCards(b){const a=sideLabel(scenario(),'French'),c=sideLabel(scenario(),'Imperial');$('#playBatchResult').innerHTML=b?`<div class="balance-grid"><div><span>${safe(a)}</span><strong>${b.winPct.French.toFixed(1)}%</strong></div><div><span>${safe(c)}</span><strong>${b.winPct.Imperial.toFixed(1)}%</strong></div><div><span>Draw</span><strong>${b.winPct.Draw.toFixed(1)}%</strong></div><div><span>Avg turns</span><strong>${b.avgTurns.toFixed(1)}</strong></div><div><span>Avg ${safe(a)} VP</span><strong>${b.avgVp.French.toFixed(1)}</strong></div><div><span>Avg ${safe(c)} VP</span><strong>${b.avgVp.Imperial.toFixed(1)}</strong></div></div><p class="muted">${b.runs} current-configuration runs · ${preparedHash}</p>`:'<p class="muted">Run a batch to estimate balance.</p>';}
  function eventText(ev,debug=false){if(!ev)return'Setup';const p=ev.payload||{},t=`T${ev.turn}`;if(ev.type==='move')return`${t} ${ev.actorName} advanced ${Number(p.distance||0).toFixed(1)}"${p.terrain?.length?` through ${p.terrain.join(', ')}`:''}.`;if(ev.type==='pivot')return`${t} ${ev.actorName} pivoted ${Math.abs(Number(p.delta||0)).toFixed(0)}°.`;if(ev.type==='attack')return`${t} ${ev.actorName} → ${p.targetName||p.target}: ${p.hits} hit(s)${p.defensive?' · Defensive terrain (Armour 6)':''}${debug?` · rolls ${JSON.stringify(p.rolls)} vs ${p.armor}+`:''}.`;if(ev.type==='artillery')return`${t} ${ev.actorName} bombarded ${p.targetName||p.target}: roll ${p.roll}${p.defensive?' · target in Defensive terrain':''}.`;if(ev.type==='charge'||ev.type==='charge_contact')return`${t} ${ev.actorName} charged ${p.targetName||p.target}.`;if(ev.type==='unit_destroyed')return`${t} ${ev.actorName} BROKEN / destroyed.`;if(ev.type==='army_asset_destroyed')return`${t} ${p.targetName||p.target} destroyed by ${ev.actorName} · ${p.victoryPoints||4} VP.`;if(ev.type==='command_test')return`${t} ${ev.actorName} Command Test ${p.outcome}${debug?` (${p.roll} vs ${p.threshold}+)`:''}.`;if(ev.type==='ai_hold')return`${t} ${ev.actorName} held position · ${p.order||'tactical order'}${debug&&p.reason?` · ${p.reason}`:''}.`;if(ev.type==='ai_action_choice')return`${t} ${ev.actorName} AI chose ${p.action||'none'} under ${p.order||'Auto'}${debug?` · score ${p.score} · ${(p.reasons||[]).join('; ')}`:''}.`;if(ev.type==='commander_move')return`${t} ${ev.actorName} moved ${Number(p.distance||0).toFixed(1)}" to improve command coverage (${p.coveredBefore}→${p.coveredAfter}).`;if(ev.type==='commander_hold')return`${t} ${ev.actorName} held position · ${p.reason}.`;if(ev.type==='commander_command_test')return`${t} ${ev.actorName} escape Command Test ${p.outcome}${debug?` (${p.die} vs ${p.threshold}+)`:''}.`;if(ev.type==='commander_escape')return`${t} ${ev.actorName} escaped ${p.d3}" directly away from ${p.awayFromName||'the charger'}.`;if(ev.type==='commander_destroyed')return`${t} ${ev.actorName} CAPTURED / killed · ${p.victoryPoints} VP to the enemy.`;if(ev.type==='commander_charge_contact')return`${t} ${ev.actorName} contacted ${p.targetName||p.target} in a charge.`;if(ev.type==='reinforcement_activated')return`${t} ${ev.actorName} entered play.`;if(ev.type==='move_blocked')return`${t} ${ev.actorName} movement blocked: ${p.reason}.`;if(ev.type==='move_shortened')return`${t} ${ev.actorName} shortened movement to avoid overlap.`;return`${t} ${ev.actorName||''} ${ev.type.replaceAll('_',' ')}.`;}
  function commandColor(faction,id=''){const cmds=scenario().commands?.[faction]||[],i=Math.max(0,cmds.findIndex(c=>c.id===id)),palettes={French:['#164A7A','#2376BD','#49A0D8','#285A8F','#196F82','#5A57B5','#2E87A7'],Imperial:['#7E2727','#A93A32','#D45A4D','#8B405D','#B96A32','#C64468','#6D3947'],Garrison:['#6F5423','#9B782D','#C19A45','#80683D']},a=palettes[faction]||['#4d6380','#66809f','#384e68'];return a[i%a.length];}
  function deathVictim(ev){if(!ev)return null;if(ev.type==='unit_destroyed'||ev.type==='commander_destroyed')return ev.actor;if(ev.type==='army_asset_destroyed'||ev.type==='artillery_destroyed_on_contact')return ev.payload?.target||null;return null;}
  function pctTablePoint(p){if(!p)return null;const w=Number(state.project.playSpace?.width||48),h=Number(state.project.playSpace?.height||48);return{x:Number(p.x||0)/w*100,y:Number(p.y||0)/h*100};}
  function cuePoint(snap,id){return snap.units.find(u=>u.id===id)||snap.commanders.find(c=>c.id===id)||null;}
  function addCueIcon(host,cls,p,text=''){if(!p)return;const el=document.createElement('span');el.className=`replay-cue ${cls}`;el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;if(text)el.textContent=text;host.appendChild(el);}
  function addCueArrow(host,a,b,cls='shot'){if(!a||!b)return;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class',`replay-cue-arrow ${cls}`);svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');svg.innerHTML=`<defs><marker id="arrow-${cls}" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 Z"></path></marker></defs><line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" marker-end="url(#arrow-${cls})"></line>`;host.appendChild(svg);}
  function renderEventCue(snap){const host=$('#playReplayEvents');if(!host)return;host.innerHTML='';const level=state.playtestWorkspace.cueLevel||'standard';if(level==='off'||!snap?.event)return;const ev=snap.event,p=ev.payload||{},actor=cuePoint(snap,ev.actor),target=cuePoint(snap,p.target),mid=actor&&target?{x:(actor.x+target.x)/2,y:(actor.y+target.y)/2}:actor;
    if(ev.type==='command_test'||ev.type==='commander_command_test')addCueIcon(host,`command-flag ${p.outcome==='pass'?'pass':'fail'}`,actor);
    if((ev.type==='attack'&&p.shooting)||ev.type==='artillery'){addCueIcon(host,`smoke ${ev.type==='artillery'?'artillery-smoke':''}`,actor);addCueArrow(host,actor,target,'shot');}
    if(ev.type==='charge_contact'||ev.type==='commander_charge_contact'){const from=pctTablePoint(p.from)||actor;addCueArrow(host,from,target||actor,'charge');}
    if(ev.type==='charge'||(ev.type==='attack'&&!p.shooting))addCueIcon(host,'melee',mid,'⚔');
    if(['unit_destroyed','commander_destroyed','army_asset_destroyed','artillery_destroyed_on_contact'].includes(ev.type)){const victim=cuePoint(snap,deathVictim(ev))||actor;addCueIcon(host,'destroyed-cue',victim,'☠');}
    if(ev.type==='commander_escape')addCueIcon(host,'retreat-cue',actor,'‹‹');
    if(level==='detailed'&&ev.type==='ai_hold')addCueIcon(host,'hold-cue',actor,'◆');
  }
  function renderReplay(){syncBattlefieldImages(state);syncAspect();const host=$('#playReplayPieces'),label=$('#replayEventLabel'),slider=$('#replaySlider');host.innerHTML='';if(!currentRun){label.textContent='No replay loaded';slider.max=0;slider.value=0;$('#playReplayEvents').innerHTML='';drawHeat();return;}replayIndex=Math.max(0,Math.min(currentRun.snapshots.length-1,replayIndex));slider.max=currentRun.snapshots.length-1;slider.value=replayIndex;const snap=toPctSnapshot(currentRun.snapshots[replayIndex],state),victim=deathVictim(snap.event);for(const u of snap.units){if(u.destroyed&&u.id!==victim)continue;const el=document.createElement('div');el.className=`replay-piece ${u.faction.toLowerCase()} ${u.destroyed?'destroyed':''} ${u.inactive?'inactive':''}`;el.style.left=`${u.x}%`;el.style.top=`${u.y}%`;const fp=footprint(Number(u.baseMm||scenario().tabletop?.unitBaseMm||50));el.style.width=`${fp.width}%`;el.style.height=`${fp.height}%`;el.style.background=commandColor(u.faction,u.commandId);const facing=Number(u.facing||0);el.style.transform=`translate(-50%,-50%) rotate(${facing}deg)`;el.style.setProperty('--label-counter-rotation',`${-facing}deg`);el.innerHTML=`<span class="facing-arrow" aria-hidden="true"></span><span class="piece-label">${safe(u.name)}</span>`;el.title=`${u.name} · ${Number(u.baseMm||scenario().tabletop?.unitBaseMm||50)} mm square footprint · facing ${Number(u.facing||0).toFixed(0)}°`;host.appendChild(el);}for(const c of snap.commanders){if(c.destroyed&&c.id!==victim)continue;const el=document.createElement('div');el.className=`replay-commander ${c.faction.toLowerCase()} ${c.destroyed?'destroyed':''}`;el.style.left=`${c.x}%`;el.style.top=`${c.y}%`;const fp=footprint(Number(c.baseMm||scenario().tabletop?.commanderBaseMm||25));el.style.width=`${fp.width}%`;el.style.height=`${fp.height}%`;el.textContent='★';el.title=`${c.name} · ${Number(c.baseMm||scenario().tabletop?.commanderBaseMm||25)} mm round footprint`;host.appendChild(el);}label.textContent=eventText(snap.event);$('#replayCounter').textContent=`${replayIndex}/${currentRun.snapshots.length-1}`;renderBattleSoFar(snap);drawHeat();renderEventCue(snap);document.querySelectorAll('.event-row.active-event').forEach(x=>x.classList.remove('active-event'));document.querySelector(`.event-row[data-event-index="${snap.event?.i}"]`)?.classList.add('active-event');}
  function drawHeat(){const canvas=$('#playHeatCanvas');if(!canvas)return;const frame=$('#playReplayStage'),rect=frame.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));canvas.style.width=`${rect.width}px`;canvas.style.height=`${rect.height}px`;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,rect.width,rect.height);if(!currentRun||heatType==='none')return;const points=currentRun.heat?.[heatType]||[],cols=18,rows=18,grid=Array.from({length:rows},()=>Array(cols).fill(0)),w=Number(state.project.playSpace?.width||48),h=Number(state.project.playSpace?.height||48);for(const p of points){const x=Math.max(0,Math.min(cols-1,Math.floor(p.x/w*cols))),y=Math.max(0,Math.min(rows-1,Math.floor(p.y/h*rows)));grid[y][x]++;}const max=Math.max(1,...grid.flat());for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const v=grid[y][x]/max;if(!v)continue;ctx.fillStyle=`rgba(255,45,38,${0.10+v*.58})`;ctx.fillRect(x*rect.width/cols,y*rect.height/rows,rect.width/cols+1,rect.height/rows+1);}}
  function eventClass(ev){if(['attack','artillery','charge','charge_contact'].includes(ev.type))return'combat';if(['unit_destroyed','army_asset_destroyed','commander_destroyed','reinforcement_activated'].includes(ev.type))return'major';if(ev.type.startsWith('command'))return'command';if(ev.type.startsWith('commander'))return'command';if(ev.type.startsWith('move')||ev.type==='pivot')return'movement';if(ev.type.startsWith('ai_'))return'tactical';return'other';}
  function visibleEvent(ev){if(logMode==='debug')return true;if(logMode==='key')return['attack','artillery','charge','charge_contact','unit_destroyed','army_asset_destroyed','commander_destroyed','commander_escape','reinforcement_activated'].includes(ev.type);return !['pivot','break_test','commander_hold','ai_action_choice'].includes(ev.type);}
  function renderBattleSoFar(snap){if(!snap||!currentRun){$('#battleSoFar').innerHTML='';return;}const turn=snap.event?.turn||0,aliveF=snap.units.filter(u=>u.faction==='French'&&!u.destroyed).length,aliveI=snap.units.filter(u=>u.faction!=='French'&&!u.destroyed&&!u.inactive).length,a=sideLabel(scenario(),'French'),b=sideLabel(scenario(),'Imperial');$('#battleSoFar').innerHTML=`<strong>Turn ${turn} of ${settings().turns}</strong><span>${safe(a)} active ${aliveF}</span><span>${safe(b)} active ${aliveI}</span>`;}
  function renderLog(){const host=$('#playEventLog');if(!currentRun){host.innerHTML='<p class="muted">No run selected.</p>';return;}const groups=new Map();for(const ev of currentRun.events.filter(visibleEvent)){if(!groups.has(ev.turn))groups.set(ev.turn,[]);groups.get(ev.turn).push(ev);}host.innerHTML=[...groups.entries()].map(([turn,events])=>`<details class="turn-log" ${turn===1?'open':''}><summary>Turn ${turn}<span>${events.length} events</span></summary><div>${events.map(ev=>`<button class="event-row ${eventClass(ev)}" data-event-index="${ev.i}"><span>${ev.i}</span><strong>${safe(eventClass(ev))}</strong><small>${safe(eventText(ev,logMode==='debug'))}</small></button>`).join('')}</div></details>`).join('');host.querySelectorAll('[data-event-index]').forEach(b=>b.addEventListener('click',()=>{const idx=Number(b.dataset.eventIndex),snapIndex=currentRun.snapshots.findIndex(s=>s.event?.i===idx);if(snapIndex>=0){replayIndex=snapIndex;renderReplay();}}));}
  function stopPlayback(){if(playTimer){clearInterval(playTimer);playTimer=null;}if($('#replayPlay'))$('#replayPlay').textContent='▶ Play';}
  function startPlayback(){if(!currentRun)return;if(playTimer){stopPlayback();return;}const speed=Number($('#replaySpeed')?.value||1),ms=Math.max(80,650/speed);$('#replayPlay').textContent='⏸ Pause';playTimer=setInterval(()=>{if(replayIndex>=currentRun.snapshots.length-1){stopPlayback();return;}replayIndex++;renderReplay();},ms);}
  async function single(){if(isStale())return;stopPlayback();readiness();const rt=runtimeInfo();if(!rt.units.length||!rt.units.some(u=>u.faction==='French')||!rt.units.some(u=>u.faction==='Imperial'||u.faction==='Garrison'))return;setRunBusy(true,'Running deterministic game with tactical decision layer…');try{currentRun=await simulate('single',settings());currentBatch=null;replayIndex=0;scenario().playtestSingle={configHash:preparedHash,seed:currentRun.seed,winner:currentRun.winner,turnsCompleted:currentRun.turnsCompleted,victoryPoints:currentRun.victoryPoints,generatedAt:new Date().toISOString()};persist();resultCards(currentRun);batchCards(null);renderReplay();renderLog();renderTacticalPlan();$('#playRunStatus').textContent=`Seed ${currentRun.seed} complete · Auto/overridden tactical plan applied · ${preparedHash}`;}catch(error){simulationFailure(error);}finally{setRunBusy(false);}}
  async function batch(){if(isStale())return;stopPlayback();readiness();const rt=runtimeInfo();if(!rt.units.length||!rt.units.some(u=>u.faction==='French')||!rt.units.some(u=>u.faction==='Imperial'||u.faction==='Garrison'))return;setRunBusy(true,`Running ${settings().runs} games with tactical decision layer…`);try{currentBatch=await simulate('batch',settings());currentRun=currentBatch.results[0]||null;scenario().playtestSummary={configHash:preparedHash,runs:currentBatch.runs,seed:settings().seed,winPct:currentBatch.winPct,avgTurns:currentBatch.avgTurns,avgVp:currentBatch.avgVp,generatedAt:new Date().toISOString()};persist();replayIndex=0;batchCards(currentBatch);resultCards(currentRun);renderReplay();renderLog();renderTacticalPlan();$('#playRunStatus').textContent=`${currentBatch.runs} runs complete · ${preparedHash}`;}catch(error){simulationFailure(error);}finally{setRunBusy(false);}}
  function fitBattlefield(){const frame=$('#playReplayFrame');frame?.classList.add('fit');setTimeout(()=>{frame?.classList.remove('fit');drawHeat();},300);}

  $('#resetPlaytest')?.addEventListener('click',resetPlaytest);$('#resetPlaytestTop')?.addEventListener('click',resetPlaytest);$('#runSinglePlaytest')?.addEventListener('click',single);$('#runBatchPlaytest')?.addEventListener('click',batch);$('#replayPlay')?.addEventListener('click',startPlayback);$('#replayStart')?.addEventListener('click',()=>{stopPlayback();replayIndex=0;renderReplay();});$('#replayEnd')?.addEventListener('click',()=>{stopPlayback();if(currentRun){replayIndex=currentRun.snapshots.length-1;renderReplay();}});$('#replaySpeed')?.addEventListener('change',()=>{if(playTimer){stopPlayback();startPlayback();}});$('#replaySlider')?.addEventListener('input',e=>{replayIndex=Number(e.target.value);renderReplay();});$('#replayPrev')?.addEventListener('click',()=>{stopPlayback();replayIndex--;renderReplay();});$('#replayNext')?.addEventListener('click',()=>{stopPlayback();replayIndex++;renderReplay();});$('#playLogMode')?.addEventListener('change',e=>{logMode=e.target.value;renderLog();});$('#fitBattlefield')?.addEventListener('click',fitBattlefield);$('#replayCueLevel')?.addEventListener('change',e=>{state.playtestWorkspace.cueLevel=e.target.value;persist();renderReplay();});document.querySelectorAll('[data-heat]').forEach(b=>b.addEventListener('click',()=>{heatType=b.dataset.heat;document.querySelectorAll('[data-heat]').forEach(x=>x.classList.toggle('active',x===b));drawHeat();}));['playSeed','playRuns','playGarrisonTurn'].forEach(id=>$(`#${id}`)?.addEventListener('change',()=>{readiness();renderTacticalPlan();}));$('#playTurns')?.addEventListener('change',()=>{$('#playRunStatus').textContent='Playtest turn override changed. Reset if you want to return to scenario turn count.';});window.addEventListener('bax:scenario-changed',()=>{updateStale();readiness();renderTacticalPlan();renderReplay();});window.addEventListener('bax:battlefield-changed',()=>{syncBattlefieldImages(state);syncAspect();updateStale();readiness();renderTacticalPlan();renderReplay();});window.addEventListener('resize',()=>{syncAspect();drawHeat();});document.querySelector('[data-view="playtest"]')?.addEventListener('click',()=>setTimeout(()=>{syncBattlefieldImages(state);syncAspect();updateStale();readiness();renderTacticalPlan();renderReplay();},0));
  syncBattlefieldImages(state);syncAspect();if($('#replayCueLevel'))$('#replayCueLevel').value=state.playtestWorkspace.cueLevel;preparedHash=scenario().playtestPreparedHash||null;if(!preparedHash)resetPlaytest();else updateStale();readiness();renderTacticalPlan();resultCards(null);batchCards(null);renderReplay();renderLog();return{readiness,runSingle:single,runBatch:batch,reset:resetPlaytest,renderTacticalPlan};
}
