import { UNIT_LIBRARY } from '../data/scenarioData.js?v=0.5.0-ui-preview';

function xmur3(str){let h=1779033703^str.length;for(let i=0;i<str.length;i++){h=Math.imul(h^str.charCodeAt(i),3432918353);h=h<<13|h>>>19;}return()=>{h=Math.imul(h^h>>>16,2246822507);h=Math.imul(h^h>>>13,3266489909);return(h^h>>>16)>>>0;};}
function mulberry32(a){return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function makeRng(seed){const h=xmur3(String(seed))();const r=mulberry32(h);return{float:r,d6:()=>1+Math.floor(r()*6),d3:()=>1+Math.floor(r()*3)};}
const profileMap=new Map(UNIT_LIBRARY.map(x=>[x.profile,x]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const normDeg=d=>((d%360)+360)%360;
function bearing(a,b){return normDeg(Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI+90);}
function shortestTurn(a,b){return ((b-a+540)%360)-180;}
function pivotToward(u,target,ctx){const to=bearing(u,target),delta=shortestTurn(u.facing??0,to);if(Math.abs(delta)<.5){u.facing=to;return 0;}const from=u.facing??0;u.facing=to;ctx.event('pivot',u,{from,to,delta});return Math.abs(delta);}
function coalition(f){return f==='French'?'French':'Imperial';}
function pctToTable(p,state){return{x:Number(p.x||0)/100*Number(state.project.playSpace?.width||48),y:Number(p.y||0)/100*Number(state.project.playSpace?.height||48)};}
function tableToPct(p,state){return{x:p.x/Number(state.project.playSpace?.width||48)*100,y:p.y/Number(state.project.playSpace?.height||48)*100};}
function toTablePoint(p,width,height){return{x:Number(p[0]||0)/100*width,y:Number(p[1]||0)/100*height};}
function pointInPoly(x,y,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const xi=pts[i].x,yi=pts[i].y,xj=pts[j].x,yj=pts[j].y;const hit=((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/((yj-yi)||1e-9)+xi);if(hit)inside=!inside;}return inside;}
function pointSegDistance(x,y,a,b){const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;if(!l2)return Math.hypot(x-a.x,y-a.y);let t=((x-a.x)*dx+(y-a.y)*dy)/l2;t=Math.max(0,Math.min(1,t));return Math.hypot(x-(a.x+t*dx),y-(a.y+t*dy));}
function featureTerrain(state){
  const width=Number(state.project.playSpace?.width||48),height=Number(state.project.playSpace?.height||48);
  return (state.project.features||[]).map(f=>({f,dec:state.decisions?.[f.id]})).filter(x=>x.dec?.status==='approved').map(({f,dec})=>{
    const parts=(f.geometry?.parts||[]).map(part=>({closed:!!part.closed,points:(part.points||[]).map(p=>toTablePoint(p,width,height))})).filter(p=>p.points.length>=2);
    const z={id:f.id,name:f.name,cls:dec.cls||f.cls,effects:new Set(dec.effects||[]),parts,override:f.terrainOverride||null};
    if(!parts.length&&Array.isArray(f.box)){z.x=f.box[0]/100*width;z.y=f.box[1]/100*height;z.w=f.box[2]/100*width;z.h=f.box[3]/100*height;}
    return z;
  });
}
function terrainContains(z,x,y){
  if(z.parts?.length){for(const p of z.parts){if(p.closed&&p.points.length>=3&&pointInPoly(x,y,p.points))return true;if(!p.closed){const buffer=z.cls==='Masonry Wall'?0.22:z.cls==='Road'?0.18:z.cls==='Open Grove'?0.18:0.14;for(let i=1;i<p.points.length;i++)if(pointSegDistance(x,y,p.points[i-1],p.points[i])<=buffer)return true;}}return false;}
  return Number.isFinite(z.x)&&x>=z.x&&x<=z.x+z.w&&y>=z.y&&y<=z.y+z.h;
}
function terrainAt(terrain,x,y){
  const out=new Set();let openOverride=false;
  for(const z of terrain)if(terrainContains(z,x,y)){if(z.override==='Open Crossing'||z.cls==='Bridge')openOverride=true;for(const e of z.effects)out.add(e);}
  if(openOverride){out.delete('Difficult');out.delete('Impassable');}
  return out;
}
function terrainAlong(terrain,a,b){const out=new Set(),d=dist(a,b),steps=Math.max(1,Math.ceil(d/.25));for(let i=0;i<=steps;i++){const q=i/steps,x=a.x+(b.x-a.x)*q,y=a.y+(b.y-a.y)*q;for(const e of terrainAt(terrain,x,y))out.add(e);}return out;}

function baseSize(u){return (u.profile==='Camp'||u.profile==='Baggage Train')?40/25.4:50/25.4;}
function endpointClear(u,x,y,ctx){return !ctx.units.some(o=>o.id!==u.id&&!o.destroyed&&!o.inactive&&Math.hypot(x-o.x,y-o.y)<(baseSize(u)+baseSize(o))/2-1e-4);}
function nearestClearEndpoint(u,start,desired,ctx){const dx=desired.x-start.x,dy=desired.y-start.y;for(let f=1;f>=0;f-=0.025){const x=start.x+dx*f,y=start.y+dy*f;if(endpointClear(u,x,y,ctx))return{x,y,f};}return null;}
function commanderForUnit(unit,commanders){return commanders.find(c=>!c.destroyed&&c.faction===unit.faction&&c.commandId===unit.commandId)||null;}
function generalForUnit(unit,commanders){return commanders.find(c=>!c.destroyed&&c.faction===unit.faction&&c.isGeneral)||null;}
function commandBonus(unit,commanders,scale){
  const own=commanderForUnit(unit,commanders);if(own&&dist(unit,own)<=3*scale)return{bonus:1,commander:own,range:3*scale,kind:'command'};
  const gen=generalForUnit(unit,commanders);if(gen&&dist(unit,gen)<=4*scale)return{bonus:1,commander:gen,range:4*scale,kind:'general'};
  return{bonus:0,commander:null,range:0,kind:'none'};
}
function commandTest(unit,ctx){const threshold=unit.traits.includes('Elite')?3:4,cb=commandBonus(unit,ctx.commanders,ctx.scale),die=ctx.rng.d6(),roll=die+cb.bonus,ok=roll>=threshold;ctx.event('command_test',unit,{die,bonus:cb.bonus,bonusFrom:cb.commander?.name||null,bonusKind:cb.kind,distance:cb.commander?Number(dist(unit,cb.commander).toFixed(2)):null,range:cb.range||null,roll,threshold,outcome:ok?'pass':'fail'});return ok;}
function coverageForCommander(c,ctx){const range=(c.isGeneral?4:3)*ctx.scale;const candidates=ctx.units.filter(u=>!u.destroyed&&!u.inactive&&u.faction===c.faction&&(c.isGeneral||u.commandId===c.commandId));const covered=candidates.filter(u=>dist(c,u)<=range);return{range,candidates,covered,uncovered:candidates.filter(u=>dist(c,u)>range)};}
function commanderMoveTarget(c,ctx){const cov=coverageForCommander(c,ctx);if(!cov.candidates.length)return{cov,target:null,reason:'no active commanded units'};if(!cov.uncovered.length)return{cov,target:null,reason:'all eligible units already in command range'};const pool=cov.uncovered;return{cov,target:{x:pool.reduce((a,u)=>a+u.x,0)/pool.length,y:pool.reduce((a,u)=>a+u.y,0)/pool.length},reason:'reposition to improve command coverage'};}
function moveCommander(c,ctx){
  const before=commanderMoveTarget(c,ctx);if(!before.target){ctx.event('commander_hold',c,{reason:before.reason,covered:before.cov.covered.length,total:before.cov.candidates.length,commandRange:before.cov.range});return;}
  const maxMove=4*ctx.scale,d=dist(c,before.target);if(d<.01)return;let travel=Math.min(maxMove,d),nx=c.x+(before.target.x-c.x)/d*travel,ny=c.y+(before.target.y-c.y)/d*travel;
  // Commanders may not move within 1" (scaled) of an enemy. Shorten the move if necessary.
  const enemies=ctx.units.filter(u=>!u.destroyed&&!u.inactive&&coalition(u.faction)!==coalition(c.faction));
  while(travel>0&&enemies.some(e=>Math.hypot(nx-e.x,ny-e.y)<1*ctx.scale)){travel=Math.max(0,travel-.25);nx=c.x+(before.target.x-c.x)/d*travel;ny=c.y+(before.target.y-c.y)/d*travel;}
  const from={x:c.x,y:c.y};c.x=clamp(nx,0,ctx.width);c.y=clamp(ny,0,ctx.height);const after=coverageForCommander(c,ctx);ctx.event('commander_move',c,{from,to:{x:c.x,y:c.y},distance:Number(dist(from,c).toFixed(2)),reason:before.reason,coveredBefore:before.cov.covered.length,coveredAfter:after.covered.length,total:after.candidates.length,commandRange:after.range});
}
function moveCommandersForSide(side,ctx){for(const c of ctx.commanders.filter(c=>c.faction===side&&!c.destroyed))moveCommander(c,ctx);}
function breakTest(target,ctx){const roll=ctx.rng.d6(),total=roll+target.damage;if(total>=6){target.destroyed=true;ctx.event('unit_destroyed',target,{roll,damage:target.damage});return false;}ctx.event('break_test',target,{roll,damage:target.damage,total,outcome:'survives'});target.damage=0;return true;}
function shootingDice(u){if(u.traits.includes('Arquebus')||u.traits.includes('Arquebuses')||u.traits.includes('Pistols'))return 2;const s=u.traits.find(t=>/^Shoot \d+/i.test(t));return s?Number(s.match(/\d+/)[0]):0;}
function defenseState(target,ctx){const effects=terrainAt(ctx.terrain,target.x,target.y),defensive=effects.has('Defensive');return{effects:[...effects],defensive,baseArmor:target.armor,effectiveArmor:defensive?6:target.armor};}
function attack(target,count,armor,ctx,attacker,shooting=false,meta={}){const rolls=Array.from({length:count},()=>ctx.rng.d6()),hits=rolls.filter(r=>r>=armor).length;target.damage+=hits;ctx.event('attack',attacker,{target:target.id,targetName:target.name,rolls,armor,hits,shooting,...meta});if(hits&&!target.destroyed)breakTest(target,ctx);return hits;}
function shoot(u,target,ctx){if(u.destroyed||target.destroyed)return false;const defense=defenseState(target,ctx);if(u.traits.includes('Artillery')){if(dist(u,target)>8*ctx.scale)return false;const roll=ctx.rng.d6();ctx.event('artillery',u,{target:target.id,targetName:target.name,roll,terrain:defense.effects,defensive:defense.defensive,note:defense.defensive?'Target is in Defensive terrain; normal artillery procedure retained.':''});if(roll>=5){target.damage+=ctx.rng.d3();breakTest(target,ctx);}return true;}const dice=shootingDice(u);if(!dice)return false;const range=(u.traits.includes('Arquebus')||u.traits.includes('Arquebuses')||u.traits.includes('Pistols')?2:4)*ctx.scale;if(dist(u,target)>range)return false;let armor=defense.effectiveArmor;if(!defense.defensive){if(u.traits.includes('Arquebus')||u.traits.includes('Arquebuses'))armor=4;if(u.traits.includes('Pistols'))armor=5;}attack(target,dice,armor,ctx,u,true,{terrain:defense.effects,defensive:defense.defensive,baseArmor:defense.baseArmor,defensiveArmor:defense.defensive?6:null});return true;}
function melee(u,target,ctx){if(u.destroyed||target.destroyed)return false;if(target.traits.includes('Army Asset')){target.destroyed=true;ctx.event('army_asset_destroyed',u,{target:target.id,targetName:target.name,assetType:target.profile,victoryPoints:target.points||4});return true;}if(u.traits.includes('Army Asset'))return false;pivotToward(u,target,ctx);const uDef=defenseState(u,ctx),tDef=defenseState(target,ctx);let ud=u.combat;if(u.traits.includes('Fury')||u.traits.includes('Shock Cavalry')){if(!(u.traits.includes('Shock Cavalry')&&target.traits.includes('Pikes')))ud*=2;}let td=target.combat;if(target.traits.includes('Pikes'))td*=2;ctx.event('engagement',u,{target:target.id,targetName:target.name,attackerDefensive:uDef.defensive,defenderDefensive:tDef.defensive,defenderAttacksFirst:tDef.defensive&&!uDef.defensive});const strikeU=()=>attack(target,ud,tDef.effectiveArmor,ctx,u,false,{terrain:tDef.effects,defensive:tDef.defensive,baseArmor:tDef.baseArmor,defensiveArmor:tDef.defensive?6:null});const strikeT=()=>attack(u,td,uDef.effectiveArmor,ctx,target,false,{terrain:uDef.effects,defensive:uDef.defensive,baseArmor:uDef.baseArmor,defensiveArmor:uDef.defensive?6:null});if(tDef.defensive&&!uDef.defensive){strikeT();if(!u.destroyed&&!target.destroyed)strikeU();}else{strikeU();if(!u.destroyed&&!target.destroyed)strikeT();}return true;}
function moveToward(u,target,ctx){if(u.traits.includes('Immobile')){ctx.event('move_blocked',u,{reason:'Immobile army asset'});return false;}const start={x:u.x,y:u.y},d=dist(u,target);if(d<.01)return false;pivotToward(u,target,ctx);let allowance=u.move*ctx.scale;const tentative={x:u.x+(target.x-u.x)/d*Math.min(d,allowance),y:u.y+(target.y-u.y)/d*Math.min(d,allowance)};let effects=terrainAlong(ctx.terrain,start,tentative);if(effects.has('Difficult'))allowance/=2;const travel=Math.min(d,allowance),nx=clamp(u.x+(target.x-u.x)/d*travel,1,ctx.width-1),ny=clamp(u.y+(target.y-u.y)/d*travel,1,ctx.height-1);effects=terrainAlong(ctx.terrain,start,{x:nx,y:ny});if(effects.has('Impassable')){ctx.event('move_blocked',u,{from:start,toward:{x:nx,y:ny},reason:'Impassable terrain'});return false;}const clear=nearestClearEndpoint(u,start,{x:nx,y:ny},ctx);if(!clear){ctx.event('move_blocked',u,{from:start,toward:{x:nx,y:ny},reason:'Final position occupied'});return false;}if(clear.f<0.999)ctx.event('move_shortened',u,{intended:{x:nx,y:ny},to:{x:clear.x,y:clear.y},reason:'Final footprint collision'});u.x=clear.x;u.y=clear.y;if(effects.has('Dangerous')&&ctx.rng.d6()===1){u.destroyed=true;ctx.event('unit_destroyed',u,{cause:'dangerous terrain'});}ctx.event('move',u,{from:start,to:{x:u.x,y:u.y},distance:dist(start,u),terrain:[...effects]});return true;}
function nearestEnemy(u,units){return units.filter(x=>!x.destroyed&&coalition(x.faction)!==coalition(u.faction)).sort((a,b)=>dist(u,a)-dist(u,b))[0]||null;}
function activate(u,ctx,unalerted){if(u.destroyed||u.inactive||u.traits.includes('Army Asset'))return;if(unalerted.has(u.id)){if(!commandTest(u,ctx)){ctx.event('activation_blocked',u,{reason:'unalerted'});return;}unalerted.delete(u.id);ctx.event('unit_alerted',u,{});}const act=()=>{const t=nearestEnemy(u,ctx.units);if(!t)return false;if(shoot(u,t,ctx))return true;const reach=u.move*ctx.scale+2;if(dist(u,t)<=reach)return melee(u,t,ctx);return moveToward(u,t,ctx);};const acted=act();if(acted&&!u.destroyed&&commandTest(u,ctx))act();}
function vpFor(side,units){return units.filter(u=>coalition(u.faction)!==coalition(side)&&u.destroyed).reduce((a,u)=>a+(u.points||(['Camp','Baggage Train'].includes(u.profile)?4:0)),0);}
function winner(units,turn,maxTurns){const alive=new Set(units.filter(u=>!u.destroyed&&!u.inactive).map(u=>coalition(u.faction)));if(alive.size===1)return [...alive][0];if(turn>maxTurns){const f=vpFor('French',units),i=vpFor('Imperial',units);return f===i?'Draw':f>i?'French':'Imperial';}return null;}
function makeSnapshot(ctx,event){return{event,units:ctx.units.map(u=>({id:u.id,name:u.name,profile:u.profile,commandId:u.commandId,faction:u.faction,x:u.x,y:u.y,facing:u.facing??0,destroyed:u.destroyed,inactive:u.inactive})),commanders:ctx.commanders.map(c=>({...c}))};}
function acceptedText(s){return (s.suggestions||[]).filter(x=>x.status==='accepted').map(x=>`${x.title} ${x.proposal}`).join(' ').toLowerCase();}

export function scenarioConfigFingerprint(state){const s=state.project.scenario||{};const relevant={playSpace:state.project.playSpace,metadata:s.metadata,commands:s.commands,deployment:s.deployment,rules:(s.suggestions||[]).filter(x=>x.status==='accepted').map(x=>({id:x.id,title:x.title,proposal:x.proposal,engineStatus:x.engineStatus,engineText:x.engineText,overrides:x.overrides})),victory:s.victoryText,terrain:(state.project.features||[]).map(f=>({id:f.id,geometry:f.geometry,box:f.box,override:f.terrainOverride,decision:state.decisions?.[f.id]}))};const str=JSON.stringify(relevant);let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return `cfg-${(h>>>0).toString(16).padStart(8,'0')}`;}

export function buildRuntimeFromStudio(state,settings={}){const s=state.project.scenario,units=[],commanders=[],scale=Number(settings.measurementScale||2);for(const [faction,cmds] of Object.entries(s.commands||{})){for(let ci=0;ci<(cmds||[]).length;ci++){const c=cmds[ci];const cp=s.deployment?.commanderPlacements?.[c.id];if(c.commander&&cp){const p=pctToTable(cp,state);commanders.push({id:`cmd-${c.id}`,commandId:c.id,name:c.commander,faction,x:p.x,y:p.y,destroyed:false,isGeneral:!!c.isGeneral||ci===0});}for(const u of c.units||[]){const p0=s.deployment?.placements?.[u.id];if(!p0)continue;const p=pctToTable(p0,state),base=profileMap.get(u.profile)||{m:2,c:2,a:4,pts:1,traits:[]};units.push({id:u.id,name:u.name,profile:u.profile,faction,commandId:c.id,x:p.x,y:p.y,facing:Number(p0.facing??(faction==='French'?0:180)),move:base.m,combat:base.c,armor:base.a,points:base.pts,traits:[...new Set([...(base.traits||[]),...(u.traits||[]), ...(['Camp','Baggage Train'].includes(u.profile)?['Immobile','Army Asset',u.profile]:[])])],damage:0,destroyed:false,inactive:false});}}}
  const text=acceptedText(s),surprise=text.includes('surprise')||text.includes('unalerted')||text.includes('readiness'),sortie=text.includes('sortie')||text.includes('garrison');const garrisonTurn=Number(settings.garrisonTurn||2);if(sortie)for(const u of units)if(u.faction==='Garrison')u.inactive=true;const unalerted=new Set();if(surprise){for(const u of units.filter(x=>x.faction==='French')){const near=units.some(e=>e.faction==='Imperial'&&!e.destroyed&&dist(u,e)<=18);if(!near)unalerted.add(u.id);}}
  return{units,commanders,terrain:featureTerrain(state),scale,width:Number(state.project.playSpace?.width||48),height:Number(state.project.playSpace?.height||48),surprise,sortie,garrisonTurn,unalerted};}

export function runPlaytest(state,settings={}){const seed=settings.seed??1,maxTurns=Number(settings.turns||state.project.scenario.metadata?.gameLength||6||6),runtime=buildRuntimeFromStudio(state,settings),rng=makeRng(seed),events=[],snapshots=[],heat={movement:[],combat:[],casualty:[],commander:[],congestion:[]};let eventNo=0;const ctx={...runtime,rng,event(type,actor,payload={}){const ev={i:++eventNo,turn:ctx.turn||0,side:ctx.side||'',type,actor:actor?.id||null,actorName:actor?.name||actor?.id||'',x:actor?.x??null,y:actor?.y??null,payload};events.push(ev);if(type==='move')heat.movement.push({x:actor.x,y:actor.y});if(['attack','artillery','engagement'].includes(type))heat.combat.push({x:actor.x,y:actor.y});if(['unit_destroyed','army_asset_destroyed'].includes(type))heat.casualty.push({x:actor.x,y:actor.y});snapshots.push(makeSnapshot(ctx,ev));}};snapshots.push(makeSnapshot(ctx,{i:0,turn:0,type:'setup',actor:null,payload:{}}));let turn=1,win=null;const order=['Imperial','Garrison','French'];while(turn<=maxTurns&&!win){ctx.turn=turn;if(runtime.sortie&&turn>=runtime.garrisonTurn)for(const u of ctx.units.filter(x=>x.faction==='Garrison'&&x.inactive)){u.inactive=false;ctx.event('reinforcement_activated',u,{turn});}for(const c of ctx.commanders)if(!c.destroyed)heat.commander.push({x:c.x,y:c.y});for(const u of ctx.units)if(!u.destroyed&&!u.inactive)heat.congestion.push({x:u.x,y:u.y});for(const side of order){ctx.side=side;for(const u of ctx.units.filter(x=>x.faction===side&&!x.destroyed&&!x.inactive))activate(u,ctx,runtime.unalerted);moveCommandersForSide(side,ctx);win=winner(ctx.units,turn,maxTurns);if(win)break;}turn++;}
  if(!win)win=winner(ctx.units,turn,maxTurns)||'Draw';const result={seed,winner:win,turnsCompleted:Math.min(turn-1,maxTurns),victoryPoints:{French:vpFor('French',ctx.units),Imperial:vpFor('Imperial',ctx.units)},survivors:{French:ctx.units.filter(u=>u.faction==='French'&&!u.destroyed).length,Imperial:ctx.units.filter(u=>u.faction==='Imperial'&&!u.destroyed).length,Garrison:ctx.units.filter(u=>u.faction==='Garrison'&&!u.destroyed).length},events,snapshots,heat,finalUnits:ctx.units};return result;}

export function runBatch(state,settings={}){const runs=clamp(Number(settings.runs||20),1,250),base=Number(settings.seed||1),results=[];for(let i=0;i<runs;i++)results.push(runPlaytest(state,{...settings,seed:base+i}));const wins={French:0,Imperial:0,Draw:0};for(const r of results)wins[r.winner]=(wins[r.winner]||0)+1;const avg=k=>results.reduce((a,r)=>a+r[k],0)/runs;const avgVp={French:results.reduce((a,r)=>a+r.victoryPoints.French,0)/runs,Imperial:results.reduce((a,r)=>a+r.victoryPoints.Imperial,0)/runs};return{runs,wins,winPct:Object.fromEntries(Object.entries(wins).map(([k,v])=>[k,v/runs*100])),avgTurns:avg('turnsCompleted'),avgVp,results};}

export function toPctSnapshot(snapshot,state){return{...snapshot,units:snapshot.units.map(u=>({...u,...tableToPct(u,state)})),commanders:snapshot.commanders.map(c=>({...c,...tableToPct(c,state)}))};}
