import { loadState } from '../app/state.js?v=0.6.9.1';
import { setupScenarioLibrary } from './scenarioLibrary.js?v=0.6.9.1';
import { setupExternalAiExchange } from './externalAiExchange.js?v=0.6.9.1';
import { generateAutoTacticalPlan690, interpretSemanticOrder690, validateTacticalPlanWorkspace690 } from './tacticalPlanner690.js?v=0.6.9.1';

const VERSION='0.6.9.1';
const AUTO_KEYS='bax-690-auto-keys';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const freshState=()=>loadState().state;
function autoKeys(){try{return new Set(JSON.parse(sessionStorage.getItem(AUTO_KEYS)||'[]'));}catch{return new Set();}}
function saveAutoKeys(set){try{sessionStorage.setItem(AUTO_KEYS,JSON.stringify([...set]));}catch{}}
function keyFor(el){if(el?.dataset?.armyPosture)return`army:${el.dataset.armyPosture}:posture`;if(el?.dataset?.armyText)return`army:${el.dataset.armyText}:text`;if(el?.dataset?.commandOrder)return`command:${el.dataset.commandOrder}:order`;if(el?.dataset?.commandText)return`command:${el.dataset.commandText}:text`;return null;}

function installStyles(){if(document.querySelector('#bax690Styles'))return;const style=document.createElement('style');style.id='bax690Styles';style.textContent=`
#tacticalPlanEditor .order-interpretation{display:none!important}.bax-library-dialog{width:min(980px,92vw);max-width:980px}.bax-library-tools{display:grid;grid-template-columns:1fr 180px auto;gap:10px;align-items:end;margin:12px 0}.bax-library-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px;margin-top:12px}.bax-library-card{border:1px solid var(--line,#d8dee8);border-radius:10px;padding:14px;background:var(--panel,#fff)}.bax-library-card header{display:flex;justify-content:space-between;gap:12px}.bax-library-card h3{margin:.15rem 0}.bax-library-card dl{display:grid;gap:4px}.bax-library-card dl div{display:grid;grid-template-columns:70px 1fr;gap:8px}.bax-library-card dt{font-weight:700}.bax-tactical-ai{width:min(980px,92vw);max-width:980px}.bax690-plan-tools{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.bax690-auto-summary{margin:10px 0;padding:10px 12px;border:1px solid var(--line,#d8dee8);border-radius:8px;background:rgba(80,110,150,.06)}.bax690-auto-summary h4{margin:0 0 6px}.bax690-auto-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:8px}.bax690-auto-side{padding:8px;border-left:3px solid currentColor;background:rgba(80,110,150,.04)}.bax690-interpretation{margin:4px 0 10px;padding:8px 10px;border-radius:7px;border:1px solid var(--line,#d8dee8);font-size:.88rem}.bax690-interpretation strong{display:block;margin-bottom:3px}.bax690-understood{border-left:4px solid #2d7a46}.bax690-warning{border-left:4px solid #ad7b1c}.bax690-blocked{border-left:4px solid #a43b35;background:rgba(164,59,53,.06)}.bax690-interpretation ul{margin:5px 0 0;padding-left:18px}.bax690-run-blocked{outline:2px solid #a43b35;outline-offset:2px}@media(max-width:760px){.bax-library-tools{grid-template-columns:1fr}.bax-library-list{grid-template-columns:1fr}}
`;document.head.appendChild(style);}

function patchVersionLabel(){window.__BAX_VERSION__=VERSION;const el=document.querySelector('#runtimeVersion');if(el)el.textContent=`v${VERSION}`;const diag=document.querySelector('#diagApp');if(diag&&/v0\.6\.8\.1/.test(diag.textContent||''))diag.textContent=(diag.textContent||'').replace('v0.6.8.1',`v${VERSION}`);document.documentElement.dataset.baxRelease=VERSION;}
function patchPlaytestWorkerCacheBust(){if(window.__BAX_690_WORKER_PATCH__||typeof window.Worker!=='function')return;const NativeWorker=window.Worker;function BattleAxeWorker(url,options){try{const u=new URL(url,document.baseURI);if(/\/playtestWorker\.js$/.test(u.pathname))u.searchParams.set('v',VERSION);return new NativeWorker(u,options);}catch{return new NativeWorker(url,options);}}BattleAxeWorker.prototype=NativeWorker.prototype;try{Object.setPrototypeOf(BattleAxeWorker,NativeWorker);}catch{}window.Worker=BattleAxeWorker;window.__BAX_690_WORKER_PATCH__=true;}
function snapshotFromDom(){const state=freshState(),w=state.playtestWorkspace||(state.playtestWorkspace={armyOrders:{},commandOrders:{},cueLevel:'standard'});w.armyOrders=w.armyOrders||{};w.commandOrders=w.commandOrders||{};document.querySelectorAll('[data-army-posture]').forEach(el=>{const side=el.dataset.armyPosture;w.armyOrders[side]={...(w.armyOrders[side]||{}),posture:el.value};});document.querySelectorAll('[data-army-text]').forEach(el=>{const side=el.dataset.armyText;w.armyOrders[side]={...(w.armyOrders[side]||{}),text:el.value};});document.querySelectorAll('[data-command-order]').forEach(el=>{const id=el.dataset.commandOrder;w.commandOrders[id]={...(w.commandOrders[id]||{}),order:el.value};});document.querySelectorAll('[data-command-text]').forEach(el=>{const id=el.dataset.commandText;w.commandOrders[id]={...(w.commandOrders[id]||{}),text:el.value};});return state;}
function semanticHtml(x){if(x.status==='empty')return`<div class="bax690-interpretation bax690-understood"><strong>Auto / no written override</strong><span>${esc(x.meaning[0])}</span></div>`;const cls=x.status==='blocked'?'bax690-blocked':x.warnings.length?'bax690-warning':'bax690-understood',title=x.status==='blocked'?'Cannot execute as written':x.warnings.length?'Understood with execution note':'Understood';return`<div class="bax690-interpretation ${cls}"><strong>${title}</strong>${x.meaning.length?`<ul>${x.meaning.map(m=>`<li>${esc(m)}</li>`).join('')}</ul>`:''}${x.execution?.length?`<ul>${x.execution.map(m=>`<li><b>Game term:</b> ${esc(m.field)} = ${esc(m.value)}</li>`).join('')}</ul>`:''}${x.warnings.length?`<ul>${x.warnings.map(m=>`<li><b>Note:</b> ${esc(m)}</li>`).join('')}</ul>`:''}${x.unresolved.length?`<ul>${x.unresolved.map(m=>`<li><b>Needs correction:</b> ${esc(m)}</li>`).join('')}</ul>`:''}</div>`;}
let lastInterpretFingerprint='';
function renderInterpretations(){const host=document.querySelector('#tacticalPlanEditor');if(!host)return;const state=snapshotFromDom(),army=[...host.querySelectorAll('[data-army-text]')],cmd=[...host.querySelectorAll('[data-command-text]')],fingerprint=JSON.stringify([...army,...cmd].map(x=>[keyFor(x),x.value])),expected=army.length+cmd.filter(x=>String(x.value||'').trim()).length;if(fingerprint===lastInterpretFingerprint&&host.querySelectorAll('.bax690-interpretation').length===expected)return;lastInterpretFingerprint=fingerprint;host.querySelectorAll('.bax690-interpretation').forEach(x=>x.remove());for(const el of army){const x=interpretSemanticOrder690(el.value,state,{scope:'army',side:el.dataset.armyText});el.closest('label')?.insertAdjacentHTML('afterend',semanticHtml(x));}for(const el of cmd){if(!String(el.value||'').trim())continue;const x=interpretSemanticOrder690(el.value,state,{scope:'command',commandId:el.dataset.commandText});el.closest('.tactical-command')?.insertAdjacentHTML('afterend',semanticHtml(x));}}
function autoSummaryHtml(plan){return`<h4>Auto Tactical Planner preview</h4><div class="bax690-auto-grid">${['sideA','sideB'].map(side=>{const a=plan.armies?.[side],cmds=Object.values(plan.commands||{}).filter(c=>c.side===side);if(!a)return'';return`<div class="bax690-auto-side"><strong>${esc(a.label||side)} — ${esc(a.posture)}</strong><p>${esc(a.reason||'')}</p><ul>${cmds.map(c=>`<li>${esc(c.name)}: <b>${esc(c.order)}</b> — ${esc(c.mission)}</li>`).join('')}</ul></div>`;}).join('')}</div>${plan.notes?.length?`<p class="help">${esc(plan.notes.join(' '))}</p>`:''}`;}
function setAutoControl(selector,value,key){const el=document.querySelector(selector);if(!el)return false;const keys=autoKeys(),can=el.value==='Auto'||keys.has(key);if(!can)return false;keys.add(key);saveAutoKeys(keys);el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}));return true;}
function setDerivedControl(selector,value,key){const el=document.querySelector(selector);if(!el||el.value!=='Auto')return false;const keys=autoKeys();keys.delete(key);saveAutoKeys(keys);el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}));return true;}
function applySemanticExecution(){let state=snapshotFromDom();for(const el0 of [...document.querySelectorAll('[data-command-text]')]){const id=el0.dataset.commandText,text=el0.value;if(!String(text||'').trim())continue;const x=interpretSemanticOrder690(text,state,{scope:'command',commandId:id});if(x.status==='blocked')continue;let order=x.action||((x.region==='left'||x.region==='right'||x.region==='nearest')?'Maneuver':null);if(order&&['Hold','Defend','Advance','Assault','Reserve','Screen','Maneuver','Withdraw'].includes(order))setDerivedControl(`[data-command-order="${CSS.escape(id)}"]`,order,`command:${id}:order`);state=snapshotFromDom();}}
function applyAutoPlanToLive(plan){for(const [side,a] of Object.entries(plan.armies||{}))setAutoControl(`[data-army-posture="${CSS.escape(side)}"]`,a.posture||'Balanced',`army:${side}:posture`);for(const [id,c] of Object.entries(plan.commands||{}))setAutoControl(`[data-command-order="${CSS.escape(id)}"]`,c.order||'Advance',`command:${id}:order`);}

function setupTacticalUi(){const panel=document.querySelector('.tactical-plan-panel'),heading=panel?.querySelector('.panel-heading');if(!panel||!heading)return false;let tools=document.querySelector('#bax690PlanTools');if(!tools){tools=document.createElement('div');tools.id='bax690PlanTools';tools.className='bax690-plan-tools';const preview=document.createElement('button');preview.id='previewAutoPlan690';preview.className='secondary compact';preview.type='button';preview.textContent='Preview Auto Plan';tools.appendChild(preview);heading.appendChild(tools);const summary=document.createElement('div');summary.id='bax690AutoSummary';summary.className='bax690-auto-summary';summary.hidden=true;heading.after(summary);preview.addEventListener('click',()=>{const p=generateAutoTacticalPlan690(snapshotFromDom());summary.innerHTML=autoSummaryHtml(p);summary.hidden=false;});}
  const editor=document.querySelector('#tacticalPlanEditor');if(editor&&!editor.dataset.bax690Bound){editor.dataset.bax690Bound='1';const observer=new MutationObserver(()=>queueMicrotask(renderInterpretations));observer.observe(editor,{childList:true,subtree:true});editor.addEventListener('input',()=>queueMicrotask(renderInterpretations),true);editor.addEventListener('change',e=>{if(e.isTrusted){const key=keyFor(e.target);if(key){const set=autoKeys();set.delete(key);saveAutoKeys(set);}}queueMicrotask(renderInterpretations);},true);renderInterpretations();}
  const beforeRun=e=>{let state=snapshotFromDom(),issues=validateTacticalPlanWorkspace690(state);if(issues.length){e.preventDefault();e.stopImmediatePropagation();const first=issues[0],status=document.querySelector('#playRunStatus');if(status)status.textContent=`Playtest not started: ${first.label} has a written Tactical Plan clause the local engine cannot execute safely. Review the red Engine Interpretation warning; Battle Axe will not silently substitute a default.`;e.currentTarget.classList.add('bax690-run-blocked');setTimeout(()=>e.currentTarget.classList.remove('bax690-run-blocked'),1600);renderInterpretations();return;}applySemanticExecution();state=snapshotFromDom();const plan=generateAutoTacticalPlan690(state);applyAutoPlanToLive(plan);const summary=document.querySelector('#bax690AutoSummary');if(summary){summary.innerHTML=autoSummaryHtml(plan);summary.hidden=false;}setTimeout(()=>{renderInterpretations();window.dispatchEvent(new CustomEvent('bax:tactical-plan-prepared',{detail:{version:VERSION,plan}}));},0);};
  const single=document.querySelector('#runSinglePlaytest'),batch=document.querySelector('#runBatchPlaytest');if(single&&!single.dataset.bax690Bound){single.dataset.bax690Bound='1';single.addEventListener('click',beforeRun,true);}if(batch&&!batch.dataset.bax690Bound){batch.dataset.bax690Bound='1';batch.addEventListener('click',beforeRun,true);}return true;
}

function boot(){if(typeof window==='undefined'||typeof document==='undefined')return;if(window.__BAX_RELEASE_690_SETUP__)return;const ready=document.querySelector('#openProjectBtn')&&document.querySelector('#aiBridgeDialog')&&document.querySelector('.tactical-plan-panel');if(!ready){setTimeout(boot,80);return;}window.__BAX_RELEASE_690_SETUP__=true;installStyles();patchVersionLabel();patchPlaytestWorkerCacheBust();setupScenarioLibrary({studioVersion:VERSION});setupExternalAiExchange({studioVersion:VERSION});setupTacticalUi();setTimeout(patchVersionLabel,700);setTimeout(patchVersionLabel,2500);}
if(typeof window!=='undefined'&&typeof document!=='undefined')setTimeout(boot,0);
export function setupRelease690(){if(typeof window!=='undefined'&&typeof document!=='undefined')boot();}
