import { loadState, normalizeImportedState, migrateImportedProject, mergeImportedScenarioWithCurrentBattlefield, savePreImportBackup, saveState } from '../app/state.js?v=0.6.8.1';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const currentState=()=>loadState().state;

function ensureUi(){
  if(!document.querySelector('#scenarioLibraryBtn')){
    const b=document.createElement('button');b.id='scenarioLibraryBtn';b.className='new-scenario-btn';b.type='button';b.textContent='Scenario Library';b.title='Open scenarios published with Battle Axe';
    const open=document.querySelector('#openProjectBtn');if(open)open.after(b);
  }
  if(!document.querySelector('#scenarioLibraryDialog')){
    const d=document.createElement('dialog');d.id='scenarioLibraryDialog';d.innerHTML=`<div class="dialog-card bax-library-dialog"><div class="dialog-heading"><div><p class="eyebrow">Published & playtest scenarios</p><h2>Scenario Library</h2></div><button id="closeScenarioLibrary" class="icon-button" aria-label="Close">✕</button></div><p class="muted">These scenarios live with the Battle Axe site. Loading one uses the same project migration/validation path as Open Project. JSON remains the portable canonical format.</p><div class="bax-library-tools"><input id="scenarioLibrarySearch" type="search" placeholder="Search battle, period, status…"><select id="scenarioLibraryStatus"><option value="">All statuses</option><option>Published</option><option>Playtest</option><option>Sample</option><option>Development</option></select><button id="refreshScenarioLibrary" class="secondary compact">Refresh</button></div><div id="scenarioLibraryStatusText" class="help">Library not loaded yet.</div><div id="scenarioLibraryList" class="bax-library-list"></div></div>`;document.body.appendChild(d);
  }
}

export function setupScenarioLibrary({studioVersion='0.6.9.0'}={}){
  ensureUi();const dialog=document.querySelector('#scenarioLibraryDialog'),list=document.querySelector('#scenarioLibraryList'),status=document.querySelector('#scenarioLibraryStatusText'),search=document.querySelector('#scenarioLibrarySearch'),filter=document.querySelector('#scenarioLibraryStatus');let catalog=[];
  const setStatus=t=>{if(status)status.textContent=t;};
  function render(){const q=String(search?.value||'').toLowerCase().trim(),f=String(filter?.value||'').toLowerCase();const rows=catalog.filter(x=>(!f||String(x.status||'').toLowerCase()===f)&&(!q||[x.title,x.date,x.location,x.period,x.supplement,x.status,x.description].some(v=>String(v||'').toLowerCase().includes(q))));if(!rows.length){list.innerHTML='<div class="notice"><strong>No matching scenarios.</strong><br>The catalog can be expanded by adding scenario JSON files under /scenarios and registering them in scenarios/index.json.</div>';return;}list.innerHTML=rows.map(x=>`<article class="bax-library-card"><header><div><p class="eyebrow">${esc(x.period||x.supplement||'Battle Axe')}</p><h3>${esc(x.title||x.id)}</h3></div><span class="count-pill">${esc(x.status||'Published')}</span></header><p>${esc(x.description||'')}</p><dl><div><dt>Date</dt><dd>${esc(x.date||'—')}</dd></div><div><dt>Location</dt><dd>${esc(x.location||'—')}</dd></div><div><dt>Table</dt><dd>${esc(x.tableSize||'—')}</dd></div></dl><div class="button-row"><button class="primary compact" data-library-load="${esc(x.id)}">Load scenario</button>${x.version?`<small>Scenario ${esc(x.version)}</small>`:''}</div></article>`).join('');list.querySelectorAll('[data-library-load]').forEach(b=>b.addEventListener('click',()=>loadEntry(catalog.find(x=>x.id===b.dataset.libraryLoad))));}
  async function refresh(){setStatus('Loading scenario catalog…');try{const url=new URL(`./scenarios/index.json?v=${encodeURIComponent(studioVersion)}`,document.baseURI),r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`catalog returned HTTP ${r.status}`);const data=await r.json();if(data.format!=='battle-axe-scenario-library'||!Array.isArray(data.scenarios))throw new Error('catalog format is not recognized');catalog=data.scenarios;setStatus(`${catalog.length} scenario${catalog.length===1?'':'s'} available · catalog ${data.version||'1.0'}`);render();}catch(error){catalog=[];setStatus(`Scenario Library unavailable: ${error.message}`);list.innerHTML='<div class="notice"><strong>Library could not be loaded.</strong><br>Open Project still works normally. If this is a local/offline copy, the site catalog may not be reachable.</div>';}}
  async function loadEntry(entry){if(!entry?.path)return;try{setStatus(`Loading ${entry.title||entry.id}…`);const url=new URL(entry.path,document.baseURI),r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`scenario returned HTTP ${r.status}`);const data=await r.json(),restoredBase=normalizeImportedState(data),migrated=migrateImportedProject(data),migration=migrated.migration;let restored=restoredBase,current=currentState();try{savePreImportBackup(current,window.localStorage,{studioVersion});}catch(error){console.warn('Scenario Library pre-import backup failed',error);}if(!migration?.capabilities?.containsBattlefield&&current.project?.mapSource){const keep=window.confirm(`“${entry.title||entry.id}” does not contain its own battlefield map/compiled terrain.\n\nPress OK to keep the currently loaded battlefield while importing this scenario.\nPress Cancel to load the scenario without the current battlefield.`);if(keep){restored=mergeImportedScenarioWithCurrentBattlefield(restored,current);migration.warnings.push('Scenario Library entry contained no battlefield; retained current authoritative battlefield/terrain workspace.');}}
      saveState(restored);sessionStorage.setItem('bax-import-migration-note',`Loaded Scenario Library entry “${entry.title||entry.id}” through the normal migration/validation path (${migration.sourceVersion}). ${[...(migration.steps||[]),...(migration.warnings||[])].join(' ')}`);window.location.reload();
    }catch(error){setStatus(`Could not load scenario: ${error.message}`);}}
  document.querySelector('#scenarioLibraryBtn')?.addEventListener('click',()=>{dialog.showModal();refresh();});document.querySelector('#closeScenarioLibrary')?.addEventListener('click',()=>dialog.close());document.querySelector('#refreshScenarioLibrary')?.addEventListener('click',refresh);search?.addEventListener('input',render);filter?.addEventListener('change',render);return{open:()=>{dialog.showModal();refresh();},refresh};
}
