import { createBlankScenario } from '../data/scenarioData.js?v=0.6.8.0';
import { createProjectExportPayload } from '../app/state.js?v=0.6.8.0';
import { getEffectiveRuleset, listSupplements, ensureScenarioRuleset, effectiveArmyAssetPolicy } from '../rules/ruleset.js?v=0.6.8.0';
import { analyzeScenarioText, proposedRosterUnits } from './scenarioAnalyzer.js?v=0.6.8.0';
import { SIDE_KEYS, registerEvidenceSides, sideForFaction, sideLabel, ensureTwoSideModel } from './scenarioSides.js?v=0.6.8.0';
import { normalizeCommandHierarchy, reparentCommand, removeCommand, wouldCreateCommandCycle } from './commandHierarchy.js?v=0.6.8.0';

const $=s=>document.querySelector(s);
const safe=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;

export function setupScenarioBuilder(state,persist){
  const scenario=()=>state.project.scenario;
  ensureTwoSideModel(scenario());
  let editingUnit=null,editingSuggestion=null,stagedText='';
  const forceUndoStack=[],forceRedoStack=[];
  const canonicalSide=faction=>SIDE_KEYS.includes(faction)?faction:(sideForFaction(scenario(),faction,{assign:true})||'French');

  function allUnits(){return Object.values(scenario().commands||{}).flatMap(cmds=>cmds.flatMap(c=>c.units||[]));}
  function forceSnapshot(){return{commands:structuredClone(scenario().commands||{}),deployment:structuredClone(scenario().deployment||{})};}
  function updateForceHistoryButtons(){const u=$('#forceUndo'),r=$('#forceRedo');if(u)u.disabled=!forceUndoStack.length;if(r)r.disabled=!forceRedoStack.length;}
  function checkpointForces(){forceUndoStack.push(forceSnapshot());if(forceUndoStack.length>40)forceUndoStack.shift();forceRedoStack.length=0;updateForceHistoryButtons();}
  function restoreForceSnapshot(snap){scenario().commands=structuredClone(snap.commands||{});scenario().deployment=structuredClone(snap.deployment||{});normalizeCommandHierarchy(scenario());persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderForces();updateForceHistoryButtons();}
  function undoForces(){if(!forceUndoStack.length)return;forceRedoStack.push(forceSnapshot());restoreForceSnapshot(forceUndoStack.pop());}
  function redoForces(){if(!forceRedoStack.length)return;forceUndoStack.push(forceSnapshot());restoreForceSnapshot(forceRedoStack.pop());}
  function ensureCommand(faction,name,commander='',options={}){
    const side=canonicalSide(faction),cmds=scenario().commands[side]||(scenario().commands[side]=[]),label=sideLabel(scenario(),side);
    let c=options.sourceId?cmds.find(x=>x.sourceId===options.sourceId):cmds.find(x=>x.name===name&&((x.parentCommandId||null)===(options.parentCommandId||null)));
    const commandType=options.commandType||options.echelon||'command';
    if(!c){c={id:options.id||uid('command'),sourceId:options.sourceId||null,name:name||`${label} Command ${cmds.length+1}`,commander:commander||'',commandType,echelon:commandType,parentCommandId:options.parentCommandId||null,commandRating:options.commandRating??null,status:options.status||'',role:options.role||'',notes:[...(options.notes||[])],units:[]};cmds.push(c);}else{if(!c.commander&&commander)c.commander=commander;if(options.commandType||options.echelon){c.commandType=commandType;c.echelon=commandType;}if(options.parentCommandId!==undefined)c.parentCommandId=options.parentCommandId||null;if(options.commandRating!=null)c.commandRating=options.commandRating;if(options.status)c.status=options.status;if(options.role)c.role=options.role;if(options.notes?.length)c.notes=[...new Set([...(c.notes||[]),...options.notes])];}
    normalizeCommandHierarchy(scenario());return c;
  }
  function findCommand(faction,id){const side=canonicalSide(faction);return (scenario().commands[side]||[]).find(c=>c.id===id);}

  function ruleset(){return getEffectiveRuleset(scenario());}
  function unitLibrary(){return ruleset().unitLibrary;}
  function commandRatingRules(){return ruleset().supplement.commandRules?.mode==='rating-proximity'?ruleset().supplement.commandRules:null;}
  function normalizeCommandRating(value){if(value==null||String(value).trim()==='')return null;const n=Number(value),r=commandRatingRules();return Number.isFinite(n)&&r?Math.max(Number(r.ratingMin??0),Math.min(Number(r.ratingMax??3),Math.round(n))):null;}
  function supplementForceIssues(){
    const rs=ruleset(),fs=rs.supplement.forceStructure;
    if(!fs)return[];
    const issues=[];
    for(const [side,cmds] of Object.entries(scenario().commands||{})){
      const armyUnits=(cmds||[]).flatMap(c=>c.units||[]);
      for(const [profile,max] of Object.entries(fs.armyMax||{})){
        const count=armyUnits.filter(u=>u.profile===profile).length;
        if(count>Number(max))issues.push(['error',`${sideLabel(scenario(),side)} has ${count} ${profile} units; ${rs.supplement.name} allows at most ${max}.`]);
      }
      for(const c of cmds||[]){
        const units=c.units||[];
        if(!units.length)continue;
        if(!c.commander)issues.push(['warning',`${c.name} has no commander; ${rs.supplement.name} brigades include a commander.`]);
        const cavalry=units.filter(u=>u.profile==='Cavalry').length;
        const infantry=units.filter(u=>u.profile==='Infantry').length;
        const kind=cavalry&&!infantry?'cavalry-brigade':'infantry-brigade';
        const rule=(fs.brigadeTypes||[]).find(x=>x.id===kind);
        if(!rule)continue;
        const primary=units.filter(u=>u.profile===rule.primaryProfile).length;
        if(primary<rule.primaryMin||primary>rule.primaryMax)issues.push(['warning',`${c.name} has ${primary} ${rule.primaryProfile} units; ${rule.name} expects ${rule.primaryMin}–${rule.primaryMax}.`]);
        for(const [profile,max] of Object.entries(rule.optionalMax||{})){
          const count=units.filter(u=>u.profile===profile).length;
          if(count>Number(max))issues.push(['warning',`${c.name} has ${count} ${profile} units; ${rule.name} allows up to ${max}.`]);
        }
        const allowed=new Set([rule.primaryProfile,...Object.keys(rule.optionalMax||{})]);
        const other=units.filter(u=>!allowed.has(u.profile));
        if(other.length)issues.push(['warning',`${c.name} mixes profiles outside the normal ${rule.name}: ${[...new Set(other.map(u=>u.profile))].join(', ')}.`]);
      }
    }
    return issues;
  }

  function ensureTabletop(){const s=scenario(),legacy=Number(s.tabletop?.unitBaseMm||50);s.tabletop={preset:'double',unitBaseMm:legacy,unitBaseWidthMm:legacy,unitBaseDepthMm:legacy,commanderBaseMm:25,measurementMultiplier:2,...(s.tabletop||{})};s.tabletop.unitBaseWidthMm=Number(s.tabletop.unitBaseWidthMm||legacy);s.tabletop.unitBaseDepthMm=Number(s.tabletop.unitBaseDepthMm||legacy);s.tabletop.unitBaseMm=Number(s.tabletop.unitBaseMm||s.tabletop.unitBaseWidthMm);return s.tabletop;}
  function renderTabletop(){const x=ensureTabletop();$('#tabletopPreset').value=x.preset||'custom';$('#unitBaseWidthMm').value=x.unitBaseWidthMm;$('#unitBaseDepthMm').value=x.unitBaseDepthMm;$('#commanderBaseMm').value=x.commanderBaseMm;$('#measurementMultiplier').value=x.measurementMultiplier;$('#tabletopScaleSummary').textContent=`${x.unitBaseWidthMm}×${x.unitBaseDepthMm} mm · ${x.commanderBaseMm} mm · ${x.measurementMultiplier}×`;}
  function saveTabletop(){const x=ensureTabletop(),preset=$('#tabletopPreset').value;if(preset==='original')Object.assign(x,{preset,unitBaseMm:25,unitBaseWidthMm:25,unitBaseDepthMm:25,commanderBaseMm:15,measurementMultiplier:1});else if(preset==='double')Object.assign(x,{preset,unitBaseMm:50,unitBaseWidthMm:50,unitBaseDepthMm:50,commanderBaseMm:25,measurementMultiplier:2});else if(preset==='acw-regiment')Object.assign(x,{preset,unitBaseMm:50,unitBaseWidthMm:50,unitBaseDepthMm:25,commanderBaseMm:25,measurementMultiplier:1});else{const width=Number($('#unitBaseWidthMm').value||50),depth=Number($('#unitBaseDepthMm').value||width);Object.assign(x,{preset:'custom',unitBaseMm:width,unitBaseWidthMm:width,unitBaseDepthMm:depth,commanderBaseMm:Number($('#commanderBaseMm').value||25),measurementMultiplier:Number($('#measurementMultiplier').value||1)});}renderTabletop();persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));}
  function renderRuleInspector(){const accepted=(scenario().suggestions||[]).filter(x=>x.status==='accepted');$('#rulesInterpretationInspector').innerHTML=accepted.length?accepted.map(x=>`<div class="rule-inspect"><strong>${safe(x.title)}</strong><span>${safe(x.engineStatus||'tabletop')}</span><p>${safe(x.engineText||'No automated engine interpretation supplied.')}</p>${x.overrides?`<small>Overrides: ${safe(x.overrides)}</small>`:''}</div>`).join(''):'<p class="muted">No accepted scenario rules.</p>';}
  function validateScenario(){const s=scenario(),issues=[],units=allUnits(),placed=s.deployment?.placements||{};if(!s.metadata?.title)issues.push(['warning','Scenario title is blank.']);if(!units.length)issues.push(['error','No Battle Axe units are in the force lists.']);for(const [side,cmds] of Object.entries(s.commands||{}))for(const c of cmds||[]){const reserve=!!c.reserve?.enabled;for(const u of c.units||[])if(!placed[u.id]&&!reserve)issues.push(['warning',`${u.name} is not deployed.`]);if(c.commander&&!s.deployment?.commanderPlacements?.[c.id]&&!reserve)issues.push(['warning',`${c.commander} (${side}) is not deployed.`]);if(reserve&&!(Number(c.reserve?.deploymentTurn)>0))issues.push(['warning',`${c.name} is a reserve command but has no valid deployment turn.`]);}for(const r of (s.suggestions||[]).filter(x=>x.status==='accepted'&&x.engineStatus==='automated'))if(!r.engineText?.trim())issues.push(['error',`${r.title} is marked automated but has no Engine Interpretation.`]);const tt=ensureTabletop();if(!(tt.unitBaseWidthMm>0&&tt.unitBaseDepthMm>0&&tt.commanderBaseMm>0&&tt.measurementMultiplier>0))issues.push(['error','Tabletop scale contains an invalid value.']);issues.push(...supplementForceIssues());$('#scenarioValidationReport').innerHTML=issues.length?issues.map(([k,m])=>`<div class="validation-item ${k}"><strong>${k==='error'?'Needs attention':'Check'}</strong> ${safe(m)}</div>`).join(''):'<div class="validation-item ok"><strong>Ready:</strong> no basic configuration problems found.</div>';return issues;}

  function tabs(){document.querySelectorAll('.scenario-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.scenario-tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.scenario-pane').forEach(p=>p.classList.toggle('active',p.id===`scenario-${b.dataset.scenarioTab}`));if(b.dataset.scenarioTab==='forces')renderForces();if(b.dataset.scenarioTab==='summary')renderSummary();}));}
  function activateTab(name){document.querySelector(`.scenario-tab[data-scenario-tab="${name}"]`)?.click();}

  async function addFiles(files){const s=scenario();for(const file of files){const rec={id:uid('source'),name:file.name,type:file.type||'unknown',size:file.size,status:'registered',textExtracted:false};const ext=file.name.toLowerCase().split('.').pop();if(['txt','md','json','csv'].includes(ext)){try{const text=await file.text();rec.textExtracted=true;rec.status='text extracted';rec.text=text.slice(0,250000);stagedText+=`\n\n${text}`;}catch{rec.status='read failed';}}else rec.status='registered — visual/binary extraction pending';s.sources.push(rec);}persist();renderSources();}
  function renderRuleset(){ensureScenarioRuleset(scenario());const select=$('#scenarioSupplementSelector'),rs=ruleset();if(select)select.innerHTML=listSupplements().map(x=>`<option value="${safe(x.id)}" ${x.id===rs.supplement.id?'selected':''}>${safe(x.name)}</option>`).join('');if($('#scenarioRulesetSummary')){const basing=rs.supplement.recommendedTabletop?` Suggested Studio basing: ${rs.supplement.recommendedTabletop.unitBaseWidthMm}×${rs.supplement.recommendedTabletop.unitBaseDepthMm} mm (${safe(rs.supplement.recommendedTabletop.note||'optional')}).`:'';$('#scenarioRulesetSummary').innerHTML=`<strong>${safe(rs.core.name)}</strong> + <strong>${safe(rs.supplement.name)}</strong><br><span class="muted">Effective order: Core → Supplement → accepted scenario overrides. ${rs.unitLibrary.length} period profiles loaded.${rs.supplement.aiDoctrine?.name?` Tactical AI: ${safe(rs.supplement.aiDoctrine.name)}.`:''}${basing}</span>`;}if($('#unitLibraryHelp'))$('#unitLibraryHelp').textContent=`Canonical ${rs.supplement.name} unit library. The selected supplement defines available profiles and period rules; imported sources influence suggestions, not the library.`;}

  function renderHistoricalRegister(){const host=$('#historicalExtractionRegister');if(!host)return;const sc=scenario(),rows=[...(sc.sourceCommands||[]).map(c=>({kind:'Commander / command evidence',name:c.commander||c.name,detail:c.sourceText||'',confidence:c.confidence||80,provenance:c.provenance||'SOURCE'})),...(sc.sourceForces||[]).map(f=>({kind:'Historical formation',name:f.name,detail:`${f.faction||'Side unresolved'}${f.strength?` · strength ${f.strength}`:''} · BA profile hint: ${f.profileHint||f.profile||'unresolved'}`,confidence:f.confidence||70,provenance:f.provenance||'SOURCE'}))];host.innerHTML=rows.length?rows.map(r=>`<div class="extraction-row"><div><strong>${safe(r.name)}</strong><small>${safe(r.kind)}</small></div><div><span class="provenance-tag">${safe(r.provenance)}</span><span class="confidence-badge">${r.confidence}%</span></div><p>${safe(r.detail)}</p></div>`).join(''):'<p class="muted">No historical evidence extracted yet.</p>';}

  function renderSources(){const s=scenario();$('#scenarioSourceList').innerHTML=s.sources.length?s.sources.map(x=>`<div class="source-item"><span><strong>${safe(x.name)}</strong><small>${safe(x.type)} · ${(x.size/1024).toFixed(1)} KB</small></span><span class="source-status ${x.textExtracted?'ok':'pending'}">${safe(x.status)}</span></div>`).join(''):'<p class="muted">No source documents registered yet.</p>';}

  function mergeAnalysis(a,sourceName){
    const s=scenario(),norm=x=>String(x||'').trim().toLowerCase().replace(/\s+/g,' '),commandIdMap=new Map(),forceIdMap=new Map(),incomingCommands=[];
    for(const [k,v] of Object.entries(a.metadata))if(v&&!s.metadata[k])s.metadata[k]=v;
    if(a.historicalSituation&&!s.historicalSituation)s.historicalSituation=a.historicalSituation;if(a.deploymentNotes&&!s.deploymentNotes)s.deploymentNotes=a.deploymentNotes;if(a.victoryText&&!s.victoryText)s.victoryText=a.victoryText;
    for(const o of a.observations)if(!s.observations.some(x=>x.field===o.field&&x.value===o.value))s.observations.push(o);
    // Re-analysis enriches existing evidence rather than leaving an older orphaned copy behind.
    // Keep stable Studio IDs where possible, but refresh hierarchy/commander fields from the newer parse.
    for(const c0 of a.sourceCommands||[]){const c={...c0,sourceName};let existing=(s.sourceCommands||[]).find(x=>x.id===c.id)|| (s.sourceCommands||[]).find(x=>norm(x.faction)===norm(c.faction)&&norm(x.name)===norm(c.name)&&norm(x.commander)===norm(c.commander));if(existing){const stableId=existing.id;Object.assign(existing,c,{id:stableId});commandIdMap.set(c0.id,stableId);incomingCommands.push(existing);}else{s.sourceCommands.push(c);commandIdMap.set(c0.id,c.id);incomingCommands.push(c);}}
    for(const f0 of a.forces||[]){const f={...f0,sourceName,commandId:commandIdMap.get(f0.commandId)||f0.commandId||null};let existing=(s.sourceForces||[]).find(x=>x.key===f.key)|| (s.sourceForces||[]).find(x=>norm(x.faction)===norm(f.faction)&&norm(x.name)===norm(f.name)&&norm(x.sourceText)===norm(f.sourceText));if(existing){const stableId=existing.id;Object.assign(existing,f,{id:stableId});forceIdMap.set(f0.id,stableId);}else{s.sourceForces.push(f);forceIdMap.set(f0.id,f.id);}}
    for(let i=0;i<(a.sourceCommands||[]).length;i++){const original=a.sourceCommands[i],actual=incomingCommands[i];if(!actual)continue;actual.formations=[...new Set((original.formations||[]).map(id=>forceIdMap.get(id)||id))];for(const fid of actual.formations){const f=s.sourceForces.find(x=>x.id===fid);if(f){f.commandId=actual.id;f.commandName=actual.name;f.commander=actual.commander||f.commander||'';f.armyCommander=actual.armyCommander||f.armyCommander||'';}}}
    registerEvidenceSides(s,s.sourceForces,s.sourceCommands);
    // Source-authored rules are scenario evidence, not optional AI suggestions. Preserve them as accepted editable rules.
    for(const rule of a.sourceRules||[]){const existing=s.suggestions.find(x=>x.id===rule.id);if(existing){const status=existing.status||'accepted',edited=existing.provenance==='SOURCE'&&existing._designerEdited;if(edited)Object.assign(existing,{evidence:rule.evidence,confidence:rule.confidence,status});else Object.assign(existing,{...rule,status});}else s.suggestions.push({...rule});}
    for(const sg of a.suggestions||[])if(!s.suggestions.some(x=>x.id===sg.id))s.suggestions.push(sg);
    if((a.sourceCommands||[]).length)s.unresolved=(s.unresolved||[]).filter(x=>!/command organization|subordinate command|command assignment/i.test(x));s.unresolved=[...new Set([...s.unresolved,...a.unresolved])];s.lastAnalysis={at:new Date().toISOString(),sourceName};
  }
  function analyze(text,name='Scenario intake'){if(!text.trim())return;mergeAnalysis(analyzeScenarioText(text,{sourceName:name,ruleset:ruleset()}),name);persist();renderAllScenario();activateTab('review');}

  function renderReview(){const s=scenario(),unresolved=s.unresolved.length;$('#scenarioReviewStatus').textContent=s.lastAnalysis?`${s.observations.length} observations`:'Not analyzed';$('#scenarioReviewSummary').innerHTML=s.lastAnalysis?`<div class="intake-metrics"><span><b>${s.sourceCommands.length}</b> source commands</span><span><b>${s.sourceForces.length}</b> formations</span><span><b>${unresolved}</b> unresolved</span></div>`:'<p class="muted">Analyze a source to populate the scenario.</p>';$('#sourceObservations').innerHTML=s.observations.length?s.observations.map(o=>`<div class="observation"><div><strong>${safe(o.field)}</strong><span class="confidence-badge">${o.confidence}%</span></div><p>${safe(o.value)}</p><small>Source: ${safe(o.sourceName)}</small></div>`).join(''):'<p class="muted">No extracted observations yet.</p>';$('#scenarioTitle').value=s.metadata.title||'';$('#scenarioDate').value=s.metadata.date||'';$('#scenarioLocation').value=s.metadata.location||'';$('#scenarioGameLength').value=s.metadata.gameLength||'';$('#scenarioTableSize').value=s.metadata.tableSize||'';$('#scenarioStatus').value=s.metadata.status||'';$('#scenarioSituation').value=s.historicalSituation||'';$('#scenarioDeployment').value=s.deploymentNotes||'';$('#scenarioVictory').value=s.victoryText||'';}
  function saveFields(){const s=scenario();s.metadata={title:$('#scenarioTitle').value,date:$('#scenarioDate').value,location:$('#scenarioLocation').value,gameLength:$('#scenarioGameLength').value,status:$('#scenarioStatus').value,tableSize:$('#scenarioTableSize').value};s.historicalSituation=$('#scenarioSituation').value;s.deploymentNotes=$('#scenarioDeployment').value;s.victoryText=$('#scenarioVictory').value;persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderSummary();renderChecklist();renderRuleInspector();}

  function renderSuggestions(){const s=scenario(),visible=s.suggestions.filter(x=>x.status!=='ignored');$('#suggestionCount').textContent=visible.filter(x=>x.status==='pending').length;$('#suggestionTray').innerHTML=visible.length?visible.map(x=>`<article class="suggestion-card ${x.status}"><div class="suggestion-head"><div><span class="suggestion-type">${safe(x.type)}</span><h4>${safe(x.title)}</h4></div><label class="include-toggle"><input type="checkbox" data-suggestion-include="${x.id}" ${x.status==='accepted'?'checked':''}> Include</label></div><p class="proposal-text">${safe(x.proposal)}</p><p class="evidence-text"><strong>Evidence:</strong> ${safe(x.evidence)}</p><div class="suggestion-foot"><span>Confidence ${x.confidence}%</span><div><button class="link-button" data-suggestion-edit="${x.id}">Edit</button> <button class="link-button" data-suggestion-ignore="${x.id}">Ignore</button></div></div></article>`).join(''):'<p class="muted">No Studio suggestions yet.</p>';const ignored=s.suggestions.filter(x=>x.status==='ignored');$('#ignoredSuggestionCount').textContent=ignored.length;$('#ignoredSuggestions').innerHTML=ignored.map(x=>`<div class="ignored-suggestion"><span>${safe(x.title)}</span><button class="link-button" data-suggestion-restore="${x.id}">Restore</button></div>`).join('');document.querySelectorAll('[data-suggestion-include]').forEach(el=>el.addEventListener('change',()=>{const x=s.suggestions.find(y=>y.id===el.dataset.suggestionInclude);x.status=el.checked?'accepted':'pending';persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderSuggestions();}));document.querySelectorAll('[data-suggestion-ignore]').forEach(el=>el.addEventListener('click',()=>{const x=s.suggestions.find(y=>y.id===el.dataset.suggestionIgnore);x.status='ignored';persist();renderSuggestions();}));document.querySelectorAll('[data-suggestion-restore]').forEach(el=>el.addEventListener('click',()=>{const x=s.suggestions.find(y=>y.id===el.dataset.suggestionRestore);x.status='pending';persist();renderSuggestions();}));document.querySelectorAll('[data-suggestion-edit]').forEach(el=>el.addEventListener('click',()=>openSuggestionEditor(el.dataset.suggestionEdit)));}
  function openSuggestionEditor(id){const x=scenario().suggestions.find(y=>y.id===id);if(!x)return;editingSuggestion=id;$('#ruleEditorName').value=x.title;$('#ruleEditorText').value=x.proposal;$('#ruleEditorEvidence').textContent=x.evidence||'Designer-created rule';$('#ruleEditorConfidence').textContent=`${x.confidence??100}%`;$('#ruleEngineStatus').value=x.engineStatus||'tabletop';$('#ruleOverrides').value=x.overrides||'';$('#ruleEngineText').value=x.engineText||'';$('#ruleEditorDialog').showModal();}
  function saveSuggestion(){const x=scenario().suggestions.find(y=>y.id===editingSuggestion);if(!x)return;if(x.provenance==='SOURCE')x._designerEdited=true;x.title=$('#ruleEditorName').value.trim()||x.title;x.proposal=$('#ruleEditorText').value.trim();x.engineStatus=$('#ruleEngineStatus').value;x.overrides=$('#ruleOverrides').value.trim();x.engineText=$('#ruleEngineText').value.trim();x.status='accepted';persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed')); $('#ruleEditorDialog').close();renderSuggestions();}

  function addManualRule(){const s=scenario();const id=uid('rule');s.suggestions.push({id,type:'SCENARIO RULE',title:'New scenario rule',proposal:'',evidence:'Designer-created rule. No source evidence required.',confidence:100,status:'pending',provenance:'designer',engineStatus:'tabletop',engineText:'',overrides:''});editingSuggestion=id;openSuggestionEditor(id);}

  function sourceDotClass(faction){return (sideForFaction(scenario(),faction,{assign:false})||'French').toLowerCase();}
  function sourceFormationCard(f){return `<div class="source-force-card"><span class="faction-dot ${sourceDotClass(f.faction)}"></span><div><strong>${safe(f.name)}</strong><small>${safe(f.faction||'Side unresolved')} · ${safe(f.profileHint||f.profile||'profile unresolved')}</small><p><strong>Historical note:</strong> ${safe(f.historicalNote||f.sourceText)}</p><small class="source-evidence">Source evidence: ${safe(f.sourceText)}</small></div></div>`;}
  function sourceCommandCard(c){const formations=(c.formations||[]).map(id=>scenario().sourceForces.find(f=>f.id===id)).filter(Boolean);return `<details class="source-command-card" open><summary><span><strong>${safe(c.name)}</strong><small>${safe(c.faction||'Side unresolved')} · Commander: ${safe(c.commander||'Not identified')} · Army commander: ${safe(c.armyCommander||'Not identified')}</small></span><span class="count-pill">${formations.length}</span></summary><div class="source-command-body">${formations.length?formations.map(sourceFormationCard).join(''):'<p class="muted">Command relationship is unresolved; formations remain listed separately below.</p>'}</div></details>`;}
  function renderSourceForces(){const s=scenario(),host=$('#sourceForceList');if(!host)return;$('#sourceForceCount').textContent=s.sourceForces.length;host.innerHTML='<p class="muted">Historical source evidence is retained in Extraction Review. Force Builder focuses on the proposed OOB and canonical Battle Axe unit library.</p>';const sourcePanel=host.parentElement,plan=$('#suggestedForcePlan'),library=$('#unitLibrary');if(sourcePanel&&!sourcePanel.contains(plan)&&!sourcePanel.contains(library)){const layout=sourcePanel.parentElement;if(layout&&layout.contains(plan)&&layout.contains(library)){sourcePanel.style.display='none';if(getComputedStyle(layout).display==='grid'){layout.style.gridTemplateColumns='minmax(0,2fr) minmax(300px,1fr)';layout.style.alignItems='start';}}}}


  function unitFootprint(u){const tt=ensureTabletop(),base=unitLibrary().find(x=>x.profile===u.profile)||{},scenarioLegacy=Number(tt.unitBaseMm||50),fixed=!!base.asset&&Number(base.baseMm)>0,legacy=Number(fixed?base.baseMm:scenarioLegacy),profileWidth=Number(base.baseWidthMm||(fixed?legacy:(tt.unitBaseWidthMm||legacy))),profileDepth=Number(base.baseDepthMm||(fixed?legacy:(tt.unitBaseDepthMm||legacy)));return{width:Number(u.baseWidthMm||profileWidth),depth:Number(u.baseDepthMm||profileDepth)};}
  function unitCard(u,faction,commandId){const card=document.createElement('div');card.className='unit-card';card.draggable=true;card.dataset.unitId=u.id;const base=unitLibrary().find(x=>x.profile===u.profile),fp=unitFootprint(u);card.innerHTML=`<button type="button" class="unit-card-delete" data-delete-unit="${u.id}" title="Delete ${safe(u.name)}" aria-label="Delete ${safe(u.name)}">×</button><div class="unit-card-top"><strong>${safe(u.name)}</strong><span>${safe(u.profile)}</span></div><small>${safe(u.represents||'No historical link yet')} · ${fp.width}×${fp.depth} mm</small>${base?`<div class="unit-stats"><span>M ${base.m}</span><span>C ${base.c}</span><span>A ${base.a}</span><span>${base.pts} pts</span></div>`:''}<div class="trait-chips">${(u.traits||[]).map(t=>`<span>${safe(t)}</span>`).join('')}</div>`;card.addEventListener('click',e=>{if(e.target.closest('[data-delete-unit]'))return;openUnitEditor(faction,commandId,u.id);});card.querySelector('[data-delete-unit]')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();deleteUnitById(faction,commandId,u.id);});card.addEventListener('dragstart',e=>{e.stopPropagation();e.dataTransfer.setData('application/x-bax-roster',JSON.stringify({unitId:u.id,fromFaction:faction,fromCommand:commandId}));});return card;}
  function startCommandDrag(e,faction,c){e.stopPropagation();e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('application/x-bax-command',JSON.stringify({commandId:c.id,faction}));}
  function moveCommandInTree(faction,commandId,parentCommandId){const side=canonicalSide(faction);if(parentCommandId===commandId||wouldCreateCommandCycle(scenario(),commandId,parentCommandId)){alert('A command cannot be dropped onto itself or one of its subordinate commands.');return;}checkpointForces();try{reparentCommand(scenario(),side,commandId,parentCommandId||null);}catch(err){forceUndoStack.pop();updateForceHistoryButtons();alert(err.message);return;}persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderForces();}
  function commandCard(faction,c,depth=0,childrenMap=new Map()){const shell=document.createElement('section');shell.className='command-card';shell.dataset.commandId=c.id;const parent=(scenario().commands[faction]||[]).find(x=>x.id===c.parentCommandId),reserve=c.reserve?.enabled?` · RESERVE T${safe(c.reserve.deploymentTurn||'?')}`:'',type=c.commandType||c.echelon||'command';shell.innerHTML=`<div class="command-head" draggable="true" title="Drag this command onto another command to make it subordinate"><div><span class="command-drag-handle" aria-hidden="true">⋮⋮</span><strong>${safe(c.name)}</strong><small>${safe(type)}${parent?` · under ${safe(parent.name)}`:''} · Commander: ${safe(c.commander||'Unassigned')}${commandRatingRules()?` · CR ${c.commandRating==null?'auto':safe(c.commandRating)}`:''}${reserve}</small></div><div class="command-actions"><button class="link-button" data-edit-command="${c.id}">Edit</button><button class="link-button danger-text" data-delete-command="${c.id}">Delete</button></div></div><div class="command-dropzone" data-faction="${faction}" data-command="${c.id}"><small class="drop-hint">Drop Battle Axe units here</small></div><div class="command-children" data-command-children="${c.id}"></div>`;const head=shell.querySelector('.command-head'),zone=shell.querySelector('.command-dropzone'),childrenHost=shell.querySelector('.command-children');head.addEventListener('dragstart',e=>startCommandDrag(e,faction,c));shell.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('application/x-bax-command')){e.preventDefault();shell.classList.add('command-drag-over');}});shell.addEventListener('dragleave',e=>{if(!shell.contains(e.relatedTarget))shell.classList.remove('command-drag-over');});shell.addEventListener('drop',e=>{const raw=e.dataTransfer.getData('application/x-bax-command');if(!raw)return;e.preventDefault();e.stopPropagation();shell.classList.remove('command-drag-over');const d=JSON.parse(raw);if(d.faction!==faction){alert('Commands cannot be assigned across opposing sides.');return;}moveCommandInTree(faction,d.commandId,c.id);});for(const u of c.units||[])zone.appendChild(unitCard(u,faction,c.id));shell.querySelector('[data-edit-command]').addEventListener('click',e=>{e.stopPropagation();editCommand(faction,c.id);});shell.querySelector('[data-delete-command]').addEventListener('click',e=>{e.stopPropagation();deleteCommandById(faction,c.id);});setupZone(zone);for(const child of childrenMap.get(c.id)||[])childrenHost.appendChild(commandCard(faction,child,depth+1,childrenMap));return shell;}
  function renderRosterSide(faction){const host=$(`#roster${faction}`);host.innerHTML='';const cmds=scenario().commands[faction]||[];const root=document.createElement('div');root.className='command-root-dropzone';root.textContent='Drop a command here to make it top-level';root.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('application/x-bax-command')){e.preventDefault();root.classList.add('drag-over');}});root.addEventListener('dragleave',()=>root.classList.remove('drag-over'));root.addEventListener('drop',e=>{const raw=e.dataTransfer.getData('application/x-bax-command');if(!raw)return;e.preventDefault();root.classList.remove('drag-over');const d=JSON.parse(raw);if(d.faction!==faction){alert('Commands cannot be moved across opposing sides.');return;}moveCommandInTree(faction,d.commandId,null);});host.appendChild(root);if(!cmds.length){host.insertAdjacentHTML('beforeend','<p class="muted">No final commands yet. Create a command, then drag commands onto one another to build the hierarchy and drag canonical Battle Axe units into their commands.</p>');return;}const byParent=new Map();for(const c of cmds){const p=c.parentCommandId||'root';if(!byParent.has(p))byParent.set(p,[]);byParent.get(p).push(c);}for(const list of byParent.values())list.sort((a,b)=>String(a.name).localeCompare(String(b.name)));for(const c of byParent.get('root')||[])host.appendChild(commandCard(faction,c,0,byParent));}
  function forcePlanTree(){
    const s=scenario(),proposed=proposedRosterUnits(s.sourceForces||[],ruleset()),bySource=new Map(),byId=new Map(),children=new Map(),used=new Set();
    for(const list of Object.values(proposed))for(const p of list)bySource.set(p.sourceId,p);
    for(const c of s.sourceCommands||[])byId.set(c.id,{...c,side:sideForFaction(s,c.faction,{assign:true}),formations:[]});
    for(const node of byId.values()){const ids=new Set(node.formations||[]);node.formations=(s.sourceForces||[]).filter(f=>ids.has(f.id)).map(f=>{used.add(f.id);return{source:f,proposal:bySource.get(f.id)||null};});if(node.parentCommandId&&byId.has(node.parentCommandId)){if(!children.has(node.parentCommandId))children.set(node.parentCommandId,[]);children.get(node.parentCommandId).push(node);}}
    const roots=SIDE_KEYS.reduce((o,x)=>(o[x]=[],o),{});for(const node of byId.values())if(!node.parentCommandId||!byId.has(node.parentCommandId))roots[node.side]?.push(node);
    const remaining=(s.sourceForces||[]).filter(f=>!used.has(f.id));for(const f of remaining){const side=sideForFaction(s,f.faction,{assign:true});let unresolved=roots[side].find(x=>x.id===`unresolved-${side}`);if(!unresolved){unresolved={id:`unresolved-${side}`,side,name:'Command organization unresolved',commander:'',armyCommander:'',hierarchyLevel:'unresolved',formations:[]};roots[side].push(unresolved);}unresolved.formations.push({source:f,proposal:bySource.get(f.id)||null});}
    const sortNodes=list=>list.sort((a,b)=>{const weight=x=>x.hierarchyLevel==='command'?0:x.hierarchyLevel==='division'?1:x.hierarchyLevel==='brigade'?2:x.hierarchyLevel==='artillery'?3:4;return weight(a)-weight(b)||String(a.name).localeCompare(String(b.name));});for(const k of Object.keys(roots))sortNodes(roots[k]);for(const list of children.values())sortNodes(list);
    return{roots,children};
  }
  // Compatibility name retained for older release-contract tests; the implementation is now a true hierarchical tree.
  function forcePlanGroups(){return forcePlanTree();}
  function forcePlanSymbol(profile){const item=unitLibrary().find(x=>x.profile===profile);return item?.icon||'▪';}
  function renderForceFormation({source,proposal}){const profile=proposal?.profile||source.profileHint||'Review profile';return `<li title="${safe(source.strength?`Historical strength: ${source.strength}${source.forceRole?` · ${source.forceRole}`:''}`:(source.forceRole||'Historical formation'))}"><span class="force-sketch-bullet">${forcePlanSymbol(profile)}</span><span><b>${safe(source.name)}</b><em>→</em><button type="button" class="force-sketch-profile" data-find-profile="${safe(profile==='Review profile'?'':profile)}">${safe(profile)}</button></span></li>`;}
  function renderForceCommand(node,children,depth=0){const childNodes=children.get(node.id)||[],hasContent=node.formations?.length||childNodes.length,unresolved=!hasContent;return `<section class="force-sketch-command force-tree-node ${unresolved?'unresolved':''} ${node.formations?.length>5?'dense':''}" data-depth="${depth}"><div class="force-sketch-command-title"><strong>${safe(node.name||'Suggested command')}</strong><span>${node.commander?safe(node.commander):node.hierarchyLevel==='artillery'?'Division artillery':'Commander unresolved'}</span></div>${node.formations?.length?`<ul>${node.formations.map(renderForceFormation).join('')}</ul>`:unresolved?'<ul><li class="empty">Regimental composition unresolved from source; no Battle Axe units invented.</li></ul>':''}${childNodes.length?`<div class="force-sketch-children">${childNodes.map(c=>renderForceCommand(c,children,depth+1)).join('')}</div>`:''}</section>`;}
  function renderForcePlan(){
    const host=$('#suggestedForcePlan');if(!host)return;host.style.display='grid';host.style.gridTemplateColumns='1fr';host.style.gap='14px';const tree=forcePlanGroups(),hasAny=SIDE_KEYS.some(side=>(tree.roots[side]||[]).length);
    if(!hasAny){host.innerHTML='<p class="muted">No historical formations are available yet. Analyze the scenario brief first.</p>';return;}
    host.innerHTML=SIDE_KEYS.map(side=>{const roots=tree.roots[side]||[],armyCommanders=[...new Set(roots.flatMap(r=>[r.armyCommander]).filter(Boolean))],armyCommander=armyCommanders.length===1?armyCommanders[0]:'';return `<figure class="force-sketch ${side.toLowerCase()}"><figcaption><strong>${safe(sideLabel(scenario(),side))}</strong>${armyCommander?`<span>${safe(armyCommander)}</span>`:'<span>Suggested historical command structure</span>'}</figcaption><div class="force-sketch-trunk"></div><div class="force-sketch-commands force-sketch-tree">${roots.length?roots.map(r=>renderForceCommand(r,tree.children,0)).join(''):'<section class="force-sketch-command unresolved"><div class="force-sketch-command-title"><strong>No source formations extracted</strong><span>Review the source or re-run analysis with the correct supplement.</span></div></section>'}</div></figure>`;}).join('');
    host.querySelectorAll('[data-find-profile]').forEach(b=>b.addEventListener('click',()=>{const profile=b.dataset.findProfile||'';if(!profile)return;$('#unitLibrarySearch').value=profile;renderLibrary();const first=$('#unitLibrary .library-card');first?.scrollIntoView({behavior:'smooth',block:'center'});first?.classList.add('library-highlight');setTimeout(()=>first?.classList.remove('library-highlight'),1400);}));
  }

  function renderForces(){ensureTwoSideModel(scenario());registerEvidenceSides(scenario(),scenario().sourceForces||[],scenario().sourceCommands||[]);normalizeCommandHierarchy(scenario());renderSourceForces();renderForcePlan();for(const side of SIDE_KEYS){const label=document.querySelector(`#roster${side}Label`);if(label)label.textContent=sideLabel(scenario(),side);renderRosterSide(side);}renderLibrary();updateForceHistoryButtons();}
  function setupZone(zone){zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('drag-over');});zone.addEventListener('dragleave',()=>zone.classList.remove('drag-over'));zone.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();zone.classList.remove('drag-over');const faction=zone.dataset.faction,commandId=zone.dataset.command;const commandRaw=e.dataTransfer.getData('application/x-bax-command');if(commandRaw){const d=JSON.parse(commandRaw);if(d.faction!==faction){alert('Commands cannot be assigned across opposing sides.');return;}moveCommandInTree(faction,d.commandId,commandId);return;}const profile=e.dataTransfer.getData('application/x-bax-library');if(profile){addLibraryUnit(profile,faction,commandId);return;}const raw=e.dataTransfer.getData('application/x-bax-roster');if(raw){const d=JSON.parse(raw),from=findCommand(d.fromFaction,d.fromCommand),to=findCommand(faction,commandId);if(!from||!to)return;const i=from.units.findIndex(x=>x.id===d.unitId);if(i>=0){checkpointForces();const [u]=from.units.splice(i,1);to.units.push(u);persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderForces();}}});}
  function renderLibrary(){const q=($('#unitLibrarySearch').value||'').toLowerCase();$('#unitLibrary').innerHTML='';for(const item of unitLibrary().filter(x=>!q||`${x.profile} ${x.category} ${x.traits.join(' ')}`.toLowerCase().includes(q))){const c=document.createElement('div');c.className='library-card';c.draggable=true;c.innerHTML=`<span class="library-icon">${item.icon}</span><div><strong>${safe(item.profile)}</strong><small>${safe(item.category)} · M${item.m} C${item.c} A${item.a} · ${item.pts} pts</small><div class="trait-chips">${item.traits.map(t=>`<span>${safe(t)}</span>`).join('')}</div><p>${safe(item.source)}</p></div>`;c.addEventListener('dragstart',e=>e.dataTransfer.setData('application/x-bax-library',item.profile));$('#unitLibrary').appendChild(c);}}
  function addLibraryUnit(profile,faction,commandId){const base=unitLibrary().find(x=>x.profile===profile);if(!base)return;if(['Camp','Baggage Train'].includes(profile)){const units=(scenario().commands[faction]||[]).flatMap(c=>c.units||[]),policy=effectiveArmyAssetPolicy(scenario(),faction),camps=units.filter(u=>u.profile==='Camp').length,baggage=units.filter(u=>u.profile==='Baggage Train').length;if(profile==='Camp'&&camps>=policy.campMax){alert(`${faction} may currently field ${policy.campMax} Camp${policy.campMax===1?'':'s'}. ${policy.source}.`);return;}if(profile==='Baggage Train'&&baggage>=policy.baggageMax){alert(`${faction} may currently field ${policy.baggageMax} Baggage Train.`);return;}if(policy.mutuallyExclusive&&((profile==='Camp'&&baggage)||(profile==='Baggage Train'&&camps))){alert(`${faction} already has ${profile==='Camp'?'Baggage Train':'Camp'}. The current effective rules keep Camps and Baggage Trains mutually exclusive.`);return;}}checkpointForces();let cmd=findCommand(faction,commandId);if(!cmd)cmd=ensureCommand(faction,`${faction} Main Command`);cmd.units.push({id:uid('unit'),name:profile,profile,commander:'',represents:'',traits:[...base.traits],notes:'Added manually from canonical Battle Axe Unit Library.'});persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderForces();}
  function createSuggestedCommands(){
    const s=scenario();if(!(s.sourceCommands||[]).length){alert('No structured source command hierarchy is available yet. Re-analyze the scenario source first.');return;}checkpointForces();registerEvidenceSides(s,s.sourceForces||[],s.sourceCommands||[]);const evidence=[...(s.sourceCommands||[])],created=new Map();
    for(let pass=0;pass<evidence.length+2;pass++)for(const src of evidence){if(created.has(src.id))continue;if(src.parentCommandId&&!created.has(src.parentCommandId))continue;const side=sideForFaction(s,src.faction,{assign:true}),parentCommandId=src.parentCommandId?(created.get(src.parentCommandId)?.id||null):null,c=ensureCommand(side,src.name,src.scenarioCommander||src.commander||'',{sourceId:src.id,commandType:src.commandType||src.hierarchyLevel||'command',parentCommandId,commandRating:src.commandRating,status:src.status||'',role:src.role||'',notes:src.notes||[]});created.set(src.id,c);}
    for(const src of evidence)if(!created.has(src.id)){const side=sideForFaction(s,src.faction,{assign:true}),c=ensureCommand(side,src.name,src.scenarioCommander||src.commander||'',{sourceId:src.id,commandType:src.commandType||src.hierarchyLevel||'command',parentCommandId:null,commandRating:src.commandRating,status:src.status||'',role:src.role||'',notes:src.notes||[]});created.set(src.id,c);}
    normalizeCommandHierarchy(s);persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderForces();
  }
  function addProposals(){const proposed=proposedRosterUnits(scenario().sourceForces,ruleset());registerEvidenceSides(scenario(),scenario().sourceForces||[],scenario().sourceCommands||[]);for(const faction of Object.keys(proposed)){const side=sideForFaction(scenario(),faction,{assign:true});for(const p of proposed[faction]){const cmd=ensureCommand(side,p.commandName,p.commander);if(cmd.units.some(u=>u.sourceId===p.sourceId&&u.profile===p.profile&&u.name===p.name))continue;cmd.units.push({id:uid('unit'),sourceId:p.sourceId,name:p.name,profile:p.profile,commander:'',represents:p.represents,traits:p.traits,notes:p.notes,forceRole:p.forceRole||null});}}persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderForces();}
  function editCommand(faction,id){const c=findCommand(faction,id);if(!c)return;const name=prompt('Command name:',c.name);if(name===null)return;const commander=prompt('Commander:',c.commander||'');if(commander===null)return;const type=prompt('Command type/echelon (Army, Corps, Division, Brigade, Wing, Battle, Artillery, etc.):',c.commandType||c.echelon||'command');if(type===null)return;checkpointForces();c.name=name.trim()||c.name;c.commander=commander.trim();c.commandType=type.trim()||'command';c.echelon=c.commandType;const cr=commandRatingRules();if(cr){const rating=prompt(`Command Rating (${cr.ratingMin??0}–${cr.ratingMax??3}; blank = roll generic rating during playtest):`,c.commandRating==null?'':String(c.commandRating));if(rating!==null)c.commandRating=normalizeCommandRating(rating);}normalizeCommandHierarchy(scenario());persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderForces();}

  function addCommand(faction){const side=canonicalSide(faction),label=sideLabel(scenario(),side),name=prompt(`New ${label} command name:`,`${label} Command ${(scenario().commands[side]||[]).length+1}`);if(!name)return;const commander=prompt('Commander (optional):','')||'',commandType=(prompt('Command type/echelon (Army, Corps, Division, Brigade, Wing, Battle, Artillery, etc.):','Brigade')||'command').trim();checkpointForces();const c=ensureCommand(side,name.trim(),commander.trim(),{commandType,parentCommandId:null}),cr=commandRatingRules();if(cr&&commander.trim()){const rating=prompt(`Command Rating (${cr.ratingMin??0}–${cr.ratingMax??3}; blank = roll generic rating during playtest):`,'');c.commandRating=normalizeCommandRating(rating);}persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderForces();}

  function deleteCommandById(faction,id){const side=canonicalSide(faction),c=findCommand(side,id);if(!c)return;const children=(scenario().commands[side]||[]).filter(x=>x.parentCommandId===id),unitCount=(c.units||[]).length;const details=[unitCount?`${unitCount} unit${unitCount===1?'':'s'} directly in this command will also be deleted.`:'',children.length?`${children.length} subordinate command${children.length===1?' will':'s will'} be promoted to ${c.parentCommandId?'the deleted command’s parent':'top level'}.`:''].filter(Boolean).join('\n');if(!confirm(`Delete command “${c.name}”?${details?`\n\n${details}`:''}`))return;checkpointForces();const removed=removeCommand(scenario(),side,id,{mode:'promote'});const dep=scenario().deployment||{};for(const unitId of removed.removedUnitIds||[])delete dep.placements?.[unitId];for(const commandId of removed.removedCommandIds||[])delete dep.commanderPlacements?.[commandId];persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderForces();}

  function openUnitEditor(faction,commandId,id){const c=findCommand(faction,commandId),u=c?.units.find(x=>x.id===id);if(!u)return;editingUnit={faction,commandId,id};$('#unitEditorTitle').textContent=u.name;$('#unitName').value=u.name;$('#unitProfile').innerHTML=unitLibrary().map(x=>`<option ${x.profile===u.profile?'selected':''}>${safe(x.profile)}</option>`).join('');$('#unitCommander').value=u.commander||'';$('#unitRepresents').value=u.represents||'';$('#unitBaseWidthOverride').value=u.baseWidthMm||'';$('#unitBaseDepthOverride').value=u.baseDepthMm||'';const fp=unitFootprint(u);$('#unitBaseWidthOverride').placeholder=`Inherit ${fp.width} mm`;$('#unitBaseDepthOverride').placeholder=`Inherit ${fp.depth} mm`;$('#unitTraits').value=(u.traits||[]).join('\n');$('#unitNotes').value=u.notes||'';$('#unitEditorDialog').showModal();}
  function saveUnit(){if(!editingUnit)return;checkpointForces();const c=findCommand(editingUnit.faction,editingUnit.commandId),u=c?.units.find(x=>x.id===editingUnit.id);if(!u)return;u.name=$('#unitName').value.trim()||$('#unitProfile').value;u.profile=$('#unitProfile').value;u.commander=$('#unitCommander').value;u.represents=$('#unitRepresents').value;const bw=Number($('#unitBaseWidthOverride').value),bd=Number($('#unitBaseDepthOverride').value);if(Number.isFinite(bw)&&bw>0)u.baseWidthMm=bw;else delete u.baseWidthMm;if(Number.isFinite(bd)&&bd>0)u.baseDepthMm=bd;else delete u.baseDepthMm;u.traits=$('#unitTraits').value.split('\n').map(x=>x.trim()).filter(Boolean);u.notes=$('#unitNotes').value;persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));$('#unitEditorDialog').close();renderForces();}
  function deleteUnitById(faction,commandId,id){const c=findCommand(faction,commandId),u=c?.units.find(x=>x.id===id);if(!c||!u)return;if(!confirm(`Delete unit “${u.name}”?`))return;checkpointForces();const i=c.units.findIndex(x=>x.id===id);if(i>=0)c.units.splice(i,1);delete scenario().deployment?.placements?.[id];persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderForces();}
  function deleteUnit(){if(!editingUnit)return;const current={...editingUnit};$('#unitEditorDialog').close();deleteUnitById(current.faction,current.commandId,current.id);editingUnit=null;}

  function renderChecklist(){const s=scenario(),units=allUnits(),accepted=s.suggestions.filter(x=>x.status==='accepted'),unresolved=[...new Set(s.unresolved||[])];const items=[['Summary',!!s.metadata.title,'review'],['Forces',units.length>0,'forces'],['Commanders',Object.values(s.commands||{}).flat().some(c=>c.commander),'forces'],['Scenario rules',accepted.length>0,'suggestions'],['Victory conditions',!!(s.victoryText||'').trim(),'review'],['Deployment',Object.keys(s.deployment?.placements||{}).length>0,'summary'],['Unresolved',unresolved.length===0,'summary']];const host=$('#scenarioChecklist');if(!host)return;host.innerHTML=items.map(([label,ok,tab])=>`<button class="check-chip ${ok?'complete':'needs'}" data-check-tab="${tab}"><span>${ok?'✓':'!'}</span>${safe(label)}${label==='Unresolved'&&unresolved.length?` (${unresolved.length})`:''}</button>`).join('');host.querySelectorAll('[data-check-tab]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`.scenario-tab[data-scenario-tab="${b.dataset.checkTab}"]`)?.click()));}

  function renderSummary(){const s=scenario(),accepted=s.suggestions.filter(x=>x.status==='accepted'),units=allUnits(),commandCount=Object.values(s.commands).flat().length;$('#scenarioSummaryCard').innerHTML=`<h4>${safe(s.metadata.title||'Untitled scenario')}</h4><dl class="summary-dl"><div><dt>Date</dt><dd>${safe(s.metadata.date||'—')}</dd></div><div><dt>Location</dt><dd>${safe(s.metadata.location||'—')}</dd></div><div><dt>Game length</dt><dd>${safe(s.metadata.gameLength||'—')}</dd></div><div><dt>Commands</dt><dd>${commandCount}</dd></div><div><dt>Battle Axe units</dt><dd>${units.length}</dd></div><div><dt>Accepted scenario rules</dt><dd>${accepted.length}</dd></div></dl><h4>Accepted rules / parameters</h4>${accepted.map(x=>`<div class="summary-rule"><b>${safe(x.title)}</b><p>${safe(x.proposal)}</p></div>`).join('')||'<p class="muted">None accepted.</p>'}`;const unresolved=[...s.unresolved];if(!s.metadata.title)unresolved.push('Scenario title required');if(!units.length)unresolved.push('No Battle Axe units in force roster');$('#scenarioUnresolved').innerHTML=unresolved.length?`<ul>${[...new Set(unresolved)].map(x=>`<li>${safe(x)}</li>`).join('')}</ul>`:'<p class="success">No current alpha validation warnings.</p>';}
  function exportJson(){const payload=createProjectExportPayload(state,{studioVersion:'0.6.8.0'}),blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${(scenario().metadata.title||'battle-axe-scenario').replace(/[^a-z0-9]+/gi,'_')}_Studio_Project.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);}
  function renderStructuredRules(){const el=$('#turnOneInitiative');if(el)el.value=scenario().structuredRules?.turnOneInitiative||'';}
  function renderAllScenario(){renderRuleset();renderStructuredRules();renderTabletop();renderSources();renderReview();renderHistoricalRegister();renderSuggestions();renderForces();renderSummary();renderChecklist();}

  tabs();renderAllScenario();window.addEventListener('bax:scenario-changed',renderAllScenario);
  $('#scenarioSupplementSelector')?.addEventListener('change',e=>{
    const selected=listSupplements().find(x=>x.id===e.target.value);
    scenario().ruleset={core:'battle-axe-core',supplement:e.target.value,supplementVersion:selected?.version||'1'};
    const defaults=ruleset().supplement.sideDefaults||{};
    scenario().sideLabels||={French:'Side A',Imperial:'Side B'};scenario().sideAliases||={};
    for(const side of SIDE_KEYS){
      const label=defaults[side];if(!label)continue;
      const generic=side==='French'?'Side A':'Side B';
      if(!scenario().sideLabels[side]||scenario().sideLabels[side]===generic){scenario().sideLabels[side]=label;scenario().sideAliases[label]=side;scenario().sideAliases[label.toLowerCase()]=side;}
    }
    // A supplement switch changes the interpretation vocabulary. Re-run source extraction so the
    // historical command tree/profile hints are not left stale from the previously selected period.
    // Final designer-built commands/units, deployment, and accepted/designer-edited rules are preserved.
    const sourceText=[stagedText,$('#scenarioSourceText')?.value,...(scenario().sources||[]).filter(x=>x.text).map(x=>x.text)].filter(Boolean).join('\n\n');
    if(sourceText.trim()){
      scenario().sourceForces=[];scenario().sourceCommands=[];scenario().observations=[];
      scenario().unresolved=(scenario().unresolved||[]).filter(x=>!/historical formation|command organization|subordinate command|command assignment/i.test(x));
      mergeAnalysis(analyzeScenarioText(sourceText,{sourceName:'Re-analysis after supplement change',ruleset:ruleset()}),'Re-analysis after supplement change');
    }
    persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));renderAllScenario();
  });
  $('#tabletopPreset')?.addEventListener('change',saveTabletop);['unitBaseWidthMm','unitBaseDepthMm','commanderBaseMm','measurementMultiplier'].forEach(id=>$('#'+id)?.addEventListener('change',()=>{$('#tabletopPreset').value='custom';saveTabletop();}));$('#checkScenario')?.addEventListener('click',validateScenario);
  $('#scenarioFiles').addEventListener('change',e=>addFiles([...e.target.files]));  $('#analyzeScenario').addEventListener('click',()=>{const text=[stagedText,$('#scenarioSourceText').value,...scenario().sources.filter(x=>x.text).map(x=>x.text)].filter(Boolean).join('\n\n');analyze(text,scenario().sources.map(x=>x.name).join(' + ')||'Pasted source text');});
  $('#clearScenarioSources').addEventListener('click',()=>{scenario().sources=[];scenario().observations=[];scenario().suggestions=[];scenario().sourceForces=[];scenario().sourceCommands=[];scenario().unresolved=[];stagedText='';$('#scenarioSourceText').value='';persist();renderAllScenario();});
  $('#saveScenarioFields').addEventListener('click',saveFields);$('#refreshForcePlan')?.addEventListener('click',renderForcePlan);$('#createSuggestedCommands')?.addEventListener('click',createSuggestedCommands);$('#turnOneInitiative')?.addEventListener('change',e=>{scenario().structuredRules={...(scenario().structuredRules||{}),turnOneInitiative:e.target.value||''};persist();window.dispatchEvent(new CustomEvent('bax:scenario-changed'));});$('#unitLibrarySearch').addEventListener('input',renderLibrary);
  document.querySelectorAll('[data-add-command]').forEach(b=>b.addEventListener('click',()=>addCommand(b.dataset.addCommand)));$('#forceUndo')?.addEventListener('click',undoForces);$('#forceRedo')?.addEventListener('click',redoForces);
  $('#closeUnitEditor').addEventListener('click',()=>$('#unitEditorDialog').close());$('#saveUnitEditor').addEventListener('click',saveUnit);$('#deleteUnitEditor').addEventListener('click',deleteUnit);
  $('#closeRuleEditor').addEventListener('click',()=>$('#ruleEditorDialog').close());$('#saveRuleEditor').addEventListener('click',saveSuggestion);$('#addScenarioRule')?.addEventListener('click',addManualRule);
  $('#exportScenarioJson').addEventListener('click',exportJson);$('#resetScenario').addEventListener('click',()=>{if(confirm('Reset the Scenario Builder to a blank scenario?')){state.project.scenario=createBlankScenario();persist();renderAllScenario();}});
  return {renderAllScenario,renderForces,renderSummary,allUnits};
}
