import { getEffectiveRuleset, profileForText } from '../rules/ruleset.js?v=0.5.6.0';

const cleanInline=s=>(s||'').replace(/\r/g,'').replace(/[ \t]+/g,' ').trim();
const cleanBlock=s=>(s||'').replace(/\r/g,'').replace(/[ \t]+\n/g,'\n').replace(/\n[ \t]+/g,'\n').replace(/\n{3,}/g,'\n\n').trim();
const lines=t=>t.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);
const idify=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,56);
const stripMarkup=s=>cleanInline(s).replace(/^#{1,6}\s*/,'').replace(/^\*\*(.*?)\*\*$/,'$1').replace(/\*\*/g,'').replace(/[:.]+$/,'').trim();

const HEADING_ALIASES={
  historical:['historical situation','historical overview','overview','background'],
  battlefield:['battlefield','terrain','the battlefield'],
  forces:['forces engaged','battle axe forces','forces'],
  french:['french army','france'],
  imperial:['imperial army','imperialist'],
  deployment:['deployment','deploy forces'],
  rules:['scenario rules','special rules','scenario notes','historical events / special-rule candidates','historical events','special-rule candidates'],
  victory:['victory conditions','victory'],designer:['designer notes','designer\'s notes'],sources:['sources','source notes','appendix'],objectives:['scenario objectives','objectives','aims'],character:['scenario character','scenario design','scenario concept']
};
function headingKey(line){const normalized=stripMarkup(line).toLowerCase();for(const [key,aliases] of Object.entries(HEADING_ALIASES))if(aliases.some(a=>normalized===a))return key;return null;}
function armyHeadingLabel(line){const normalized=stripMarkup(line);if(/^(?:battle axe )?forces?$/i.test(normalized))return null;const m=normalized.match(/^(.+?)\s+(?:army|forces?|host|contingent)$/i);if(!m)return null;const label=cleanInline(m[1]).replace(/^(?:the)\s+/i,'');return label&&label.length<=48?label:null;}
function splitSections(text){const raw=text.replace(/\r/g,'').split('\n'),out={preamble:[]};let current='preamble';for(const line of raw){const trimmed=line.trim(),key=headingKey(trimmed),army=key?null:armyHeadingLabel(trimmed);if(key||army){current=key||`army:${army}`;if(!out[current])out[current]=[];continue;}if(!out[current])out[current]=[];out[current].push(line);}return Object.fromEntries(Object.entries(out).map(([k,v])=>[k,cleanBlock(v.join('\n'))]));}
function detectMetadata(text){const ls=lines(text),joined=ls.join(' '),title=ls.find(l=>/^battle of\b/i.test(stripMarkup(l)))||ls.find(l=>/battle of/i.test(l))||'',date=(joined.match(/\b(?:\d{1,2}\s+[A-Z][a-z]+\s+\d{4}|[A-Z][a-z]+\s+\d{1,2},\s*\d{4})\b/)||[])[0]||'',location=(joined.match(/Location:\s*(.+?)(?=\s+(?:Table|Game Length|Status|Map):|$)/i)||[])[1]||'',turns=(joined.match(/(?:Game Length|Battle Length)\s*:\s*(\d+)\s*(?:Battle Axe\s*)?Turns?/i)||[])[1]||'',table=(joined.match(/(?:Table(?: Size)?\s*:\s*)?([2468]'\s*[×xX]\s*[2468]'|\d{2}\s*[”"]?\s*[×xX]\s*\d{2}\s*[”"]?)/)||[])[1]||'',status=(joined.match(/Status:\s*(.+?)(?=\s+[A-Z][A-Za-z ]+:|$)/i)||[])[1]||'';return{title:stripMarkup(title),date,location:cleanInline(location),gameLength:turns,status:cleanInline(status),tableSize:table};}
function factionFor(text,current='Unknown'){const m=text.match(/\b(French|Spanish|Imperial|English|Scottish|Venetian|Milanese|Papal|Swiss|Ottoman|Burgundian|Florentine|Neapolitan|Aragonese)\b/i);return m?m[1][0].toUpperCase()+m[1].slice(1).toLowerCase():current;}
function strengthFrom(text){const m=text.match(/\b(?:approximately|about|roughly|c\.?|circa)?\s*(\d{1,3}(?:,\d{3})+|\d{3,5})\b/i);return m?m[1]:'';}
function explicitCommander(line){const m=stripMarkup(line).match(/^Commander\s*:\s*(.+)$/i);return m?cleanInline(m[1]).trim():'';}
function armyCommander(line){const m=stripMarkup(line).match(/^(?:Commander[- ]in[- ]Chief|Commander in Chief|Army Commander|Overall Commander)\s*:\s*(.+)$/i);return m?cleanInline(m[1]).trim():'';}
function associatedCommander(line){const m=stripMarkup(line).match(/^(?:Associated Commander|Attached Commander)\s*:\s*(.+)$/i);return m?cleanInline(m[1]).trim():'';}
function evidenceName(line,profile){const x=cleanInline(line).replace(/^[-*•\d.)\s]+/,'').replace(/\*\*/g,'');const first=x.split(/[.;]/)[0].replace(/\s*→.*$/,'').trim();return first.length<=110?first:profile;}
function confidenceContext(line,current=86){const s=stripMarkup(line).toLowerCase();if(/higher[- ]confidence|high confidence|well attested|secure assignment/.test(s))return 95;if(/reasonably supported|probable|likely assignment/.test(s))return 82;if(/provisional|tentative|uncertain assignment|possible assignment/.test(s))return 62;return current;}
function isConfidenceHeading(line){return /confidence|reasonably supported|provisional|tentative|assignment/i.test(stripMarkup(line))&&!/commander/i.test(stripMarkup(line));}
function isListLike(line){return /^\s*(?:[-*•]|\d+[.)])\s+/.test(line);}
function isGenericHeading(line){const s=stripMarkup(line).toLowerCase();return !!headingKey(line)||!!armyHeadingLabel(line)||/^(?:command structure|order of battle|higher[- ]confidence command assignments|reasonably supported assignments|provisional command assignments|command assignments|formations|troops|composition|notes?)$/i.test(s);}
function looksLikeCommandHeading(raw,nextLines=[]){if(!raw.trim()||isListLike(raw)||isGenericHeading(raw)||armyCommander(raw)||explicitCommander(raw)||associatedCommander(raw))return false;const s=stripMarkup(raw);if(!s||s.length>100||/[:;]$/.test(s))return false;const marked=/^#{1,6}\s/.test(raw.trim())||/^\*\*.*\*\*$/.test(raw.trim());const nextHasCommander=nextLines.slice(0,3).some(x=>!!explicitCommander(x)||!!associatedCommander(x));const commandWord=/\b(command|reserve|centre|center|wing|vanguard|rearguard|rear guard|infantry|cavalry|artillery|garrison|battle|division|column|contingent|guard)\b/i.test(s);const nextHasFormation=nextLines.slice(0,5).some(x=>isListLike(x));return nextHasCommander||(commandWord&&(marked||nextHasFormation));}

/** Parse army -> command -> formation hierarchy directly from the authored intake text.
 * The parser preserves explicit document hierarchy and confidence language. It never invents
 * a command from troop type alone; formations without an explicit enclosing command remain unassigned.
 */
export function detectForceHierarchy(text,ruleset=getEffectiveRuleset(null)){
  const raw=text.replace(/\r/g,'').split('\n'),forces=[],commands=[],armyCommanders=new Map();let faction='Unknown',currentCommand=null,assignmentConfidence=88;
  const nextNonBlank=i=>raw.slice(i+1).map(x=>x.trim()).filter(Boolean);
  const makeCommand=(name,sourceText)=>{const id=`cmd-evidence-${idify(`${faction}-${name}-${commands.length}`)}`,c={id,faction,name:stripMarkup(name)||'Command',commander:'',armyCommander:armyCommanders.get(faction)||'',associatedCommander:'',formations:[],provenance:'SOURCE',confidence:assignmentConfidence,sourceText};commands.push(c);return c;};
  for(let i=0;i<raw.length;i++){
    const original=raw[i],trimmed=original.trim();if(!trimmed)continue;
    const army=armyHeadingLabel(trimmed);if(army){faction=army;currentCommand=null;continue;}
    const knownHeading=headingKey(trimmed);if(knownHeading==='french'){faction='French';currentCommand=null;continue;}if(knownHeading==='imperial'){faction='Imperial';currentCommand=null;continue;}if(knownHeading&&knownHeading!=='forces'){currentCommand=null;continue;}
    assignmentConfidence=confidenceContext(trimmed,assignmentConfidence);
    if(isConfidenceHeading(trimmed)){currentCommand=null;continue;}
    const chief=armyCommander(trimmed);if(chief){armyCommanders.set(faction,chief);for(const c of commands.filter(x=>x.faction===faction&&!x.armyCommander))c.armyCommander=chief;continue;}
    const next=nextNonBlank(i);
    if(looksLikeCommandHeading(original,next)){currentCommand=makeCommand(trimmed,trimmed);continue;}
    const commander=explicitCommander(trimmed);if(commander){if(!currentCommand)currentCommand=makeCommand(`${faction} command`,trimmed);currentCommand.commander=commander;currentCommand.sourceText=`${currentCommand.sourceText}\n${trimmed}`;currentCommand.confidence=Math.max(currentCommand.confidence,assignmentConfidence);continue;}
    const assoc=associatedCommander(trimmed);if(assoc){if(!currentCommand)currentCommand=makeCommand(`${faction} artillery / attached command`,trimmed);currentCommand.associatedCommander=assoc;currentCommand.sourceText=`${currentCommand.sourceText}\n${trimmed}`;continue;}
    const profile=profileForText(trimmed,ruleset);if(!profile)continue;
    const listLike=isListLike(original),lineFaction=factionFor(trimmed,faction),name=evidenceName(trimmed,profile),key=`${lineFaction}|${currentCommand?.id||'unassigned'}|${name}|${profile}`;
    if(forces.some(x=>x.key===key))continue;
    const id=`src-${idify(key)}`,force={key,id,faction:lineFaction,name,profileHint:profile,strength:strengthFrom(trimmed),sourceText:trimmed,section:`army:${lineFaction}`,confidence:listLike?Math.min(96,assignmentConfidence+3):Math.min(84,assignmentConfidence),provenance:'SOURCE',translationStatus:'unresolved',forceRole:/\bgarrison\b|\bdefenders? of\b/i.test(trimmed)?'garrison':null,commandId:currentCommand?.id||null,commandName:currentCommand?.name||'',commander:currentCommand?.commander||'',armyCommander:armyCommanders.get(lineFaction)||currentCommand?.armyCommander||''};
    forces.push(force);if(currentCommand){if(currentCommand.faction==='Unknown')currentCommand.faction=lineFaction;currentCommand.formations.push(id);}
  }
  for(const c of commands){if(!c.armyCommander)c.armyCommander=armyCommanders.get(c.faction)||'';c.formations=[...new Set(c.formations)];}
  // Remove empty synthetic commands created by isolated Commander lines only when they add no useful hierarchy.
  const useful=commands.filter(c=>c.formations.length||c.commander||c.associatedCommander);
  return{forces:forces.slice(0,100),commands:useful.slice(0,40),armyCommanders:Object.fromEntries(armyCommanders)};
}

function detectHistoricalFormations(text,sections={},ruleset=getEffectiveRuleset(null)){const h=detectForceHierarchy(text,ruleset);if(h.forces.length)return h.forces;const out=[];for(const [section,block] of Object.entries(sections)){if(!block)continue;let current=section==='french'?'French':section==='imperial'?'Imperial':section.startsWith('army:')?section.slice(5):'Unknown';for(const raw of lines(block)){if(explicitCommander(raw)||armyCommander(raw)||raw.length>240)continue;const profile=profileForText(raw,ruleset);if(!profile)continue;const listLike=/^[-*•]|\d+[.)]\s/.test(raw),faction=factionFor(raw,current),name=evidenceName(raw,profile),key=`${section}|${faction}|${name}|${profile}`;if(!out.some(x=>x.key===key))out.push({key,id:`src-${idify(key)}`,faction,name,profileHint:profile,strength:strengthFrom(raw),sourceText:raw,section,confidence:listLike?92:(raw.length<125?76:58),provenance:'SOURCE',translationStatus:'unresolved',forceRole:/\bgarrison\b|\bdefenders? of\b/i.test(raw)?'garrison':null,commandId:null,commandName:'',commander:'',armyCommander:''});}}return out.slice(0,80);}
function makeSuggestion(type,title,proposal,evidence,confidence=70){return{id:`sug-${idify(type+'-'+title)}`,type,title,proposal,evidence,confidence,status:'pending',provenance:'STUDIO PROPOSAL'};}
function detectSuggestions(text,sections={}){let paras=[];for(const k of ['rules','designer'])if(sections[k])paras.push(...sections[k].split(/\n+/));if(!paras.length)paras=text.split(/\n+/).filter(x=>/rule|candidate|special|event|objective|prepared|delayed|arrival|counterattack|explosion|death|visibility|screen/i.test(x));const s=[];for(const raw of paras.map(cleanInline).filter(Boolean)){const p=raw.replace(/\*\*/g,''),colon=p.indexOf(':'),title=cleanInline(colon>0?p.slice(0,colon):p).replace(/^[-*•]+/,'').slice(0,80),body=cleanInline(colon>0?p.slice(colon+1):p);if(title.length<3)continue;if(/candidate|consider|may|could|should|optional|rule|event|position|attack|screen|artillery|counterattack|explosion|death|prepared/i.test(p))s.push(makeSuggestion('Scenario Rule Candidate',title,body||`Consider whether ${title} requires a scenario-specific mechanism.`,`Source presents this as a possible scenario mechanism/event: ${p}`,88));}if(/\bfog\b|\bmist\b|\bvisibility\b/i.test(text))s.push(makeSuggestion('Scenario Rule Candidate','Opening visibility','Consider whether opening visibility should be restricted and then improve as conditions change.','Source mentions fog, mist, or visibility conditions.',72));if(/\bsortie\b|\bgarrison\b.{0,80}\b(?:enter|attack|commit|emerge)\b/i.test(text))s.push(makeSuggestion('Scenario Rule Candidate','Garrison sortie','Consider a scenario condition governing when the garrison may enter or become active.','Source mentions a garrison sortie or later garrison commitment.',78));const seen=new Set();return s.filter(x=>{const k=x.title.toLowerCase();if(seen.has(k))return false;seen.add(k);return true;}).slice(0,24);}

export function analyzeScenarioText(text,{sourceName='Pasted text',ruleset=getEffectiveRuleset(null)}={}){text=cleanBlock(text);const sections=splitSections(text),metadata=detectMetadata(text),historicalSituation=sections.historical||sections.preamble||'',deploymentNotes=sections.deployment||'',victoryText=sections.victory||sections.objectives||'',hierarchy=detectForceHierarchy(text,ruleset),forces=hierarchy.forces.length?hierarchy.forces:detectHistoricalFormations(text,sections,ruleset),sourceCommands=hierarchy.commands,suggestions=detectSuggestions(text,sections),observations=[];for(const [field,value] of Object.entries(metadata))if(value)observations.push({field,value,sourceName,confidence:field==='title'||field==='date'?95:82,provenance:'SOURCE'});for(const [field,value,confidence] of [['Historical situation',historicalSituation,90],['Battlefield character',sections.battlefield||'',88],['Scenario character',sections.character||sections.designer||'',82],['Deployment',deploymentNotes,86],['Victory conditions',victoryText,86]])if(value)observations.push({field,value:value.slice(0,3500),sourceName,confidence,provenance:'SOURCE'});const unresolved=[];if(!metadata.gameLength)unresolved.push('Game length not found');if(!victoryText)unresolved.push('Victory conditions/objectives not found');if(!forces.length)unresolved.push('No historical formations confidently extracted');if(forces.length&&!sourceCommands.length)unresolved.push('Subordinate command organization is unresolved; no explicit command hierarchy was found in the intake source.');else if(forces.some(f=>!f.commandId))unresolved.push(`${forces.filter(f=>!f.commandId).length} historical formation(s) remain outside an explicit source command.`);return{metadata,historicalSituation,deploymentNotes,victoryText,forces,sourceCommands,suggestions,observations,unresolved};}
export function proposedRosterUnits(sourceForces,ruleset=getEffectiveRuleset(null)){const byFaction={};for(const f of sourceForces){if(!byFaction[f.faction])byFaction[f.faction]=[];const profile=f.profileHint;byFaction[f.faction].push({proposalId:`proposal-${f.id}`,sourceId:f.id,name:profile,profile,represents:f.name,commander:f.commander||'',commandName:f.commandName||`${f.faction} — command unresolved`,traits:[...(ruleset.unitLibrary.find(u=>u.profile===profile)?.traits||[])],notes:`STUDIO PROPOSAL from historical evidence: ${f.sourceText}${f.strength?` Strength recorded: ${f.strength}.`:''} The source does not by itself determine how many Battle Axe units this formation should become. Review unit count, profile, and command allocation before acceptance.`,accepted:false,provenance:'STUDIO PROPOSAL',confidence:Math.max(45,f.confidence-12),forceRole:f.forceRole||null});}return byFaction;}
