import { buildAutoTacticalPlan, interpretOrderText, scenarioConfigFingerprint } from './playtestEngine.js?v=0.6.9.1';
import { compileTacticalIntent, validateTacticalIntent, TACTICAL_INTENT_VERSION } from './tacticalIntent.js?v=0.6.9.1';
import { acceptedScenarioRules } from './scenarioProposal.js?v=0.6.9.1';

const VALID_POSTURES=new Set(['Auto','Offensive','Balanced','Defensive','Delay']);
const VALID_ORDERS=new Set(['Auto','Hold','Defend','Advance','Assault','Reserve','Screen','Maneuver','Withdraw']);
const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').trim();
const words=s=>new Set(norm(s).split(/\s+/).filter(Boolean));
const centerOfBox=box=>Array.isArray(box)&&box.length>=4?{x:Number(box[0])+Number(box[2])/2,y:Number(box[1])+Number(box[3])/2}:null;
const pctDist=(a,b)=>a&&b?Math.hypot(a.x-b.x,a.y-b.y):Infinity;

function allCommands(scenario){return Object.entries(scenario?.commands||{}).flatMap(([faction,commands])=>(commands||[]).map(c=>({faction,...c})));}
function commandCentroid(state,c){const p=state.project?.scenario?.deployment?.placements||{},pts=(c.units||[]).map(u=>p[u.id]).filter(Boolean).map(x=>({x:Number(x.x),y:Number(x.y)}));return pts.length?{x:pts.reduce((a,q)=>a+q.x,0)/pts.length,y:pts.reduce((a,q)=>a+q.y,0)/pts.length}:null;}
function commandRole(c){const names=(c.units||[]).map(u=>norm(`${u.profile} ${(u.traits||[]).join(' ')}`));if(names.length&&names.every(x=>/cannon|artillery/.test(x)))return'artillery';if(names.length&&names.every(x=>/caval|gendar|stradiot|ginete|horse/.test(x)))return'cavalry';if(names.length&&names.every(x=>/skirm|sharpshooter|light/.test(x)))return'light';return'line';}
function commandWeight(c){return(c.units||[]).reduce((sum,u)=>sum+(/cannon|artillery/i.test(u.profile||'')?.65:/caval|gendar|horse/i.test(u.profile||'')?1.15:1),0);}
function sideForFaction(f){return f==='sideA'?'sideA':'sideB';}
function sideLabel(scenario,side){return scenario?.sideLabels?.[side]||side;}
function objectiveFeature(state){
  const text=norm(state.project?.scenario?.victoryText||'');if(!text)return null;
  const approved=(state.project?.features||[]).filter(f=>state.decisions?.[f.id]?.status==='approved');
  const matches=approved.map(f=>({f,key:norm(f.name)})).filter(x=>x.key.length>=4&&text.includes(x.key)).sort((a,b)=>b.key.length-a.key.length);
  const hit=matches[0]?.f;if(!hit)return null;
  let center=centerOfBox(hit.box);if(!center&&hit.geometry?.parts?.length){const pts=hit.geometry.parts.flatMap(p=>p.points||[]);if(pts.length)center={x:pts.reduce((a,p)=>a+Number(p[0]??p.x??0),0)/pts.length,y:pts.reduce((a,p)=>a+Number(p[1]??p.y??0),0)/pts.length};}
  return{id:hit.id,name:hit.name,center};
}
function explicitRow(row){return !!row&&(row.autoGenerated690!==true)&&((row.order&&row.order!=='Auto')||String(row.text||'').trim()||(row.posture&&row.posture!=='Auto'));}

export function tacticalIntentContext690(state,{scope='command',commandId=null,side=null}={}){
  const scenario=state.project?.scenario||{},commands=allCommands(scenario).map(c=>({id:c.id,name:c.name,commander:c.commander||'',commanderName:c.commanderName||'',historicalCommander:c.historicalCommander||'',scenarioCommanderOverride:c.scenarioCommanderOverride||'',side:sideForFaction(c.faction)})),terrain=(state.project?.features||[]).filter(f=>state.decisions?.[f.id]?.status==='approved').map(f=>({id:f.id,name:f.name,class:state.decisions?.[f.id]?.cls||f.cls}));
  return{scope,commandId,ownSide:side||commands.find(c=>c.id===commandId)?.side||null,sideLabels:scenario.sideLabels||{},supplementId:scenario.ruleset?.supplement||'',commands,terrain};
}

export function generateAutoTacticalPlan690(state){
  const scenario=state.project?.scenario||{},objective=objectiveFeature(state);let base={armies:{},commands:{}};
  try{base=buildAutoTacticalPlan(state)||base;}catch(error){base._error=error?.message||String(error);}
  const result={version:'0.6.9.1',generatedAt:new Date().toISOString(),configuration:scenarioConfigFingerprint(state),objective:objective?{id:objective.id,name:objective.name}:null,armies:{},commands:{},notes:[]};
  for(const side of ['sideA','sideB']){
    const candidates=allCommands(scenario).filter(c=>sideForFaction(c.faction)===side&&(c.units||[]).length>0),enemy=allCommands(scenario).filter(c=>sideForFaction(c.faction)!==side&&(c.units||[]).length>0),enemyPts=enemy.map(c=>commandCentroid(state,c)).filter(Boolean),enemyCenter=enemyPts.length?{x:enemyPts.reduce((a,p)=>a+p.x,0)/enemyPts.length,y:enemyPts.reduce((a,p)=>a+p.y,0)/enemyPts.length}:null;
    const baseArmy=base.armies?.[side]||{},posture=VALID_POSTURES.has(baseArmy.posture)?baseArmy.posture:'Balanced';
    const line=candidates.filter(c=>commandRole(c)==='line'),mobile=candidates.filter(c=>commandRole(c)==='cavalry'),lights=candidates.filter(c=>commandRole(c)==='light'),artillery=candidates.filter(c=>commandRole(c)==='artillery');
    const scored=line.map(c=>{const pos=commandCentroid(state,c),target=objective?.center||enemyCenter,d=target?pctDist(pos,target):50;return{c,score:commandWeight(c)*20-Math.min(50,d)};}).sort((a,b)=>b.score-a.score);
    const main=scored[0]?.c||line[0]||candidates.find(c=>commandRole(c)!=='artillery')||candidates[0]||null;
    let reserve=null;
    if(candidates.length>=4){reserve=mobile.find(c=>c.id!==main?.id)||scored.slice().reverse().map(x=>x.c).find(c=>c.id!==main?.id)||null;}
    else if(posture==='Defensive'&&mobile.length)reserve=mobile.find(c=>c.id!==main?.id)||null;
    result.armies[side]={side,label:sideLabel(scenario,side),posture,autoPosture:baseArmy.autoPosture||posture,mainEffort:main?.id||null,reserve:reserve?.id||null,objective:objective?.name||'enemy force / scenario objective',reason:objective?`Auto Plan found the named victory-condition feature “${objective.name}” and uses it as a planning reference.`:(baseArmy.reason||'Auto Plan uses deployment, force roles and the existing Battle Axe posture assessment.')};
    for(const c of candidates){const role=commandRole(c),isMain=c.id===main?.id,isReserve=c.id===reserve?.id;let order=base.commands?.[c.id]?.autoOrder||base.commands?.[c.id]?.order||'Advance',mission='support the side plan';
      if(role==='artillery'){order='Hold';mission='provide fire support from a useful position';}
      else if(role==='light'){order=posture==='Defensive'||posture==='Delay'?'Screen':'Screen';mission='screen the main body and protect the tactical frontage';}
      else if(isReserve){order='Reserve';mission='remain available to reinforce success, stop a breakthrough, or exploit an opening';}
      else if(isMain){order=posture==='Defensive'?'Defend':posture==='Delay'?'Defend':posture==='Offensive'?'Assault':'Advance';mission=posture==='Defensive'?'hold the principal defensive sector':`make the main effort toward ${objective?.name||'the enemy position'}`;}
      else if(role==='cavalry'){order=posture==='Defensive'?'Reserve':'Maneuver';mission=posture==='Defensive'?'act as a mobile reserve':'seek a supporting flank or exploitation opportunity without abandoning the side plan';}
      else {order=posture==='Defensive'?'Defend':posture==='Delay'?'Defend':'Advance';mission=isMain?'make the main effort':'support the main effort while maintaining command cohesion';}
      const tacticalIntent={version:TACTICAL_INTENT_VERSION,source:'auto-plan',scope:'command',commandId:c.id,side,raw:'',order,mission,target:objective?{kind:'terrain',terrainIds:[objective.id],terrainName:objective.name}:null,releaseCondition:null,postReleaseOrder:null,formationIntent:role==='artillery'?'fire-support':isReserve?'reserve-depth':isMain?'main-effort':'supporting-effort',replanTriggers:[],warnings:[],unresolved:[],status:'understood'};
      result.commands[c.id]={commandId:c.id,name:c.name||c.id,side,order,mission,role,mainEffort:isMain,reserve:isReserve,objective:objective?.name||null,tacticalIntent,reason:isMain?'Chosen as the strongest/most relevant line command for the main effort.':role==='artillery'?'Artillery is kept in a supporting fire role.':isReserve?'Auto Plan retains depth instead of committing every command at once.':'Assigned a supporting mission so commands do not independently chase unrelated local opportunities.'};
    }
    if(!candidates.length)result.notes.push(`${sideLabel(scenario,side)} has no command containing Battle Axe units for Auto Plan.`);
  }
  return result;
}

export function applyAutoTacticalPlan690(state,persist,{force=false}={}){
  state.playtestWorkspace=state.playtestWorkspace||{armyOrders:{},commandOrders:{},cueLevel:'standard'};state.playtestWorkspace.armyOrders=state.playtestWorkspace.armyOrders||{};state.playtestWorkspace.commandOrders=state.playtestWorkspace.commandOrders||{};
  const plan=generateAutoTacticalPlan690(state);
  for(const [side,a] of Object.entries(plan.armies)){
    const old=state.playtestWorkspace.armyOrders[side]||{};if(!force&&explicitRow(old))continue;
    state.playtestWorkspace.armyOrders[side]={...old,posture:a.posture||'Auto',autoGenerated690:true,autoPlanMission:a.reason||'',autoPlanMainEffort:a.mainEffort||null};
  }
  for(const [id,c] of Object.entries(plan.commands)){
    const old=state.playtestWorkspace.commandOrders[id]||{};if(!force&&explicitRow(old))continue;
    state.playtestWorkspace.commandOrders[id]={...old,order:VALID_ORDERS.has(c.order)?c.order:'Auto',tacticalIntent:structuredClone(c.tacticalIntent),autoGenerated690:true,autoPlanMission:c.mission,autoPlanReason:c.reason,autoPlanMainEffort:!!c.mainEffort,autoPlanReserve:!!c.reserve};
  }
  state.playtestWorkspace.autoPlan690=plan;if(typeof persist==='function')persist();return plan;
}

function commandAliases(scenario,c){const a=[c.name,c.commander,c.commanderName,c.historicalCommander,c.scenarioCommanderOverride].map(norm).filter(Boolean);return a;}
function resolveCommands(text,state){const t=norm(text),scenario=state.project?.scenario||{},hits=[];for(const c of allCommands(scenario)){for(const alias of commandAliases(scenario,c)){if(alias.length>=3&&t.includes(alias)){hits.push({id:c.id,name:c.name,commander:c.commander||'',side:sideForFaction(c.faction),alias});break;}}}return hits;}
function resolveSidePhrase(text,state){const t=norm(text),s=state.project?.scenario||{},aliases=[];for(const side of ['sideA','sideB']){const label=norm(sideLabel(s,side));if(label)aliases.push([side,label]);}
  const supplement=norm(s.ruleset?.supplement||'');if(supplement.includes('american civil war'))aliases.push(['sideA','union'],['sideB','confederate'],['sideB','confederates'],['sideA','federal'],['sideB','rebel']);
  for(const [side,a] of aliases)if(a&&new RegExp(`\\b${a.replace(/ /g,'\\s+')}\\b`).test(t))return{side,label:sideLabel(s,side),alias:a};return null;
}
function resolveTerrain(text,state){const t=norm(text),approved=(state.project?.features||[]).filter(f=>state.decisions?.[f.id]?.status==='approved'),hits=approved.map(f=>({id:f.id,name:f.name,key:norm(f.name)})).filter(x=>x.key.length>=4&&t.includes(x.key)).sort((a,b)=>b.key.length-a.key.length);return hits;}
function extractTurn(t){const m=/(?:turn|on turn|after turn|until turn|by turn)\s*(\d+)/i.exec(t);return m?Number(m[1]):null;}

export function interpretSemanticOrder690(text,state,{scope='command',commandId=null,side=null}={}){
  const raw=String(text||'').trim(),legacy=interpretOrderText(raw),context=tacticalIntentContext690(state,{scope,commandId,side}),intent=compileTacticalIntent(raw,context),commands=intent.resolved?.commands||[],targetCommand=intent.target?.commandId?commands.find(c=>c.id===intent.target.commandId)||context.commands.find(c=>c.id===intent.target.commandId)||null:null,targetSide=intent.target?.side?{side:intent.target.side,label:context.sideLabels?.[intent.target.side]||intent.target.side}:intent.resolved?.side||null,terrain=intent.resolved?.terrain||[],terrainReference=terrain.length?{name:terrain[0].name,ids:terrain.filter(x=>norm(x.name)===norm(terrain[0].name)).map(x=>x.id)}:null;
  if(!raw)return{...intent,legacy,action:null,region:null,commands:[],targetCommand:null,targetSide:null,terrain:[],terrainReference:null,turn:null,postReleaseOrder:null,meaning:['No written override. Auto Tactical Planner may fill this mission.'],execution:[]};
  const errors=validateTacticalIntent(intent,context);if(errors.length){intent.unresolved.push(...errors);intent.status='blocked';}
  const turnPredicate=intent.releaseCondition?.type==='turn_reached'?intent.releaseCondition:(intent.releaseCondition?.conditions||[]).find(x=>x.type==='turn_reached');
  return{...intent,legacy,tacticalIntent:intent,action:intent.order,region:intent.target?.region||null,commands,targetCommand,targetSide,terrain,terrainReference,turn:turnPredicate?.turn||null,postReleaseOrder:intent.postReleaseOrder};
}

export function validateTacticalPlanWorkspace690(state){
  const issues=[],s=state.project?.scenario||{},w=state.playtestWorkspace||{};
  for(const side of ['sideA','sideB']){const row=w.armyOrders?.[side];if(row?.text){const x=interpretSemanticOrder690(row.text,state,{scope:'army',side});if(x.status==='blocked')issues.push({scope:'army',id:side,label:sideLabel(s,side),interpretation:x});}}
  for(const c of allCommands(s)){const row=w.commandOrders?.[c.id];if(row?.text){const x=interpretSemanticOrder690(row.text,state,{scope:'command',commandId:c.id,side:sideForFaction(c.faction)});if(x.status==='blocked')issues.push({scope:'command',id:c.id,label:c.name,interpretation:x});}}
  return issues;
}

export function markManualTacticalEdit690(state,element){
  if(element?.dataset?.armyPosture||element?.dataset?.armyText){const side=element.dataset.armyPosture||element.dataset.armyText,row=state.playtestWorkspace?.armyOrders?.[side];if(row)row.autoGenerated690=false;}
  if(element?.dataset?.commandOrder||element?.dataset?.commandText){const id=element.dataset.commandOrder||element.dataset.commandText,row=state.playtestWorkspace?.commandOrders?.[id];if(row)row.autoGenerated690=false;}
}

export function tacticalRequestContext690(state){const s=state.project?.scenario||{},plan=generateAutoTacticalPlan690(state);return{configuration:scenarioConfigFingerprint(state),metadata:s.metadata||{},sideLabels:s.sideLabels||{},ruleset:s.ruleset||{},victoryConditions:s.victoryText||'',scenarioRules:acceptedScenarioRules(s).map(x=>({id:x.id,title:x.title,text:x.text,engineStatus:x.engineStatus,engineText:x.engineText,automationStale:!!x.automationStale})),commands:allCommands(s).map(c=>({id:c.id,name:c.name,commandType:c.commandType||c.echelon||'command',parentCommandId:c.parentCommandId||null,commander:c.commander||'',commandRating:c.commandRating??null,side:sideForFaction(c.faction),units:(c.units||[]).map(u=>({id:u.id,name:u.name,profile:u.profile,traits:u.traits||[]})),deployment:commandCentroid(state,c),reserve:c.reserve||null})),approvedTerrain:(state.project?.features||[]).filter(f=>state.decisions?.[f.id]?.status==='approved').map(f=>({id:f.id,name:f.name,class:state.decisions?.[f.id]?.cls||f.cls,effects:state.decisions?.[f.id]?.effects||[],box:f.box||null})),currentWorkspace:structuredClone(state.playtestWorkspace||{}),localAutoPlan:plan};}

export { VALID_POSTURES, VALID_ORDERS };
