import { cp, mkdir, rm, copyFile, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');
await rm(dist, {recursive:true, force:true}); await mkdir(dist, {recursive:true});
await copyFile(path.join(root,'index.html'), path.join(dist,'index.html'));
await cp(path.join(root,'src'), path.join(dist,'src'), {recursive:true});
await cp(path.join(root,'public'), dist, {recursive:true});
await writeFile(path.join(dist,'.nojekyll'),'');
const html = await readFile(path.join(dist,'index.html'),'utf8');
if (!html.includes('Battle Axe Design Studio')) throw new Error('Build validation failed: title missing');
console.log('Built static GitHub Pages site in dist/');
