import { readFile, access } from 'node:fs/promises';
const files=['dist/index.html','dist/src/main.js','dist/src/modules/battlefieldDetector.js','dist/src/modules/deploymentEditor.js','dist/src/modules/playtestEngine.js','dist/src/modules/playtestCenter.js','dist/src/modules/aiBridge.js','dist/projects/pavia/battlefield.svg','dist/.nojekyll'];
for(const f of files) await access(new URL(`../${f}`,import.meta.url));
const detector=await readFile(new URL('../dist/src/modules/battlefieldDetector.js',import.meta.url),'utf8');
for(const token of ['#69D9E5','#F2AA84','syntheticOpening','rasterClassifiers','meaningfulInside','getCTM','rasterWall','rasterWood']) if(!detector.includes(token)) throw new Error(`Detector check failed: missing ${token}`);
const css=await readFile(new URL('../dist/src/styles/app.css',import.meta.url),'utf8');
for(const token of ['.map-panel{position:sticky','.deployment-layout','.deployment-zone-poly','.playtest-main','.ai-bridge']) if(!css.includes(token)) throw new Error(`CSS check failed: missing ${token}`);
const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8');
for(const token of ['ruleEditorDialog','deploymentMapFrame','addPolygonZone','playReplayFrame','runBatchPlaytest','aiBridgeDialog','data-add-command="French"']) if(!html.includes(token)) throw new Error(`UI check failed: missing ${token}`);
const engine=await readFile(new URL('../dist/src/modules/playtestEngine.js',import.meta.url),'utf8');
for(const token of ['runPlaytest','runBatch','commandTest','Artillery','surprise','garrisonTurn']) if(!engine.includes(token)) throw new Error(`Playtest adapter check failed: missing ${token}`);
console.log('Static deployment check passed.');
